<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="MSDE">
  <title>Big Data analytics / Applied Data analytics – GeoScience part 7: supplement</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="custom.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">GeoScience part 7: supplement</h1>
  <p class="subtitle">Validating spatial predictions</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
MSDE
</div>
        <p class="quarto-title-affiliation">
            Lviv University
          </p>
    </div>
</div>

</section>
<section>
<section id="validating-spatial-predictions" class="title-slide slide level1 center">
<h1>Validating spatial predictions</h1>

</section>
<section id="a-supplement-to-geo-7" class="slide level2 scrollable">
<h2>A supplement to Geo 7</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Not part of the book</strong></p>
</div>
<div class="callout-content">
<p>Geo 7 follows Part III of <em>Geographic Data Science with Python</em>. Those chapters fit spatial models and interpret their coefficients, but they never evaluate <strong>out-of-sample prediction</strong> — there is no cross-validation anywhere in them.</p>
<p>This supplement adds that missing step. It reuses Geo 7’s San Diego Airbnb data and baseline regression, and asks whether the accuracy such models report is as good as it looks.</p>
</div>
</div>
</div>
</section>
<section id="where-geo-7-left-off" class="slide level2 scrollable">
<h2>Where Geo 7 left off</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The baseline model and its residuals</strong></p>
</div>
<div class="callout-content">
<div id="86b3e363" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a aria-label="1"></a><span class="im">import</span> spreg</span>
<span id="cb1-2"><a aria-label="2"></a><span class="im">from</span> libpysal <span class="im">import</span> weights</span>
<span id="cb1-3"><a aria-label="3"></a></span>
<span id="cb1-4"><a aria-label="4"></a>db <span class="op">=</span> geopandas.read_file(<span class="ss">f"</span><span class="sc">{</span>GDS<span class="sc">}</span><span class="ss">/airbnb/regression_db.geojson"</span>)</span>
<span id="cb1-5"><a aria-label="5"></a>variable_names <span class="op">=</span> [</span>
<span id="cb1-6"><a aria-label="6"></a>    <span class="st">"accommodates"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"beds"</span>,</span>
<span id="cb1-7"><a aria-label="7"></a>    <span class="st">"rt_Private_room"</span>, <span class="st">"rt_Shared_room"</span>,</span>
<span id="cb1-8"><a aria-label="8"></a>    <span class="st">"pg_Condominium"</span>, <span class="st">"pg_House"</span>, <span class="st">"pg_Other"</span>, <span class="st">"pg_Townhouse"</span>,</span>
<span id="cb1-9"><a aria-label="9"></a>]</span>
<span id="cb1-10"><a aria-label="10"></a>m1 <span class="op">=</span> spreg.OLS(</span>
<span id="cb1-11"><a aria-label="11"></a>    db[[<span class="st">"log_price"</span>]].values, db[variable_names].values,</span>
<span id="cb1-12"><a aria-label="12"></a>    name_y<span class="op">=</span><span class="st">"log_price"</span>, name_x<span class="op">=</span>variable_names,</span>
<span id="cb1-13"><a aria-label="13"></a>)</span>
<span id="cb1-14"><a aria-label="14"></a>knn <span class="op">=</span> weights.KNN.from_dataframe(db, k<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb1-15"><a aria-label="15"></a>knn.transform <span class="op">=</span> <span class="st">"R"</span></span>
<span id="cb1-16"><a aria-label="16"></a>lag_u <span class="op">=</span> weights.spatial_lag.lag_spatial(knn, m1.u)</span>
<span id="cb1-17"><a aria-label="17"></a></span>
<span id="cb1-18"><a aria-label="18"></a><span class="bu">print</span>(<span class="ss">f"R2 (in-sample)                 = </span><span class="sc">{</span>m1<span class="sc">.</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-19"><a aria-label="19"></a><span class="bu">print</span>(<span class="ss">f"corr(residual, neighbours' lag) = </span><span class="sc">{</span>numpy<span class="sc">.</span>corrcoef(m1.u.flatten(), lag_u.flatten())[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R2 (in-sample)                 = 0.6683
corr(residual, neighbours' lag) = 0.3348</code></pre>
</div>
</div>
<p>The same model as in Geo 7: two-thirds of the variation in log price, and errors that cluster in space.</p>
</div>
</div>
</div>
</section>
<section id="the-question-nobody-asked" class="slide level2">
<h2>The question nobody asked</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Everything so far was in-sample</strong></p>
</div>
<div class="callout-content">
<p>Every <span class="math inline">\(R^2\)</span> in Geo 7 describes how well a model fits the data it was <strong>fitted on</strong>. For explanation that is defensible. For <strong>prediction</strong> it is not, and prediction is what you will usually be asked for.</p>
<p>The standard answer is cross-validation: hold out a fold, fit on the rest, score on the held-out part, repeat.</p>
<p>We are about to see that the standard answer <strong>does not work on spatial data</strong>, for a reason Geo 7 already established.</p>
</div>
</div>
</div>
</section>
<section id="recall-the-diagnostic" class="slide level2">
<h2>Recall the diagnostic</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>We measured this in Geo 7</strong></p>
</div>
<div class="callout-content">
<p>The regression’s residuals are spatially autocorrelated — correlation <strong>0.33</strong> with their 20-neighbour spatial lag, computed above. Nearby listings have similar prices <em>and</em> similar errors.</p>
<p>Now consider what random <span class="math inline">\(k\)</span>-fold cross-validation does with that. It shuffles rows and cuts them into five parts. Every test listing has, almost certainly, <strong>several of its immediate neighbours in the training set</strong>.</p>
<p>So the model is not predicting an unseen location. It is <strong>interpolating between points it has already seen</strong> — and interpolation is easy.</p>
</div>
</div>
</div>
</section>
<section id="this-is-leakage" class="slide level2">
<h2>This is leakage</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The same failure as Bio 2, in different clothing</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>not independent</th>
<th>random CV therefore</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>taxonomy</td>
<td>strains within a genus</td>
<td>tests on near-duplicates of training sequences</td>
</tr>
<tr class="even">
<td>single cell</td>
<td>cells within a donor</td>
<td>treats one donor as thousands of replicates</td>
</tr>
<tr class="odd">
<td><strong>geography</strong></td>
<td><strong>nearby places</strong></td>
<td><strong>tests on the interior of the training set</strong></td>
</tr>
</tbody>
</table>
<p>The rule is the same in all three: <strong>split at the level you want to generalise to.</strong> If you want to predict prices in a district you have no data for, your folds must be districts.</p>
</div>
</div>
</div>
</section>
<section id="setting-up-an-honest-test" class="slide level2 scrollable">
<h2>Setting up an honest test</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Features, target, and a projected CRS</strong></p>
</div>
<div class="callout-content">
<div id="41051aa4" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a aria-label="1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb3-2"><a aria-label="2"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score, KFold, GroupKFold</span>
<span id="cb3-3"><a aria-label="3"></a></span>
<span id="cb3-4"><a aria-label="4"></a>dbm <span class="op">=</span> db.to_crs(epsg<span class="op">=</span><span class="dv">3857</span>)          <span class="co"># metres, so blocks are metres</span></span>
<span id="cb3-5"><a aria-label="5"></a>xy <span class="op">=</span> numpy.column_stack((dbm.geometry.x, dbm.geometry.y))</span>
<span id="cb3-6"><a aria-label="6"></a>y <span class="op">=</span> dbm[<span class="st">"log_price"</span>].values</span>
<span id="cb3-7"><a aria-label="7"></a></span>
<span id="cb3-8"><a aria-label="8"></a>house <span class="op">=</span> [<span class="st">"accommodates"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"beds"</span>]</span>
<span id="cb3-9"><a aria-label="9"></a></span>
<span id="cb3-10"><a aria-label="10"></a></span>
<span id="cb3-11"><a aria-label="11"></a><span class="kw">def</span> rf():</span>
<span id="cb3-12"><a aria-label="12"></a>    <span class="cf">return</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">120</span>, random_state<span class="op">=</span><span class="dv">0</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb3-13"><a aria-label="13"></a></span>
<span id="cb3-14"><a aria-label="14"></a></span>
<span id="cb3-15"><a aria-label="15"></a><span class="kw">def</span> blocks(size):</span>
<span id="cb3-16"><a aria-label="16"></a>    <span class="co">"""Assign each listing to a square block of `size` metres."""</span></span>
<span id="cb3-17"><a aria-label="17"></a>    bx <span class="op">=</span> ((xy[:, <span class="dv">0</span>] <span class="op">-</span> xy[:, <span class="dv">0</span>].<span class="bu">min</span>()) <span class="op">//</span> size).astype(<span class="bu">int</span>)</span>
<span id="cb3-18"><a aria-label="18"></a>    by <span class="op">=</span> ((xy[:, <span class="dv">1</span>] <span class="op">-</span> xy[:, <span class="dv">1</span>].<span class="bu">min</span>()) <span class="op">//</span> size).astype(<span class="bu">int</span>)</span>
<span id="cb3-19"><a aria-label="19"></a>    <span class="cf">return</span> bx <span class="op">*</span> <span class="dv">10_000</span> <span class="op">+</span> by</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Reproject first.</strong> Blocks must be defined in metres; dividing degrees by 4000 is meaningless.</p>
</div>
</div>
</div>
</section>
<section id="isolating-the-leak" class="slide level2 scrollable">
<h2>Isolating the leak</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Three models, two validation schemes</strong></p>
</div>
<div class="callout-content">
<div id="a515d279" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a aria-label="1"></a>g <span class="op">=</span> blocks(<span class="dv">4000</span>)</span>
<span id="cb4-2"><a aria-label="2"></a>rows <span class="op">=</span> []</span>
<span id="cb4-3"><a aria-label="3"></a><span class="cf">for</span> name, X <span class="kw">in</span> [</span>
<span id="cb4-4"><a aria-label="4"></a>    (<span class="st">"coordinates only"</span>, xy),</span>
<span id="cb4-5"><a aria-label="5"></a>    (<span class="st">"house features only"</span>, dbm[house].values),</span>
<span id="cb4-6"><a aria-label="6"></a>    (<span class="st">"features + coordinates"</span>, numpy.column_stack([dbm[house].values, xy])),</span>
<span id="cb4-7"><a aria-label="7"></a>]:</span>
<span id="cb4-8"><a aria-label="8"></a>    r <span class="op">=</span> cross_val_score(rf(), X, y, cv<span class="op">=</span>KFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb4-9"><a aria-label="9"></a>                        scoring<span class="op">=</span><span class="st">"r2"</span>).mean()</span>
<span id="cb4-10"><a aria-label="10"></a>    b <span class="op">=</span> cross_val_score(rf(), X, y, cv<span class="op">=</span>GroupKFold(<span class="dv">5</span>), groups<span class="op">=</span>g, scoring<span class="op">=</span><span class="st">"r2"</span>).mean()</span>
<span id="cb4-11"><a aria-label="11"></a>    rows.append((name, r, b, r <span class="op">-</span> b))</span>
<span id="cb4-12"><a aria-label="12"></a></span>
<span id="cb4-13"><a aria-label="13"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'model'</span><span class="sc">:&lt;26}{</span><span class="st">'random'</span><span class="sc">:&gt;9}{</span><span class="st">'block'</span><span class="sc">:&gt;9}{</span><span class="st">'drop'</span><span class="sc">:&gt;8}</span><span class="ss">"</span>)</span>
<span id="cb4-14"><a aria-label="14"></a><span class="cf">for</span> n, r, b, d <span class="kw">in</span> rows:</span>
<span id="cb4-15"><a aria-label="15"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>n<span class="sc">:&lt;26}{</span>r<span class="sc">:&gt;9.3f}{</span>b<span class="sc">:&gt;9.3f}{</span>d<span class="sc">:&gt;8.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model                        random    block    drop
coordinates only              0.166   -0.103   0.270
house features only           0.607    0.583   0.024
features + coordinates        0.653    0.602   0.050</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="read-that-table-again" class="slide level2">
<h2>Read that table again</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The coordinates-only model is the proof</strong></p>
</div>
<div class="callout-content">
<p>Under random CV a model using <strong>nothing but latitude and longitude</strong> scores <span class="math inline">\(R^2 \approx 0.17\)</span>. It looks like it learned something about San Diego.</p>
<p>Under block CV the same model scores <strong>negative</strong> — worse than predicting the mean price for every listing.</p>
<p><strong>All of its apparent skill was memorising neighbours.</strong> Remove the neighbours from the training set and there is nothing left, because there was never anything there.</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And the contrast</strong></p>
</div>
<div class="callout-content">
<p><code>house features only</code> barely moves between the two schemes. Bedrooms and bathrooms are not spatial, so blocking costs nothing. The gap belongs to the coordinates, and only to them.</p>
</div>
</div>
</div>
</section>
<section id="how-big-are-the-blocks" class="slide level2 scrollable">
<h2>How big are the blocks?</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sweep the block size</strong></p>
</div>
<div class="callout-content">
<div id="cb89c7ac" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a aria-label="1"></a>X <span class="op">=</span> numpy.column_stack([dbm[house].values, xy])</span>
<span id="cb6-2"><a aria-label="2"></a>rand <span class="op">=</span> cross_val_score(rf(), X, y, cv<span class="op">=</span>KFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb6-3"><a aria-label="3"></a>                       scoring<span class="op">=</span><span class="st">"r2"</span>).mean()</span>
<span id="cb6-4"><a aria-label="4"></a></span>
<span id="cb6-5"><a aria-label="5"></a>sizes, scores <span class="op">=</span> [], []</span>
<span id="cb6-6"><a aria-label="6"></a><span class="cf">for</span> s <span class="kw">in</span> (<span class="dv">250</span>, <span class="dv">500</span>, <span class="dv">1000</span>, <span class="dv">2000</span>, <span class="dv">4000</span>, <span class="dv">8000</span>):</span>
<span id="cb6-7"><a aria-label="7"></a>    gg <span class="op">=</span> blocks(s)</span>
<span id="cb6-8"><a aria-label="8"></a>    <span class="cf">if</span> <span class="bu">len</span>(numpy.unique(gg)) <span class="op">&lt;</span> <span class="dv">5</span>:</span>
<span id="cb6-9"><a aria-label="9"></a>        <span class="cf">continue</span></span>
<span id="cb6-10"><a aria-label="10"></a>    sizes.append(s)</span>
<span id="cb6-11"><a aria-label="11"></a>    scores.append(cross_val_score(rf(), X, y, cv<span class="op">=</span>GroupKFold(<span class="dv">5</span>), groups<span class="op">=</span>gg,</span>
<span id="cb6-12"><a aria-label="12"></a>                                  scoring<span class="op">=</span><span class="st">"r2"</span>).mean())</span>
<span id="cb6-13"><a aria-label="13"></a></span>
<span id="cb6-14"><a aria-label="14"></a><span class="cf">for</span> s, sc <span class="kw">in</span> <span class="bu">zip</span>(sizes, scores):</span>
<span id="cb6-15"><a aria-label="15"></a>    <span class="bu">print</span>(<span class="ss">f"  block </span><span class="sc">{</span>s<span class="sc">:&gt;5}</span><span class="ss"> m : R2 = </span><span class="sc">{</span>sc<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb6-16"><a aria-label="16"></a><span class="bu">print</span>(<span class="ss">f"  random CV      : R2 = </span><span class="sc">{</span>rand<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb6-17"><a aria-label="17"></a></span>
<span id="cb6-18"><a aria-label="18"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">3</span>))</span>
<span id="cb6-19"><a aria-label="19"></a>ax.semilogx(sizes, scores, <span class="st">"o-"</span>, label<span class="op">=</span><span class="st">"block CV"</span>)</span>
<span id="cb6-20"><a aria-label="20"></a>ax.axhline(rand, ls<span class="op">=</span><span class="st">"--"</span>, color<span class="op">=</span><span class="st">"grey"</span>, label<span class="op">=</span><span class="st">"random CV"</span>)</span>
<span id="cb6-21"><a aria-label="21"></a>ax.set_xlabel(<span class="st">"block size (m)"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"$R^2$"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb6-22"><a aria-label="22"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  block   250 m : R2 = 0.656
  block   500 m : R2 = 0.641
  block  1000 m : R2 = 0.618
  block  2000 m : R2 = 0.632
  block  4000 m : R2 = 0.602
  block  8000 m : R2 = 0.568
  random CV      : R2 = 0.653</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="geo7_validation_files/figure-revealjs/cell-6-output-2.png" width="543" height="324"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="reading-the-curve" class="slide level2 scrollable">
<h2>Reading the curve</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What this curve actually shows</strong></p>
</div>
<div class="callout-content">
<p>Read the numbers, not the story you expected.</p>
<p><strong>At 250 m the block score equals random CV</strong> (0.656 vs 0.653). Blocks that small barely separate anything — a 250 m block still leaves neighbours in the training set. That agreement is a useful sanity check: it confirms the mechanism is distance, not the <code>GroupKFold</code> machinery.</p>
<p><strong>The trend is downward but not monotone.</strong> 1 000 m scores <em>below</em> 2 000 m here. With five folds over a few hundred blocks, each estimate carries real variance, and a single sweep is noisy. Repeat with several random block origins before reading much into any one point.</p>
<p><strong>It has not flattened by 8 km.</strong> San Diego spans roughly 40 km, so even 8 km blocks leave training listings fairly close to test ones. The honest conclusion is that we have not yet reached the distance at which leakage stops.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>So what do you report?</strong></p>
</div>
<div class="callout-content">
<p>Not a plateau, because we do not have one. Report the score <strong>at the block size matching your intended use</strong>: if you will predict 5 km from your nearest training data, the 4–8 km numbers are the relevant ones — around 0.57–0.60, against the 0.65 that random CV advertises.</p>
<p>The optimism here is modest precisely <em>because</em> most of this model’s signal is non-spatial. That is the reassuring case. The coordinates-only model a few slides back is the other one.</p>
</div>
</div>
</div>
</section>
<section id="buffered-leave-one-out" class="slide level2">
<h2>Buffered leave-one-out</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A stricter variant</strong></p>
</div>
<div class="callout-content">
<p>Blocks still put some test points right next to a block boundary, and so next to training data. <strong>Buffered LOO</strong> removes that: hold out one observation, and also <em>delete from the training set</em> everything within radius <span class="math inline">\(r\)</span> of it.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a aria-label="1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb8-2"><a aria-label="2"></a>    d <span class="op">=</span> distances_from(i)</span>
<span id="cb8-3"><a aria-label="3"></a>    train <span class="op">=</span> (d <span class="op">&gt;</span> buffer_radius)</span>
<span id="cb8-4"><a aria-label="4"></a>    model.fit(X[train], y[train])</span>
<span id="cb8-5"><a aria-label="5"></a>    pred[i] <span class="op">=</span> model.predict(X[[i]])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Expensive — one fit per observation — but it gives a clean answer to “how well do I predict at distance <span class="math inline">\(r\)</span> from any data?”, which is often the actual question.</p>
</div>
</div>
</div>
</section>
<section id="checking-the-residuals-again" class="slide level2">
<h2>Checking the residuals again</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Close the loop</strong></p>
</div>
<div class="callout-content">
<p>The residual diagnostic from Geo 7 is also the one that closes this lecture. After fitting any predictive model, compute Moran’s I on its residuals.</p>
<ul>
<li><strong>Significant autocorrelation remaining</strong> → there is spatial structure the model has not captured. Consider the spatial regression models and the engineered features from Geo 7.</li>
<li><strong>No autocorrelation</strong> → the spatial structure is accounted for, and the i.i.d. assumption behind your inference is defensible.</li>
</ul>
<p>It costs three lines and it is the single most informative check you can run on a spatial model.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center">
<h1>Wrap-up</h1>

</section>
<section id="what-we-covered" class="slide level2 scrollable">
<h2>What we covered</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Summary</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>idea</th>
<th>point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>in-sample fit</td>
<td>describes the data the model saw, not new locations</td>
</tr>
<tr class="even">
<td>random CV on spatial data</td>
<td><strong>leaks</strong>; the coordinates-only model went from 0.17 to negative</td>
</tr>
<tr class="odd">
<td>block CV</td>
<td>split at the level you want to generalise to</td>
</tr>
<tr class="even">
<td>block size</td>
<td>report the score at the distance you will actually predict at</td>
</tr>
<tr class="odd">
<td>residual Moran’s I</td>
<td>the check that says whether spatial structure is left over</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="the-thread" class="slide level2">
<h2>The thread</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One lesson, three courses</strong></p>
</div>
<div class="callout-content">
<p>Geo 5 and 6 taught you to <strong>measure</strong> spatial dependence. Geo 7 used it to <em>improve</em> models; this supplement used it to <em>distrust</em> them.</p>
<p>The second use is the transferable one. Spatial autocorrelation is a specific case of the general problem that observations are not independent — the same problem as related organisms in Bio 2 and cells from one donor in Bio 4.</p>
<blockquote>
<p>Before trusting a score, ask what the unit of independence actually is.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="exercises" class="slide level2 scrollable">
<h2>Exercises</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Try these</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Repeat the block-CV sweep with a linear model instead of a random forest. Does the optimism gap shrink? Why might a flexible model leak more?</li>
<li>Implement buffered leave-one-out for a subsample of 500 listings. Plot accuracy against buffer radius, and compare the shape to the block-size curve.</li>
<li>Split the data by <code>coastal</code> and use it as the CV group. Is predicting inland-from-coastal harder than predicting a random block? What does that tell you about transferability?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="further-reading" class="slide level2 scrollable">
<h2>Further reading</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sources</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Roberts et al.</strong>, <em>Cross-validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure</em>, <strong>Ecography</strong> 40(8), 2017. <a href="https://doi.org/10.1111/ecog.02881" class="uri">https://doi.org/10.1111/ecog.02881</a> — the standard reference for block cross-validation</li>
<li><strong>Ploton et al.</strong>, <em>Spatial validation reveals poor predictive performance of large-scale ecological mapping models</em>, <strong>Nature Communications</strong> 11, 2020. <a href="https://doi.org/10.1038/s41467-020-18321-y" class="uri">https://doi.org/10.1038/s41467-020-18321-y</a> — a high-profile demonstration of the optimism this lecture measures</li>
</ul>
</div>
</div>
</div>
</section>
<section id="projects" class="slide level2">
<h2>Projects</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>G4</strong></p>
</div>
<div class="callout-content">
<p>This supplement supplies the core of <strong>G4</strong> in the <a href="../projects.html">course projects</a>: predicting across space, and reporting the accuracy you can defend rather than the one that looks best.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="wrap-up-1" class="title-slide slide level1 center">
<h1>Wrap-up</h1>

</section>
<section id="what-we-covered-1" class="slide level2 scrollable">
<h2>What we covered</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Summary</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>idea</th>
<th>point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gini vs Theil</td>
<td>track each other (r = 0.944); their 1969→2017 “disagreement” is an endpoint choice — report trajectories</td>
</tr>
<tr class="even">
<td>Theil decomposition</td>
<td>regions converged to 1994 then partly diverged; within-region rose after the 1970s; the between-share fell from 31% to 12–20% and stayed there</td>
</tr>
<tr class="odd">
<td>decomposition and grouping</td>
<td>the between/within split is MAUP inside a statistic</td>
</tr>
<tr class="even">
<td>Moran’s I over time</td>
<td>income clustering weakened steadily, 0.649 → 0.421</td>
</tr>
<tr class="odd">
<td>clustering</td>
<td>groups with coherent profiles, found without labels</td>
</tr>
<tr class="even">
<td>scaling</td>
<td>distances depend on units — standardise before clustering</td>
</tr>
<tr class="odd">
<td>k-means and Ward</td>
<td>similar overall structure; both fragmented in space</td>
</tr>
<tr class="even">
<td>regionalization</td>
<td>clustering with a connectivity constraint; the weights define the constraint</td>
</tr>
<tr class="odd">
<td>coherence</td>
<td>regions are more compact but fit the features worse — an intrinsic trade-off</td>
</tr>
<tr class="even">
<td>hidden structure</td>
<td>the regression’s errors cluster in space; the i.i.d. assumption fails</td>
</tr>
<tr class="odd">
<td>proximity variables</td>
<td>distance to Balboa Park: not significant</td>
</tr>
<tr class="even">
<td>spatial fixed effects</td>
<td>let <span class="math inline">\(\alpha\)</span> vary by neighbourhood; coastal areas are the most expensive</td>
</tr>
<tr class="odd">
<td>spatial regimes</td>
<td>let <span class="math inline">\(\beta\)</span> vary too (coastal vs inland); the Chow test says they differ</td>
</tr>
<tr class="even">
<td>SLX</td>
<td>spatial lags of <span class="math inline">\(X\)</span>; direct (<span class="math inline">\(\beta\)</span>) and indirect (<span class="math inline">\(\gamma\)</span>) effects</td>
</tr>
<tr class="odd">
<td>spatial error, spatial lag</td>
<td><span class="math inline">\(\lambda\)</span> in the error, <span class="math inline">\(\rho\)</span> on the dependent variable — need GMM or 2SLS</td>
</tr>
<tr class="even">
<td>map matching</td>
<td>location links datasets: counts, raster samples, joins, interpolation</td>
</tr>
<tr class="odd">
<td>map synthesis</td>
<td>features from your own data: neighbour counts, spatial lags, rings, cluster labels</td>
</tr>
<tr class="even">
<td>extensive vs intensive</td>
<td>counts are apportioned, rates are averaged</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="exercises-1" class="slide level2 scrollable">
<h2>Exercises</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Try these</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Recompute the Theil decomposition grouping by <strong>state</strong> instead of census region. How much does the between-share change, and what does that tell you about the claim “most inequality is within regions”?</li>
<li>Compute <span class="math inline">\(\sigma\)</span>-convergence (the dispersion of county income over time) and compare it against rank mobility between 1969 and 2017. Do they tell the same story?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="questions-clustering-and-regionalization" class="slide level2 scrollable">
<h2>Questions: clustering and regionalization</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From the book</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>What disciplines employ regionalization? Cite concrete examples for each discipline you list.</li>
<li>Contrast and compare the concepts of <em>clusters</em> and <em>regions</em>.</li>
<li>In evaluating the quality of the solution to a regionalization problem, how might traditional measures of cluster evaluation be used? In what ways might those measures be limited and need expansion to consider the geographical dimensions of the problem?</li>
<li>Discuss the implications for the processes of regionalization that follow from the number of <em>connected components</em> in the spatial weights matrix that would be used.</li>
<li>Consider two weights matrices for a spatially constrained clustering problem. Both form a single connected component, but they differ in the sparsity of their adjacency graphs (think Rook being less dense than Queen).
<ol type="a">
<li>How might the sparsity of the weights matrix affect the quality of the clustering solution?</li>
<li>Using <code>libpysal.weights.higher_order</code>, construct a second-order adjacency matrix of the weights matrix used in this lecture.</li>
<li>Compare the <code>pct_nonzero</code> for both matrices.</li>
<li>Rerun the analysis with the second-order weights matrix. What changes?</li>
</ol></li>
<li>How might solutions to clustering and regionalization problems change if spatial dependence is very strong and positive? Very weak? Very strong and negative?</li>
<li>Using <code>w = libpysal.weights.lat2W(20, 20)</code>, how many unique ways are there to partition the graph into 20 clusters of 20 units each, with every cluster a connected component? And for <code>lat2W(20, 20, rook=False)</code>?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="questions-spatial-regression" class="slide level2 scrollable">
<h2>Questions: spatial regression</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From the book</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>The “Spatial Durbin Model” combines the SLX model with the spatial lag model; the “Spatial Durbin Error Model” combines SLX with the spatial error model. Fit a Spatial Durbin variant of the models in this lecture.
<ul>
<li>Do these variants improve the model fit?</li>
<li>What happens to the spatial autocorrelation parameters (<span class="math inline">\(\rho\)</span>, <span class="math inline">\(\lambda\)</span>) when the SLX term is added? Why might this occur?</li>
</ul></li>
<li>Spatial error models recover the same estimates (asymptotically) as OLS, but their confidence intervals change, because OLS miscalculates them under spatial correlation and/or heteroskedasticity. How much do the confidence intervals change when the spatial error model is fit?</li>
<li>A common justification for the SLX model (and the Durbin variants) is <em>omitted, spatially patterned variables</em>: if an omitted variable is associated with the included variables <em>and</em> is spatially patterned, the spatial structure of the included variables can mimic it. In the spatial lag model:
<ul>
<li>what variables might be missing that matter for predicting the price of an Airbnb?</li>
<li>would they have a spatial pattern similar to the included variables? Why or why not?</li>
</ul></li>
<li><em>Spatial</em> regression focuses on how nearby observations are similar; <em>platial</em> models — multi-level or spatial mixed-effect models — focus on how observations in the same spatial group are similar. When do these two ideas work well together, and when might they disagree?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="questions-spatial-feature-engineering" class="slide level2 scrollable">
<h2>Questions: spatial feature engineering</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From the book</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Thinking of your own work, give an example where map matching would be a useful spatial feature engineering approach. And one where map synthesis would be useful.</li>
<li>In the counting-nearby-features example, some listings may have their nearby bars and restaurants <strong>under-counted</strong>. Which ones, and why?</li>
<li>How would you correct that under-count?</li>
<li>Dasymetric mapping may introduce spurious spatial autocorrelation through the interpolation process. How does this occur, and why is it important to acknowledge?</li>
<li>Is the SLX model from the regression section a map matching or a map synthesis technique?</li>
<li>Feature engineering can be used in many applied contexts. When might it actually <em>not</em> improve a model?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="further-reading-1" class="slide level2 scrollable">
<h2>Further reading</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sources</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Rey, Arribas-Bel &amp; Wolf</strong>, <em>Geographic Data Science with Python</em>, CRC Press, 2023 — <strong>Part III in full</strong>, chs.&nbsp;9–12. <a href="https://geographicdata.science" class="uri">https://geographicdata.science</a></li>
<li><strong>Shorrocks</strong>, <em>The class of additively decomposable inequality measures</em>, <strong>Econometrica</strong> 48(3), 1980. <a href="https://doi.org/10.2307/1913126" class="uri">https://doi.org/10.2307/1913126</a> — why Theil decomposes and Gini does not</li>
<li><strong>Cowell</strong>, <em>Measuring Inequality</em>, 3rd ed., Oxford University Press, 2011 — the standard text, free from the author</li>
<li><strong>Rey &amp; Janikas</strong>, <em>Regional convergence, inequality, and space</em>, <strong>Journal of Economic Geography</strong> 5(2), 2005. <a href="https://doi.org/10.1093/jnlecg/lbh044" class="uri">https://doi.org/10.1093/jnlecg/lbh044</a> — the spatial treatment of convergence</li>
<li><strong>Duque, Ramos &amp; Suriñach</strong>, <em>Supervised regionalization methods: a survey</em>, <strong>International Regional Science Review</strong> 30(3), 2007. <a href="https://doi.org/10.1177/0160017607301605" class="uri">https://doi.org/10.1177/0160017607301605</a></li>
<li><code>inequality</code> — <a href="https://pysal.org/inequality/" class="uri">https://pysal.org/inequality/</a> — Gini, Theil and their spatial variants</li>
<li><strong>Anselin</strong>, <em>Spatial Econometrics: Methods and Models</em>, Kluwer, 1988 — the standard reference for the lag and error models</li>
<li><strong>Anselin &amp; Rey</strong>, <em>Modern Spatial Econometrics in Practice</em>, GeoDa Press, 2014</li>
<li><strong>Gelman &amp; Hill</strong>, <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>, Cambridge, 2007 — chs.&nbsp;3–4 for the non-spatial foundation</li>
<li><strong>James, Witten, Hastie &amp; Tibshirani</strong>, <em>An Introduction to Statistical Learning</em>, 2nd ed., 2021 — the book’s recommended next step for clustering and for machine learning generally</li>
<li><code>spreg</code> documentation — <a href="https://pysal.org/spreg/" class="uri">https://pysal.org/spreg/</a></li>
<li><code>tobler</code> for areal interpolation — <a href="https://pysal.org/tobler/" class="uri">https://pysal.org/tobler/</a></li>
</ul>
</div>
</div>
</div>
</section>
<section id="coming-next" class="slide level2">
<h2>Coming next</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Validation, and the projects</strong></p>
</div>
<div class="callout-content">
<p><strong><a href="../2026/geo7_validation.html">Validating spatial predictions</a></strong> is a supplement to this lecture: Part III never evaluates out-of-sample prediction, and the supplement shows why ordinary cross-validation overstates accuracy on spatial data.</p>
<p>For the <a href="../projects.html">course projects</a>: the regression and feature-engineering sections feed <strong>G1</strong> and <strong>G4</strong>, the inequality section feeds <strong>G8</strong>, and regionalization feeds <strong>G9</strong>. G4’s cross-validation is in the supplement.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/socket.io.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/multiplex.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'multiplex': {"url":"https://mplex.vitv.ly","secret":null,"id":"c8a51011f0dd683d18fef43bd11c8fae8395c0603cfeb0999a4f3c93b7572741"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dslnu\.github\.io\/data_analytics\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>