project:
  type: website

website:
  title: "Big Data analytics / Applied Data analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bigdata.qmd
        text: Big Data analytics
      - href: applied.qmd
        text: Applied Data analytics
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



