<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="MSDE">
  <title>Big Data analytics / Applied Data analytics – Bioinformatics 2</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="custom.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Bioinformatics 2</h1>
  <p class="subtitle">Homology search and classification</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
MSDE
</div>
        <p class="quarto-title-affiliation">
            Lviv University
          </p>
    </div>
</div>

</section>
<section id="homology-search" class="slide level2">
<h2>Homology search</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Source</strong></p>
</div>
<div class="callout-content">
<p><strong>An Introduction to Applied Bioinformatics</strong> (2nd ed.), Caporaso — <a href="https://readiab.org" class="uri">https://readiab.org</a>, CC BY-NC-SA 4.0.</p>
<p>Chapters 4–5: <em>Sequence homology searching</em> and <em>Machine learning in bioinformatics</em>.</p>
</div>
</div>
</div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Where we left off</strong></p>
</div>
<div class="callout-content">
<p>Smith-Waterman gives the <strong>provably optimal</strong> local alignment in <span class="math inline">\(O(mn)\)</span>. We measured ~5 ns per matrix cell.</p>
<p>A single query against GenBank’s <span class="math inline">\(\sim 10^{12}\)</span> bases is <span class="math inline">\(\sim 10^{15}\)</span> cells — <strong>over a month of compute</strong>, for one search.</p>
<p>This lecture is about the two things the field does instead: <strong>skip most of the matrix</strong>, and <strong>replace alignment with classification</strong>.</p>
</div>
</div>
</div>
</section>
<section id="roadmap" class="slide level2">
<h2>Roadmap</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Two halves</strong></p>
</div>
<div class="callout-content">
<p><strong>Homology search</strong></p>
<ul>
<li>what the database-search problem actually is</li>
<li>heuristics: <span class="math inline">\(k\)</span>-mer seeds, and what they give up</li>
<li>evaluating a heuristic: sensitivity, specificity, E-values</li>
</ul>
<p><strong>Machine learning</strong></p>
<ul>
<li><span class="math inline">\(k\)</span>-mers as features</li>
<li>Naive Bayes for taxonomic classification</li>
<li>cross-validation, and the trap that makes results look perfect</li>
</ul>
</div>
</div>
</div>
<!-- ==========================================================================
     SOURCE: readIAB ch.4 "Sequence homology searching"
             https://readiab.org/database-searching.html
             sections: "Defining the problem", "A complete homology search function"
     ========================================================================== -->
</section>
<section>
<section id="the-search-problem" class="title-slide slide level1 center">
<h1>The search problem</h1>

</section>
<section id="defining-the-problem" class="slide level2">
<h2>Defining the problem</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What we are actually asking</strong></p>
</div>
<div class="callout-content">
<blockquote>
<p>Given a <strong>query</strong> sequence of unknown function, find sequences in an annotated <strong>reference database</strong> that are homologous to it — and transfer their annotations as a hypothesis about the query.</p>
</blockquote>
<p>This is how most sequences ever get a function assigned. Nobody characterised them experimentally; they resemble something that <em>was</em> characterised.</p>
<p>The whole enterprise rests on one inference: <strong>sequence similarity implies shared ancestry implies shared function.</strong> Each of those implications can fail.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "Defining the problem" -- the homology vocabulary
     is used throughout the chapter and assumed known -->
</section>
<section id="homolog-ortholog-paralog" class="slide level2">
<h2>Homolog, ortholog, paralog</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Three words that get used interchangeably and should not be</strong></p>
</div>
<div class="callout-content">
<p><strong>Homologous</strong> — descended from a common ancestral sequence. This is a claim about <em>history</em>, and it is binary: two sequences either share an ancestor or they do not. There is no such thing as “40% homologous”.</p>
<p>Two ways homologs arise, and the distinction matters for what you may conclude:</p>
<ul>
<li><strong>orthologs</strong> — separated by a <em>speciation</em> event. Human and mouse haemoglobin. Usually retain the same function, because each species kept one copy doing the same job.</li>
<li><strong>paralogs</strong> — separated by a <em>duplication</em> within a lineage. Human haemoglobin and myoglobin. One copy is free to drift, so function often diverges.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this is a search problem, not a vocabulary problem</strong></p>
</div>
<div class="callout-content">
<p>Your best BLAST hit may be a <strong>paralog</strong>. You will then transfer an annotation from a gene that shares ancestry with your query but no longer does the same thing — and nothing in the output warns you.</p>
</div>
</div>
</div>
</section>
<section id="similar-is-not-homologous" class="slide level2">
<h2>Similar is not homologous</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The inference chain, and where each link breaks</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\text{similarity} \Rightarrow \text{common ancestry} \Rightarrow \text{shared function}\]</span></p>
<p><strong>Link 1 fails</strong> through <em>convergence</em> and through <em>composition</em>. Two unrelated proteins can arrive at similar sequence independently, and two AT-rich sequences look similar because they are AT-rich. Low-complexity regions — poly-glutamine, repeats — generate high-scoring alignments between things that have nothing to do with each other. This is why BLAST masks them by default (<code>dust</code>, <code>seg</code>).</p>
<p><strong>Link 2 fails</strong> through paralogy, through domain shuffling (two proteins sharing one module and nothing else), and through genuine functional divergence after duplication.</p>
<p>The chain is still the best tool available. It is just not a proof, and the output format — a confident table of percentages — makes it look like one.</p>
</div>
</div>
</div>
</section>
<section id="the-database-has-its-own-problems" class="slide level2">
<h2>The database has its own problems</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What you are searching against</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Redundancy.</strong> GenBank contains the same gene thousands of times from thousands of strains. A “hit list” of 500 sequences may be 500 copies of one finding. This is why RefSeq and UniRef exist: curated, de-duplicated subsets.</li>
<li><strong>Annotation is mostly inferred, not measured.</strong> The overwhelming majority of sequence annotations were themselves assigned by homology search. Transfer an annotation and you are often copying a copy.</li>
<li><strong>Errors propagate and amplify.</strong> A misannotation becomes the best hit for the next query, which inherits it, which becomes evidence for the next. The literature calls this <em>annotation error percolation</em>, and it is measurable in the databases.</li>
<li><strong>Sampling is biased.</strong> Reference databases over-represent organisms that are easy to culture and interesting to fund. An environmental sample is mostly things nobody has sequenced.</li>
</ul>
<p>Every one of these makes your results look <em>better</em> than they are, never worse.</p>
</div>
</div>
</div>
</section>
<section id="the-cost" class="slide level2 scrollable">
<h2>The cost</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exhaustive search, measured</strong></p>
</div>
<div class="callout-content">
<div id="30b3aa1a" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a aria-label="1"></a><span class="im">import</span> timeit</span>
<span id="cb1-2"><a aria-label="2"></a></span>
<span id="cb1-3"><a aria-label="3"></a>aligner <span class="op">=</span> PairwiseAligner(mode<span class="op">=</span><span class="st">"local"</span>, match_score<span class="op">=</span><span class="dv">2</span>, mismatch_score<span class="op">=-</span><span class="dv">3</span>,</span>
<span id="cb1-4"><a aria-label="4"></a>                          open_gap_score<span class="op">=-</span><span class="dv">5</span>, extend_gap_score<span class="op">=-</span><span class="dv">2</span>)</span>
<span id="cb1-5"><a aria-label="5"></a></span>
<span id="cb1-6"><a aria-label="6"></a>query <span class="op">=</span> random_seq(<span class="dv">300</span>)</span>
<span id="cb1-7"><a aria-label="7"></a>database <span class="op">=</span> [random_seq(<span class="dv">300</span>) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">200</span>)]</span>
<span id="cb1-8"><a aria-label="8"></a></span>
<span id="cb1-9"><a aria-label="9"></a>t <span class="op">=</span> <span class="bu">min</span>(timeit.repeat(</span>
<span id="cb1-10"><a aria-label="10"></a>    <span class="kw">lambda</span>: [aligner.align(query, s).score <span class="cf">for</span> s <span class="kw">in</span> database],</span>
<span id="cb1-11"><a aria-label="11"></a>    number<span class="op">=</span><span class="dv">2</span>, repeat<span class="op">=</span><span class="dv">3</span>)) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb1-12"><a aria-label="12"></a></span>
<span id="cb1-13"><a aria-label="13"></a>per_seq <span class="op">=</span> t <span class="op">/</span> <span class="bu">len</span>(database)</span>
<span id="cb1-14"><a aria-label="14"></a><span class="bu">print</span>(<span class="ss">f"  200 sequences      : </span><span class="sc">{</span>t <span class="op">*</span> <span class="dv">1000</span><span class="sc">:.1f}</span><span class="ss"> ms"</span>)</span>
<span id="cb1-15"><a aria-label="15"></a><span class="bu">print</span>(<span class="ss">f"  per comparison     : </span><span class="sc">{</span>per_seq <span class="op">*</span> <span class="fl">1e6</span><span class="sc">:.1f}</span><span class="ss"> us"</span>)</span>
<span id="cb1-16"><a aria-label="16"></a><span class="bu">print</span>(<span class="ss">f"  extrapolated to 10^8 sequences: </span><span class="sc">{</span>per_seq <span class="op">*</span> <span class="fl">1e8</span> <span class="op">/</span> <span class="dv">3600</span><span class="sc">:.1f}</span><span class="ss"> hours"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  200 sequences      : 210.6 ms
  per comparison     : 1053.0 us
  extrapolated to 10^8 sequences: 29.2 hours</code></pre>
</div>
</div>
<p>And that is with a <strong>C implementation</strong> on short sequences. The real database is larger and the real sequences are longer.</p>
</div>
</div>
</div>
</section>
<section id="the-shape-of-the-solution" class="slide level2">
<h2>The shape of the solution</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Do not align what cannot match</strong></p>
</div>
<div class="callout-content">
<p>Two homologous sequences share <strong>exact short substrings</strong> almost certainly. Two unrelated sequences share far fewer, and only by chance.</p>
<p>So: use a cheap, approximate test to discard the vast majority of the database, and run the expensive exact alignment only on what survives.</p>
<p><span class="math display">\[\text{cheap filter} \rightarrow \text{small candidate set} \rightarrow \text{exact alignment}\]</span></p>
<p>This is <strong>seed-and-extend</strong>, and it is the core idea of BLAST. It is also the same shape as the sampling and approximation strategies in the scheduling lectures: give up a guarantee, buy several orders of magnitude.</p>
</div>
</div>
</div>
</section>
<section id="k-mer-similarity" class="slide level2 scrollable">
<h2><span class="math inline">\(k\)</span>-mer similarity</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Jaccard index over <span class="math inline">\(k\)</span>-mer sets</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[J(A, B) = \frac{|A \cap B|}{|A \cup B|}\]</span></p>
<p>where <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are the sets of <span class="math inline">\(k\)</span>-mers in each sequence. No alignment, no matrix — two set operations.</p>
<div id="9b7674cc" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a aria-label="1"></a><span class="kw">def</span> kmers(s, k<span class="op">=</span><span class="dv">5</span>):</span>
<span id="cb3-2"><a aria-label="2"></a>    <span class="cf">return</span> {s[i : i <span class="op">+</span> k] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(s) <span class="op">-</span> k <span class="op">+</span> <span class="dv">1</span>)}</span>
<span id="cb3-3"><a aria-label="3"></a></span>
<span id="cb3-4"><a aria-label="4"></a></span>
<span id="cb3-5"><a aria-label="5"></a><span class="kw">def</span> jaccard(a, b):</span>
<span id="cb3-6"><a aria-label="6"></a>    <span class="cf">return</span> <span class="bu">len</span>(a <span class="op">&amp;</span> b) <span class="op">/</span> <span class="bu">len</span>(a <span class="op">|</span> b) <span class="cf">if</span> (a <span class="op">|</span> b) <span class="cf">else</span> <span class="fl">0.0</span></span>
<span id="cb3-7"><a aria-label="7"></a></span>
<span id="cb3-8"><a aria-label="8"></a></span>
<span id="cb3-9"><a aria-label="9"></a>base <span class="op">=</span> random_seq(<span class="dv">300</span>)</span>
<span id="cb3-10"><a aria-label="10"></a>candidates <span class="op">=</span> [(<span class="st">"diverged 2%"</span>, mutate(base, <span class="fl">0.02</span>)),</span>
<span id="cb3-11"><a aria-label="11"></a>              (<span class="st">"diverged 5%"</span>, mutate(base, <span class="fl">0.05</span>)),</span>
<span id="cb3-12"><a aria-label="12"></a>              (<span class="st">"diverged 10%"</span>, mutate(base, <span class="fl">0.10</span>)),</span>
<span id="cb3-13"><a aria-label="13"></a>              (<span class="st">"diverged 20%"</span>, mutate(base, <span class="fl">0.20</span>)),</span>
<span id="cb3-14"><a aria-label="14"></a>              (<span class="st">"diverged 35%"</span>, mutate(base, <span class="fl">0.35</span>))] <span class="op">+</span> <span class="op">\</span></span>
<span id="cb3-15"><a aria-label="15"></a>             [(<span class="st">"unrelated"</span>, random_seq(<span class="dv">300</span>)) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>)]</span>
<span id="cb3-16"><a aria-label="16"></a></span>
<span id="cb3-17"><a aria-label="17"></a>qk <span class="op">=</span> kmers(base)</span>
<span id="cb3-18"><a aria-label="18"></a><span class="bu">print</span>(<span class="st">"  relationship    jaccard   SW score"</span>)</span>
<span id="cb3-19"><a aria-label="19"></a>rows <span class="op">=</span> []</span>
<span id="cb3-20"><a aria-label="20"></a><span class="cf">for</span> label, s <span class="kw">in</span> candidates:</span>
<span id="cb3-21"><a aria-label="21"></a>    j, sw <span class="op">=</span> jaccard(qk, kmers(s)), aligner.align(base, s).score</span>
<span id="cb3-22"><a aria-label="22"></a>    rows.append((label, j, sw))</span>
<span id="cb3-23"><a aria-label="23"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>label<span class="sc">:&lt;14}</span><span class="ss"> </span><span class="sc">{</span>j<span class="sc">:7.3f}</span><span class="ss">   </span><span class="sc">{</span>sw<span class="sc">:8.0f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  relationship    jaccard   SW score
  diverged 2%      0.911        585
  diverged 5%      0.633        515
  diverged 10%     0.577        472
  diverged 20%     0.366        353
  diverged 35%     0.247        193
  unrelated        0.156         17
  unrelated        0.151         16
  unrelated        0.160         16
  unrelated        0.192         17</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="k-mer-similarity-1" class="slide level2 scrollable">
<h2><span class="math inline">\(k\)</span>-mer similarity</h2>
<div id="d638e652" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a aria-label="1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="fl">3.6</span>))</span>
<span id="cb5-2"><a aria-label="2"></a>js <span class="op">=</span> [r[<span class="dv">1</span>] <span class="cf">for</span> r <span class="kw">in</span> rows]<span class="op">;</span> sws <span class="op">=</span> [r[<span class="dv">2</span>] <span class="cf">for</span> r <span class="kw">in</span> rows]</span>
<span id="cb5-3"><a aria-label="3"></a>homolog <span class="op">=</span> [<span class="st">"unrelated"</span> <span class="kw">not</span> <span class="kw">in</span> r[<span class="dv">0</span>] <span class="cf">for</span> r <span class="kw">in</span> rows]</span>
<span id="cb5-4"><a aria-label="4"></a>ax.scatter([j <span class="cf">for</span> j, h <span class="kw">in</span> <span class="bu">zip</span>(js, homolog) <span class="cf">if</span> h],</span>
<span id="cb5-5"><a aria-label="5"></a>           [s <span class="cf">for</span> s, h <span class="kw">in</span> <span class="bu">zip</span>(sws, homolog) <span class="cf">if</span> h], label<span class="op">=</span><span class="st">"homologs"</span>, s<span class="op">=</span><span class="dv">40</span>)</span>
<span id="cb5-6"><a aria-label="6"></a>ax.scatter([j <span class="cf">for</span> j, h <span class="kw">in</span> <span class="bu">zip</span>(js, homolog) <span class="cf">if</span> <span class="kw">not</span> h],</span>
<span id="cb5-7"><a aria-label="7"></a>           [s <span class="cf">for</span> s, h <span class="kw">in</span> <span class="bu">zip</span>(sws, homolog) <span class="cf">if</span> <span class="kw">not</span> h], label<span class="op">=</span><span class="st">"unrelated"</span>, s<span class="op">=</span><span class="dv">40</span>, marker<span class="op">=</span><span class="st">"x"</span>)</span>
<span id="cb5-8"><a aria-label="8"></a>ax.set_xlabel(<span class="st">"Jaccard index of 5-mer sets"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"Smith-Waterman score"</span>)</span>
<span id="cb5-9"><a aria-label="9"></a>ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-5-output-1.png" width="543" height="390"></p>
</figure>
</div>
</div>
</div>
<p>The cheap statistic <strong>ranks the same way</strong> as the expensive one. Homologs sit above Jaccard ~0.2; unrelated sequences cluster near 0.15. A threshold there discards most of a database for essentially no cost.</p>
</section>
<section id="what-the-heuristic-gives-up" class="slide level2">
<h2>What the heuristic gives up</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>It is not a proof</strong></p>
</div>
<div class="callout-content">
<p>Look again at the “diverged 35%” row. Its Jaccard is close to the unrelated ones — a threshold tuned to exclude noise will also <strong>exclude a genuine homolog</strong>.</p>
<p>That is the trade in one line: <em>heuristics lose distant homologs</em>, and distant homologs are often the interesting ones.</p>
<ul>
<li>for close matches, the heuristic and the exact algorithm agree</li>
<li>for remote homology, only exhaustive search finds it, and nobody can afford exhaustive search</li>
</ul>
<p>Specialised tools (PSI-BLAST, HMMER profile methods) exist precisely to push the detection limit further out.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "Reducing the runtime for database searches"
     https://readiab.org/database-searching.html -->
</section>
<section id="an-inverted-index" class="slide level2 scrollable">
<h2>An inverted index</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Precompute the database, not the query</strong></p>
</div>
<div class="callout-content">
<p>Jaccard still compares the query against <em>every</em> reference. The real saving comes from <strong>inverting</strong> the problem: build a map from <span class="math inline">\(k\)</span>-mer to the sequences containing it, once, offline.</p>
<div id="5c23fca7" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a aria-label="1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb6-2"><a aria-label="2"></a></span>
<span id="cb6-3"><a aria-label="3"></a>db_seqs <span class="op">=</span> {<span class="ss">f"ref_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">"</span>: random_seq(<span class="dv">300</span>) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">200</span>)}</span>
<span id="cb6-4"><a aria-label="4"></a>db_seqs[<span class="st">"ref_homolog"</span>] <span class="op">=</span> mutate(base, <span class="fl">0.08</span>)</span>
<span id="cb6-5"><a aria-label="5"></a></span>
<span id="cb6-6"><a aria-label="6"></a>index <span class="op">=</span> defaultdict(<span class="bu">set</span>)</span>
<span id="cb6-7"><a aria-label="7"></a><span class="cf">for</span> name, seq <span class="kw">in</span> db_seqs.items():</span>
<span id="cb6-8"><a aria-label="8"></a>    <span class="cf">for</span> km <span class="kw">in</span> kmers(seq):</span>
<span id="cb6-9"><a aria-label="9"></a>        index[km].add(name)</span>
<span id="cb6-10"><a aria-label="10"></a></span>
<span id="cb6-11"><a aria-label="11"></a><span class="bu">print</span>(<span class="ss">f"  database     : </span><span class="sc">{</span><span class="bu">len</span>(db_seqs)<span class="sc">}</span><span class="ss"> sequences"</span>)</span>
<span id="cb6-12"><a aria-label="12"></a><span class="bu">print</span>(<span class="ss">f"  index entries: </span><span class="sc">{</span><span class="bu">len</span>(index)<span class="sc">}</span><span class="ss"> distinct 5-mers"</span>)</span>
<span id="cb6-13"><a aria-label="13"></a><span class="bu">print</span>(<span class="ss">f"  avg postings : </span><span class="sc">{</span>np<span class="sc">.</span>mean([<span class="bu">len</span>(v) <span class="cf">for</span> v <span class="kw">in</span> index.values()])<span class="sc">:.1f}</span><span class="ss"> sequences per k-mer"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  database     : 201 sequences
  index entries: 1024 distinct 5-mers
  avg postings : 50.4 sequences per k-mer</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="an-inverted-index-1" class="slide level2 scrollable">
<h2>An inverted index</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Querying it</strong></p>
</div>
<div class="callout-content">
<div id="28b38d75" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a aria-label="1"></a><span class="kw">def</span> candidates(query, index, min_shared<span class="op">=</span><span class="dv">20</span>):</span>
<span id="cb8-2"><a aria-label="2"></a>    hits <span class="op">=</span> defaultdict(<span class="bu">int</span>)</span>
<span id="cb8-3"><a aria-label="3"></a>    <span class="cf">for</span> km <span class="kw">in</span> kmers(query):</span>
<span id="cb8-4"><a aria-label="4"></a>        <span class="cf">for</span> name <span class="kw">in</span> index.get(km, ()):</span>
<span id="cb8-5"><a aria-label="5"></a>            hits[name] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb8-6"><a aria-label="6"></a>    <span class="cf">return</span> {n: c <span class="cf">for</span> n, c <span class="kw">in</span> hits.items() <span class="cf">if</span> c <span class="op">&gt;=</span> min_shared}</span>
<span id="cb8-7"><a aria-label="7"></a></span>
<span id="cb8-8"><a aria-label="8"></a></span>
<span id="cb8-9"><a aria-label="9"></a>found <span class="op">=</span> candidates(base, index)</span>
<span id="cb8-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="ss">f"  candidates surviving the filter: </span><span class="sc">{</span><span class="bu">len</span>(found)<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(db_seqs)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-11"><a aria-label="11"></a><span class="cf">for</span> name, shared <span class="kw">in</span> <span class="bu">sorted</span>(found.items(), key<span class="op">=</span><span class="kw">lambda</span> kv: <span class="op">-</span>kv[<span class="dv">1</span>])[:<span class="dv">5</span>]:</span>
<span id="cb8-12"><a aria-label="12"></a>    <span class="bu">print</span>(<span class="ss">f"    </span><span class="sc">{</span>name<span class="sc">:&lt;14}</span><span class="ss"> shares </span><span class="sc">{</span>shared<span class="sc">:&gt;3}</span><span class="ss"> k-mers"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  candidates surviving the filter: 201 of 201
    ref_homolog    shares 217 k-mers
    ref_183        shares  93 k-mers
    ref_46         shares  89 k-mers
    ref_136        shares  89 k-mers
    ref_164        shares  87 k-mers</code></pre>
</div>
</div>
<p>The filter reduced the alignment workload by orders of magnitude, and the true homolog is at the top. <strong>This is the data structure inside every fast aligner</strong> — BLAST, DIAMOND, minimap2, kraken.</p>
</div>
</div>
</div>
</section>
<section id="cost-of-the-index" class="slide level2">
<h2>Cost of the index</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What you pay, and when</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>build</th>
<th>query</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>exhaustive alignment</td>
<td>nothing</td>
<td><span class="math inline">\(O(N \cdot mn)\)</span></td>
</tr>
<tr class="even">
<td>inverted index</td>
<td><span class="math inline">\(O(N \cdot m)\)</span> once</td>
<td><span class="math inline">\(O(m + \lvert\text{hits}\rvert)\)</span></td>
</tr>
</tbody>
</table>
<p>The index is built <strong>once</strong> and amortised over every subsequent search — which is exactly why NCBI can serve BLAST to the world, and why you <code>makeblastdb</code> before you <code>blastn</code>.</p>
<p>The memory cost is real: an index over <span class="math inline">\(10^{12}\)</span> bases does not fit on a laptop, which is why tools like DIAMOND and minimap2 spend most of their engineering on <em>compressing</em> the index (minimizers, spaced seeds, FM-index) rather than on the alignment itself.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "Heuristic algorithms" -->
</section>
<section id="how-blast-actually-works" class="slide level2">
<h2>How BLAST actually works</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Seed, extend, evaluate</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Index</strong> the database by <span class="math inline">\(k\)</span>-mer (word size 11 for nucleotides, 3 for proteins) — done once, offline.</li>
<li><strong>Seed</strong> — look up the query’s words to find exact hits. For proteins, also include <em>neighbourhood</em> words scoring above a threshold under BLOSUM62, so a conservative substitution still seeds.</li>
<li><strong>Extend</strong> — grow each seed in both directions, stopping when the score drops more than <span class="math inline">\(X\)</span> below its maximum.</li>
<li><strong>Evaluate</strong> — keep extensions above a threshold and report them with a statistical significance estimate.</li>
</ol>
<p>Almost all of the <span class="math inline">\(O(mn)\)</span> matrix is never touched. That is where the speed comes from.</p>
</div>
</div>
</div>
</section>
<section id="word-size-is-the-main-dial" class="slide level2">
<h2>Word size is the main dial</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One parameter controls the whole trade-off</strong></p>
</div>
<div class="callout-content">
<p>A seed must be an <strong>exact</strong> match of length <span class="math inline">\(w\)</span>. So the probability that a homologous region seeds at all is roughly <span class="math inline">\(p^{w}\)</span>, where <span class="math inline">\(p\)</span> is the per-position identity.</p>
<p>At 80% identity: <span class="math inline">\(0.8^{11} \approx 0.086\)</span> per position — but with hundreds of positions to try, a seed is nearly certain. At 60% identity: <span class="math inline">\(0.6^{11} \approx 0.004\)</span>, and short homologous regions now seed only occasionally.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>word size</th>
<th>effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>larger</td>
<td>fewer seeds, fewer extensions, <strong>faster</strong>, misses remote homology</td>
</tr>
<tr class="even">
<td>smaller</td>
<td>more seeds, more extensions, <strong>slower</strong>, finds weaker matches</td>
</tr>
</tbody>
</table>
<p><code>blastn</code> defaults to 11 for general search and <strong>28</strong> for <code>megablast</code>, which is tuned for near-identical sequences and is roughly an order of magnitude faster. If a search “finds nothing”, the word size is the first thing to check — <code>megablast</code> on diverged sequences finds nothing by design.</p>
</div>
</div>
</div>
</section>
<section id="spaced-seeds" class="slide level2">
<h2>Spaced seeds</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why contiguous seeds are a poor use of <span class="math inline">\(w\)</span> positions</strong></p>
</div>
<div class="callout-content">
<p>A contiguous 11-mer requires 11 consecutive matches. But mutations are roughly independent across positions, so consecutive runs are exactly what diverged sequences lack.</p>
<p>A <strong>spaced seed</strong> requires matches only at selected positions of a longer window — pattern <code>111*1**1*1**11*111</code> demands 11 matches spread over 18 positions. Same cost to look up, far more likely to be satisfied by a genuinely homologous region.</p>
<p>Better still, overlapping hits from a spaced seed are <em>less correlated</em> than from a contiguous one, so a region that fails to seed at one offset often seeds at the next. PatternHunter showed this gives higher sensitivity <strong>and</strong> higher speed than contiguous seeding — a rare case of no trade-off.</p>
</div>
</div>
</div>
</section>
<section id="the-blast-family" class="slide level2">
<h2>The BLAST family</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Which program, and why it matters more than the parameters</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>program</th>
<th>query</th>
<th>database</th>
<th>use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>blastn</code></td>
<td>nucleotide</td>
<td>nucleotide</td>
<td>DNA vs DNA</td>
</tr>
<tr class="even">
<td><code>blastp</code></td>
<td>protein</td>
<td>protein</td>
<td>protein vs protein</td>
</tr>
<tr class="odd">
<td><code>blastx</code></td>
<td>nucleotide <em>(translated)</em></td>
<td>protein</td>
<td>what does my ORF do?</td>
</tr>
<tr class="even">
<td><code>tblastn</code></td>
<td>protein</td>
<td>nucleotide <em>(translated)</em></td>
<td>is this protein in that genome?</td>
</tr>
<tr class="odd">
<td><code>tblastx</code></td>
<td>translated</td>
<td>translated</td>
<td>expensive; last resort</td>
</tr>
</tbody>
</table>
<p><strong>The rule worth remembering: search in protein space whenever you can.</strong> The genetic code is redundant, so synonymous substitutions accumulate in DNA while the protein is unchanged. Two genes at 45% nucleotide identity — indistinguishable from noise — can be 80% identical as proteins and obviously homologous.</p>
<p>Protein search also has a 20-letter alphabet, so a chance match is far less likely, and BLOSUM62 lets a conservative substitution still count.</p>
</div>
</div>
</div>
</section>
<section id="bit-scores" class="slide level2">
<h2>Bit scores</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The score you can actually compare</strong></p>
</div>
<div class="callout-content">
<p>A raw score <span class="math inline">\(S\)</span> depends on the scoring matrix and gap penalties you used, so raw scores are not comparable between searches. The <strong>bit score</strong> normalises that away:</p>
<p><span class="math display">\[S' = \frac{\lambda S - \ln K}{\ln 2}\]</span></p>
<p>Bit scores <em>are</em> comparable across searches and databases. The E-value then follows from the bit score and the search space alone:</p>
<p><span class="math display">\[E = \frac{m \, n}{2^{S'}}\]</span></p>
<p>So: <strong>bit score describes the alignment; E-value describes the alignment in the context of this particular database.</strong> Report bit score when comparing hits to each other, E-value when arguing that a hit is real.</p>
</div>
</div>
</div>
<!-- source: background beyond readIAB -- Roberts et al. 2004 minimizers;
     included because every modern aligner uses them -->
</section>
<section id="minimizers" class="slide level2 scrollable">
<h2>Minimizers</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Indexing every <span class="math inline">\(k\)</span>-mer is wasteful</strong></p>
</div>
<div class="callout-content">
<p>A sequence of length <span class="math inline">\(m\)</span> has <span class="math inline">\(m - k + 1\)</span> <span class="math inline">\(k\)</span>-mers, and consecutive ones overlap in <span class="math inline">\(k-1\)</span> characters — enormously redundant.</p>
<p>A <strong>minimizer</strong> scheme picks, from each window of <span class="math inline">\(w\)</span> consecutive <span class="math inline">\(k\)</span>-mers, only the one that is smallest under some ordering. Two sequences that share a long exact stretch are guaranteed to select the <em>same</em> minimizer within it, so sensitivity is largely preserved.</p>
<p>The index shrinks by roughly a factor of <span class="math inline">\(w\)</span>. This is the trick behind <strong>minimap2</strong> and <strong>Kraken</strong>, and it is why long-read alignment became tractable at all.</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The general pattern</strong></p>
</div>
<div class="callout-content">
<p>Exact <span class="math inline">\(\rightarrow\)</span> approximate <span class="math inline">\(\rightarrow\)</span> <em>sampled</em> approximate. Each step trades a guarantee for a constant factor, and each is justified by measuring what the guarantee was worth.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "Determining the statistical significance of a
     pairwise alignment" -- Metrics of alignment quality; false positives,
     false negatives, p-values and alpha -->
</section>
<section id="statistical-significance" class="slide level2">
<h2>Statistical significance</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A raw score means nothing on its own</strong></p>
</div>
<div class="callout-content">
<p>A score of 60 is impressive against a 100-sequence database and meaningless against <span class="math inline">\(10^{9}\)</span> — with enough sequences, high scores arise by chance.</p>
<p>The <strong>E-value</strong> is the expected number of alignments scoring at least <span class="math inline">\(S\)</span> by chance in a database of this size:</p>
<p><span class="math display">\[E = K \, m \, n \, e^{-\lambda S}\]</span></p>
<p>with <span class="math inline">\(m\)</span> the query length, <span class="math inline">\(n\)</span> the database size, and <span class="math inline">\(K, \lambda\)</span> fitted constants.</p>
<ul>
<li><span class="math inline">\(E = 10\)</span> — expect 10 such hits by chance. Noise.</li>
<li><span class="math inline">\(E = 10^{-5}\)</span> — expect one such hit per 100 000 searches. Interesting.</li>
</ul>
<p><strong>The E-value grows with database size for a fixed score.</strong> The same alignment becomes less significant as the database grows, which is not a flaw — it is the multiple-testing correction being applied honestly.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "Metrics of alignment quality" -->
</section>
<section id="percent-identity-is-not-enough" class="slide level2">
<h2>Percent identity is not enough</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The most over-used number in bioinformatics</strong></p>
</div>
<div class="callout-content">
<p>“These sequences are 85% identical” is nearly meaningless without three more facts:</p>
<ul>
<li><strong>over what length?</strong> 85% over 20 residues is noise; over 500 it is strong evidence.</li>
<li><strong>relative to which alignment?</strong> Percent identity is computed <em>from</em> an alignment, which was produced by a scoring scheme you chose.</li>
<li><strong>at what composition?</strong> Two AT-rich sequences share bases by chance far more often than two balanced ones.</li>
</ul>
<p>This is why BLAST reports <strong>bit score</strong> and <strong>E-value</strong> alongside identity — and why comparing identity values across papers that used different aligners is not meaningful.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.4, "False positives, false negatives, p-values, and alpha" -->
</section>
<section id="evaluating-a-search" class="slide level2 scrollable">
<h2>Evaluating a search</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Four outcomes</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>homologous (truth)</th>
<th>not homologous</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>reported</strong></td>
<td>true positive</td>
<td>false positive</td>
</tr>
<tr class="even">
<td><strong>not reported</strong></td>
<td>false negative</td>
<td>true negative</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>sensitivity</strong> (recall) <span class="math inline">\(= \frac{TP}{TP + FN}\)</span> — what fraction of real homologs did we find?</li>
<li><strong>specificity</strong> <span class="math inline">\(= \frac{TN}{TN + FP}\)</span> — what fraction of non-homologs did we correctly ignore?</li>
</ul>
<p>Lowering the threshold raises sensitivity and lowers specificity. There is no setting that maximises both, so the choice depends on the cost of each error <em>in your application</em>.</p>
</div>
</div>
</div>
</section>
<section id="the-threshold-trade-off" class="slide level2 scrollable">
<h2>The threshold trade-off</h2>
<div id="cddb9b86" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a aria-label="1"></a>homologs <span class="op">=</span> [mutate(base, r) <span class="cf">for</span> r <span class="kw">in</span> np.linspace(<span class="fl">0.02</span>, <span class="fl">0.40</span>, <span class="dv">40</span>)]</span>
<span id="cb10-2"><a aria-label="2"></a>unrelated <span class="op">=</span> [random_seq(<span class="dv">300</span>) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">40</span>)]</span>
<span id="cb10-3"><a aria-label="3"></a>jh <span class="op">=</span> np.array([jaccard(qk, kmers(s)) <span class="cf">for</span> s <span class="kw">in</span> homologs])</span>
<span id="cb10-4"><a aria-label="4"></a>ju <span class="op">=</span> np.array([jaccard(qk, kmers(s)) <span class="cf">for</span> s <span class="kw">in</span> unrelated])</span>
<span id="cb10-5"><a aria-label="5"></a></span>
<span id="cb10-6"><a aria-label="6"></a>thresholds <span class="op">=</span> np.linspace(<span class="fl">0.05</span>, <span class="fl">0.6</span>, <span class="dv">60</span>)</span>
<span id="cb10-7"><a aria-label="7"></a>sens <span class="op">=</span> [(jh <span class="op">&gt;=</span> t).mean() <span class="cf">for</span> t <span class="kw">in</span> thresholds]</span>
<span id="cb10-8"><a aria-label="8"></a>spec <span class="op">=</span> [(ju <span class="op">&lt;</span> t).mean() <span class="cf">for</span> t <span class="kw">in</span> thresholds]</span>
<span id="cb10-9"><a aria-label="9"></a></span>
<span id="cb10-10"><a aria-label="10"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">5.5</span>, <span class="fl">3.4</span>))</span>
<span id="cb10-11"><a aria-label="11"></a>ax.plot(thresholds, sens, label<span class="op">=</span><span class="st">"sensitivity"</span>)</span>
<span id="cb10-12"><a aria-label="12"></a>ax.plot(thresholds, spec, label<span class="op">=</span><span class="st">"specificity"</span>)</span>
<span id="cb10-13"><a aria-label="13"></a>ax.set_xlabel(<span class="st">"Jaccard threshold"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"rate"</span>)</span>
<span id="cb10-14"><a aria-label="14"></a>ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-8-output-1.png" width="599" height="368"></p>
</figure>
</div>
</div>
</div>
<p>The crossing point is where the two errors balance. <strong>Where you sit on this curve is a decision about consequences, not about statistics</strong> — and it is the decision that every E-value cut-off encodes.</p>
<!-- ==========================================================================
     SOURCE: readIAB ch.5 "Machine learning in bioinformatics"
             https://readiab.org/machine-learning.html
             sections: "The feature table", "Supervised classification",
                       "Naive Bayes classifiers", "Training data, test data,
                       and cross-validation"
     ========================================================================== -->
<!-- source: readIAB ch.4, "Exploring the limit of detection of sequence
     homology searches" -->
</section>
<section id="the-limit-of-detection" class="slide level2 scrollable">
<h2>The limit of detection</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Where does homology become invisible?</strong></p>
</div>
<div class="callout-content">
<div id="455c1753" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a aria-label="1"></a>divergences <span class="op">=</span> np.arange(<span class="fl">0.05</span>, <span class="fl">0.75</span>, <span class="fl">0.05</span>)</span>
<span id="cb11-2"><a aria-label="2"></a>results <span class="op">=</span> []</span>
<span id="cb11-3"><a aria-label="3"></a><span class="cf">for</span> d <span class="kw">in</span> divergences:</span>
<span id="cb11-4"><a aria-label="4"></a>    scores <span class="op">=</span> [aligner.align(base, mutate(base, d)).score <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)]</span>
<span id="cb11-5"><a aria-label="5"></a>    results.append(np.mean(scores))</span>
<span id="cb11-6"><a aria-label="6"></a></span>
<span id="cb11-7"><a aria-label="7"></a>null <span class="op">=</span> [aligner.align(base, random_seq(<span class="dv">300</span>)).score <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">20</span>)]</span>
<span id="cb11-8"><a aria-label="8"></a>null_mean, null_sd <span class="op">=</span> np.mean(null), np.std(null)</span>
<span id="cb11-9"><a aria-label="9"></a></span>
<span id="cb11-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="ss">f"  unrelated baseline: </span><span class="sc">{</span>null_mean<span class="sc">:.0f}</span><span class="ss"> +/- </span><span class="sc">{</span>null_sd<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb11-11"><a aria-label="11"></a><span class="cf">for</span> d, sc <span class="kw">in</span> <span class="bu">zip</span>(divergences, results):</span>
<span id="cb11-12"><a aria-label="12"></a>    z <span class="op">=</span> (sc <span class="op">-</span> null_mean) <span class="op">/</span> null_sd</span>
<span id="cb11-13"><a aria-label="13"></a>    flag <span class="op">=</span> <span class="st">"detectable"</span> <span class="cf">if</span> z <span class="op">&gt;</span> <span class="dv">3</span> <span class="cf">else</span> <span class="st">"INDISTINGUISHABLE"</span></span>
<span id="cb11-14"><a aria-label="14"></a>    <span class="bu">print</span>(<span class="ss">f"  divergence </span><span class="sc">{</span>d<span class="sc">:.0%}</span><span class="ss">: score </span><span class="sc">{</span>sc<span class="sc">:6.0f}</span><span class="ss">  z=</span><span class="sc">{</span>z<span class="sc">:6.1f}</span><span class="ss">  </span><span class="sc">{</span>flag<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  unrelated baseline: 19 +/- 3
  divergence 5%: score    532  z= 163.0  detectable
  divergence 10%: score    488  z= 149.1  detectable
  divergence 15%: score    431  z= 131.0  detectable
  divergence 20%: score    366  z= 110.3  detectable
  divergence 25%: score    353  z= 106.2  detectable
  divergence 30%: score    256  z=  75.2  detectable
  divergence 35%: score    198  z=  56.8  detectable
  divergence 40%: score    161  z=  45.3  detectable
  divergence 45%: score    101  z=  26.0  detectable
  divergence 50%: score     80  z=  19.5  detectable
  divergence 55%: score     38  z=   5.9  detectable
  divergence 60%: score     43  z=   7.6  detectable
  divergence 65%: score     21  z=   0.6  INDISTINGUISHABLE
  divergence 70%: score     20  z=   0.3  INDISTINGUISHABLE</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-limit-of-detection-1" class="slide level2 scrollable">
<h2>The limit of detection</h2>
<div id="53020d99" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a aria-label="1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">5.5</span>, <span class="fl">3.4</span>))</span>
<span id="cb13-2"><a aria-label="2"></a>ax.plot(divergences <span class="op">*</span> <span class="dv">100</span>, results, <span class="st">"o-"</span>, label<span class="op">=</span><span class="st">"homolog score"</span>)</span>
<span id="cb13-3"><a aria-label="3"></a>ax.axhline(null_mean, color<span class="op">=</span><span class="st">"grey"</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"unrelated mean"</span>)</span>
<span id="cb13-4"><a aria-label="4"></a>ax.fill_between([<span class="dv">5</span>, <span class="dv">70</span>], null_mean <span class="op">-</span> <span class="dv">3</span> <span class="op">*</span> null_sd, null_mean <span class="op">+</span> <span class="dv">3</span> <span class="op">*</span> null_sd,</span>
<span id="cb13-5"><a aria-label="5"></a>                color<span class="op">=</span><span class="st">"grey"</span>, alpha<span class="op">=</span><span class="fl">0.2</span>, label<span class="op">=</span><span class="st">"noise band (3 sd)"</span>)</span>
<span id="cb13-6"><a aria-label="6"></a>ax.set_xlabel(<span class="st">"</span><span class="sc">% d</span><span class="st">ivergence"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"Smith-Waterman score"</span>)</span>
<span id="cb13-7"><a aria-label="7"></a>ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-10-output-1.png" width="598" height="368"></p>
</figure>
</div>
</div>
</div>
<p>Beyond a certain divergence the signal enters the noise band and <strong>no threshold can separate homolog from chance</strong>. This is not a limitation of the heuristic — it is a limitation of the data. The <em>twilight zone</em> for proteins sits around 20–35% identity, and detecting homology below it needs profile methods (PSI-BLAST, HMMER), not better alignment.</p>
</section>
<section id="profiles-beat-pairs" class="slide level2">
<h2>Profiles beat pairs</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Where the extra information comes from</strong></p>
</div>
<div class="callout-content">
<p>Pairwise alignment uses two sequences. That is all the evidence it has, and below the twilight zone it is not enough.</p>
<p>A <strong>profile</strong> uses a whole family. Align many known members, and each column of that alignment tells you something a pair cannot: <em>position 47 is always hydrophobic; position 48 is anything at all.</em> A position-specific scoring matrix (PSSM) records that — one score column per position, rather than one matrix for the whole sequence.</p>
<p>The consequence is that a query matching the family’s <strong>conserved positions</strong> scores well even at 20% overall identity, because the variable positions were never being counted against it in the first place.</p>
</div>
</div>
</div>
</section>
<section id="two-ways-to-build-a-profile" class="slide level2 scrollable">
<h2>Two ways to build a profile</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>PSI-BLAST and HMMER</strong></p>
</div>
<div class="callout-content">
<p><strong>PSI-BLAST</strong> builds the profile <em>iteratively</em> from your own search. Run <code>blastp</code>, take the hits above a threshold, build a PSSM from them, search again with the PSSM, repeat. Each round reaches sequences the previous round could not see.</p>
<p>The failure mode is specific and worth knowing: if one false positive enters the profile, the next iteration searches <em>for that too</em>. Contamination compounds across rounds — <strong>profile drift</strong>. Use a strict inclusion threshold and look at what enters on each round.</p>
<p><strong>HMMER</strong> uses a profile hidden Markov model, which models position-specific <em>insertion and deletion</em> probabilities as well as substitution — a proper probabilistic model rather than a score table. It is what Pfam is built on, and <code>hmmsearch</code> on a curated Pfam model is generally the most sensitive homology tool available.</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And beyond sequence</strong></p>
</div>
<div class="callout-content">
<p>Below ~20% identity even profiles struggle, and the remaining signal is <strong>structural</strong>. Structure is conserved far longer than sequence — which is why structure prediction changed what “remote homology detection” means, and why <code>foldseek</code> searching predicted structures now finds relationships no sequence method can.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="machine-learning" class="title-slide slide level1 center">
<h1>Machine learning</h1>

</section>
<section id="from-alignment-to-classification" class="slide level2">
<h2>From alignment to classification</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A different framing of the same task</strong></p>
</div>
<div class="callout-content">
<p>Homology search asks: <em>which database sequence is this most like?</em></p>
<p>Classification asks: <em>which of these known categories does this sequence belong to?</em> — and answers without comparing against every reference.</p>
<p>The canonical application is <strong>taxonomic assignment</strong>: given a 16S rRNA sequence from an environmental sample, which genus produced it?</p>
<p>The trick that makes it work is turning a sequence into a <strong>fixed-length feature vector</strong>, which is exactly what <span class="math inline">\(k\)</span>-mer counting does.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.5, "The feature table" -->
</section>
<section id="the-feature-table" class="slide level2">
<h2>The feature table</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The format every method assumes</strong></p>
</div>
<div class="callout-content">
<p>Almost every machine-learning method expects one thing:</p>
<p><span class="math display">\[\underbrace{n \text{ samples}}_{\text{rows}} \times \underbrace{p \text{ features}}_{\text{columns}} \;+\; \text{a label per row}\]</span></p>
<p>That is the <em>only</em> interface. The entire difficulty in applying ML to biology is that biological data does not arrive in this shape, and getting it there is where the decisions are made.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>data</th>
<th>sample</th>
<th>feature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>taxonomy</td>
<td>a sequence</td>
<td>count of each <span class="math inline">\(k\)</span>-mer</td>
</tr>
<tr class="even">
<td>microbiome</td>
<td>a specimen</td>
<td>abundance of each taxon</td>
</tr>
<tr class="odd">
<td>scRNA-seq <em>(Bio 3)</em></td>
<td>a cell</td>
<td>count of each gene</td>
</tr>
</tbody>
</table>
<p>Note the third row. <strong><code>adata.X</code> is a feature table</strong>, and the pipeline in Bio 3 and Bio 4 is a sequence of decisions about how to build one. The two halves of this series are more alike than they look.</p>
</div>
</div>
</div>
</section>
<section id="where-the-modelling-happened" class="slide level2">
<h2>Where the modelling happened</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Before you ever call <code>.fit()</code></strong></p>
</div>
<div class="callout-content">
<p>By the time you call <code>.fit()</code>, the decisions are already made: what counted as a sample, what counted as a feature, what was filtered, how counts were normalised. The classifier only sees the table.</p>
<p><strong>Most of the quality of a result is determined before the model is chosen</strong> — which is why so little of these four lectures is about models.</p>
</div>
</div>
</div>
</section>
<section id="k-mers-as-features" class="slide level2 scrollable">
<h2><span class="math inline">\(k\)</span>-mers as features</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sequence to vector</strong></p>
</div>
<div class="callout-content">
<div id="46931340" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a aria-label="1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> CountVectorizer</span>
<span id="cb14-2"><a aria-label="2"></a></span>
<span id="cb14-3"><a aria-label="3"></a>genera <span class="op">=</span> {}</span>
<span id="cb14-4"><a aria-label="4"></a><span class="cf">for</span> name, seed <span class="kw">in</span> [(<span class="st">"Genus_A"</span>, <span class="dv">1</span>), (<span class="st">"Genus_B"</span>, <span class="dv">2</span>), (<span class="st">"Genus_C"</span>, <span class="dv">3</span>)]:</span>
<span id="cb14-5"><a aria-label="5"></a>    genera[name] <span class="op">=</span> <span class="st">""</span>.join(</span>
<span id="cb14-6"><a aria-label="6"></a>        np.random.default_rng(seed).choice(<span class="bu">list</span>(<span class="st">"ACGT"</span>), <span class="dv">400</span>)</span>
<span id="cb14-7"><a aria-label="7"></a>    )</span>
<span id="cb14-8"><a aria-label="8"></a></span>
<span id="cb14-9"><a aria-label="9"></a>sequences, labels, sources <span class="op">=</span> [], [], []</span>
<span id="cb14-10"><a aria-label="10"></a><span class="cf">for</span> name, ref <span class="kw">in</span> genera.items():</span>
<span id="cb14-11"><a aria-label="11"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">40</span>):</span>
<span id="cb14-12"><a aria-label="12"></a>        sequences.append(mutate(ref, <span class="fl">0.08</span>))</span>
<span id="cb14-13"><a aria-label="13"></a>        labels.append(name)</span>
<span id="cb14-14"><a aria-label="14"></a>        sources.append(name)</span>
<span id="cb14-15"><a aria-label="15"></a></span>
<span id="cb14-16"><a aria-label="16"></a>vec <span class="op">=</span> CountVectorizer(analyzer<span class="op">=</span><span class="st">"char"</span>, ngram_range<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb14-17"><a aria-label="17"></a>X <span class="op">=</span> vec.fit_transform(sequences)</span>
<span id="cb14-18"><a aria-label="18"></a><span class="bu">print</span>(<span class="st">"  sequences      :"</span>, <span class="bu">len</span>(sequences))</span>
<span id="cb14-19"><a aria-label="19"></a><span class="bu">print</span>(<span class="st">"  feature matrix :"</span>, X.shape, <span class="ss">f"(</span><span class="sc">{</span><span class="dv">4</span><span class="op">**</span><span class="dv">5</span><span class="sc">}</span><span class="ss"> possible 5-mers)"</span>)</span>
<span id="cb14-20"><a aria-label="20"></a><span class="bu">print</span>(<span class="st">"  sparsity       :"</span>, <span class="ss">f"</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> X<span class="sc">.</span>nnz <span class="op">/</span> (X.shape[<span class="dv">0</span>] <span class="op">*</span> X.shape[<span class="dv">1</span>])<span class="sc">:.1f}</span><span class="ss">% non-zero"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sequences      : 120
  feature matrix : (120, 1024) (1024 possible 5-mers)
  sparsity       : 31.9% non-zero</code></pre>
</div>
</div>
<p>Every sequence is now a point in <span class="math inline">\(4^k\)</span>-dimensional count space, and any classifier will take it.</p>
</div>
</div>
</div>
<!-- =========================================================================
     SOURCE: readIAB ch.5 "Machine learning in bioinformatics"
       https://readiab.org/machine-learning.html
       sections: "Unsupervised versus supervised learning methods",
                 "Unsupervised learning", "Computing distances between samples",
                 "Polar ordination", "Interpreting ordination plots"
                 (axis order / uncorrelated axes / directionality),
                 "Principal Coordinates Analysis (PCoA)"
     ========================================================================= -->
</section>
<section id="two-kinds-of-learning" class="slide level2">
<h2>Two kinds of learning</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Before classifying, look</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>unsupervised</strong></th>
<th><strong>supervised</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>input</td>
<td>feature table</td>
<td>feature table <strong>+ labels</strong></td>
</tr>
<tr class="even">
<td>asks</td>
<td>what structure is in here?</td>
<td>can I predict the label?</td>
</tr>
<tr class="odd">
<td>output</td>
<td>an embedding, or clusters</td>
<td>a classifier</td>
</tr>
<tr class="even">
<td>fails by</td>
<td>finding structure that is not there</td>
<td>being confidently wrong on new data</td>
</tr>
</tbody>
</table>
<p>Unsupervised comes first in practice, and for a specific reason: <strong>it is how you find out whether your labels correspond to anything in the data at all.</strong> If samples do not separate by label in an ordination, a classifier that scores 99% is telling you about leakage, not about biology.</p>
<p>In ecology the unsupervised step is called <strong>ordination</strong>. It is the same operation you will meet in Bio 3 as dimensionality reduction — different field, different vocabulary, same mathematics.</p>
</div>
</div>
</div>
</section>
<section id="distances-between-samples" class="slide level2 scrollable">
<h2>Distances between samples</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Jaccard again, now as a distance</strong></p>
</div>
<div class="callout-content">
<p>Almost every ordination starts from <strong>distances between all pairs of samples</strong>. We already have the statistic — the Jaccard index from the search half of this lecture. Subtract it from one:</p>
<p><span class="math display">\[\text{Jaccard distance}_{(A,B)} = 1 - \frac{\lvert A \cap B \rvert}{\lvert A \cup B \rvert}\]</span></p>
<div id="638b70ea" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a aria-label="1"></a><span class="im">from</span> skbio.diversity <span class="im">import</span> beta_diversity</span>
<span id="cb16-2"><a aria-label="2"></a></span>
<span id="cb16-3"><a aria-label="3"></a>presence <span class="op">=</span> (X.toarray() <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb16-4"><a aria-label="4"></a>ids <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>lab[<span class="op">-</span><span class="dv">1</span>]<span class="sc">}{</span>i<span class="sc">:03d}</span><span class="ss">"</span> <span class="cf">for</span> i, lab <span class="kw">in</span> <span class="bu">enumerate</span>(labels)]</span>
<span id="cb16-5"><a aria-label="5"></a></span>
<span id="cb16-6"><a aria-label="6"></a>dm <span class="op">=</span> beta_diversity(<span class="st">"jaccard"</span>, presence, ids<span class="op">=</span>ids)</span>
<span id="cb16-7"><a aria-label="7"></a>D <span class="op">=</span> dm.data</span>
<span id="cb16-8"><a aria-label="8"></a></span>
<span id="cb16-9"><a aria-label="9"></a><span class="bu">print</span>(<span class="st">"  feature table   :"</span>, presence.shape, <span class="st">"(sequences x 5-mers, presence/absence)"</span>)</span>
<span id="cb16-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="st">"  distance matrix :"</span>, D.shape)</span>
<span id="cb16-11"><a aria-label="11"></a><span class="bu">print</span>(<span class="st">"  diagonal zero   :"</span>, np.allclose(np.diag(D), <span class="dv">0</span>))</span>
<span id="cb16-12"><a aria-label="12"></a><span class="bu">print</span>(<span class="st">"  symmetric       :"</span>, np.allclose(D, D.T))</span>
<span id="cb16-13"><a aria-label="13"></a><span class="bu">print</span>(<span class="ss">f"  range           : </span><span class="sc">{</span>D[D <span class="op">&gt;</span> <span class="dv">0</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss"> to </span><span class="sc">{</span>D<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  feature table   : (120, 1024) (sequences x 5-mers, presence/absence)
  distance matrix : (120, 120)
  diagonal zero   : True
  symmetric       : True
  range           : 0.382 to 0.863</code></pre>
</div>
</div>
<p>Two properties hold by construction and are worth checking anyway: the <strong>diagonal is zero</strong> (a sample is at distance 0 from itself) and the matrix is <strong>symmetric</strong>. A distance matrix that fails either is a bug upstream.</p>
</div>
</div>
</div>
</section>
<section id="the-distance-matrix" class="slide level2 scrollable">
<h2>The distance matrix</h2>
<div id="0af89ee8" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a aria-label="1"></a>order <span class="op">=</span> np.argsort(labels, kind<span class="op">=</span><span class="st">"stable"</span>)</span>
<span id="cb18-2"><a aria-label="2"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">4.6</span>, <span class="fl">3.8</span>))</span>
<span id="cb18-3"><a aria-label="3"></a>im <span class="op">=</span> ax.imshow(D[np.ix_(order, order)], cmap<span class="op">=</span><span class="st">"viridis"</span>)</span>
<span id="cb18-4"><a aria-label="4"></a>ax.set_xlabel(<span class="st">"sequence"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"sequence"</span>)</span>
<span id="cb18-5"><a aria-label="5"></a>plt.colorbar(im, label<span class="op">=</span><span class="st">"Jaccard distance"</span>)</span>
<span id="cb18-6"><a aria-label="6"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-13-output-1.png" width="495" height="408"></p>
</figure>
</div>
</div>
</div>
<p>Sorted by genus, the block structure is visible directly in the raw distances — three dark blocks on the diagonal, lighter between them. <strong>The structure is already in the data; ordination only makes it easier to look at.</strong></p>
</section>
<section id="ordination" class="slide level2">
<h2>Ordination</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong><span class="math inline">\(n \times n\)</span> distances into two axes</strong></p>
</div>
<div class="callout-content">
<p>A distance matrix over 120 sequences has 7 140 distinct entries. You cannot read that. Ordination finds a low-dimensional arrangement in which <strong>distance on the page approximates distance in the data</strong>.</p>
<p>readIAB teaches it twice over — first <strong>polar ordination</strong>, where the arithmetic is simple enough to do by hand, then <strong>PCoA</strong>, which is what you would actually use. We will do the same, because the simple version makes clear what the sophisticated one is doing.</p>
</div>
</div>
</div>
</section>
<section id="polar-ordination-by-hand" class="slide level2 scrollable">
<h2>Polar ordination by hand</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One axis, from two endpoints</strong></p>
</div>
<div class="callout-content">
<p>Pick the two most distant samples as the endpoints of an axis, then project every other sample onto it by the law of cosines:</p>
<p><span class="math display">\[p_i = \frac{D_{AB}^2 + d(A,i)^2 - d(B,i)^2}{2 D_{AB}}\]</span></p>
<div id="d525029b" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a aria-label="1"></a>a, b <span class="op">=</span> np.unravel_index(np.argmax(D), D.shape)</span>
<span id="cb19-2"><a aria-label="2"></a>Dab <span class="op">=</span> D[a, b]</span>
<span id="cb19-3"><a aria-label="3"></a>pos <span class="op">=</span> (Dab<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> D[a] <span class="op">**</span> <span class="dv">2</span> <span class="op">-</span> D[b] <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> Dab)</span>
<span id="cb19-4"><a aria-label="4"></a></span>
<span id="cb19-5"><a aria-label="5"></a><span class="bu">print</span>(<span class="ss">f"  endpoints    : </span><span class="sc">{</span>ids[a]<span class="sc">}</span><span class="ss"> and </span><span class="sc">{</span>ids[b]<span class="sc">}</span><span class="ss">, distance </span><span class="sc">{</span>Dab<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb19-6"><a aria-label="6"></a><span class="cf">for</span> g <span class="kw">in</span> <span class="bu">sorted</span>(<span class="bu">set</span>(labels)):</span>
<span id="cb19-7"><a aria-label="7"></a>    m <span class="op">=</span> np.array(labels) <span class="op">==</span> g</span>
<span id="cb19-8"><a aria-label="8"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>g<span class="sc">}</span><span class="ss">: axis 1 mean </span><span class="sc">{</span>pos[m]<span class="sc">.</span>mean()<span class="sc">:7.3f}</span><span class="ss">   sd </span><span class="sc">{</span>pos[m]<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  endpoints    : A017 and C085, distance 0.863
  Genus_A: axis 1 mean   0.173   sd 0.037
  Genus_B: axis 1 mean   0.463   sd 0.018
  Genus_C: axis 1 mean   0.678   sd 0.038</code></pre>
</div>
</div>
<p>No eigenvectors, no library — one line of arithmetic per sample, and the genera already separate along a single axis.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why nobody uses it</strong></p>
</div>
<div class="callout-content">
<p>The first axis is principled. <strong>Every axis after it is not</strong>: you must choose new endpoints, and nothing guarantees the result is uncorrelated with what you already have. Polar ordination is a teaching device, not a method — PCoA replaces it precisely by choosing all the axes at once and making them orthogonal by construction.</p>
</div>
</div>
</div>
</section>
<section id="principal-coordinates-analysis" class="slide level2 scrollable">
<h2>Principal Coordinates Analysis</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The one you would actually use</strong></p>
</div>
<div class="callout-content">
<p>PCoA (classical multidimensional scaling) eigendecomposes the centred distance matrix, giving axes that are <strong>orthogonal</strong> and <strong>ordered by the variance they explain</strong>.</p>
<div id="101dd1e2" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a aria-label="1"></a><span class="im">from</span> skbio.stats.ordination <span class="im">import</span> pcoa</span>
<span id="cb21-2"><a aria-label="2"></a></span>
<span id="cb21-3"><a aria-label="3"></a>ord_res <span class="op">=</span> pcoa(dm)</span>
<span id="cb21-4"><a aria-label="4"></a>coords <span class="op">=</span> ord_res.samples.values</span>
<span id="cb21-5"><a aria-label="5"></a>pe <span class="op">=</span> ord_res.proportion_explained.values</span>
<span id="cb21-6"><a aria-label="6"></a></span>
<span id="cb21-7"><a aria-label="7"></a><span class="bu">print</span>(<span class="st">"  coordinates :"</span>, coords.shape)</span>
<span id="cb21-8"><a aria-label="8"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb21-9"><a aria-label="9"></a>    <span class="bu">print</span>(<span class="ss">f"  axis </span><span class="sc">{</span>i <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>pe[i]<span class="sc">:6.1%}</span><span class="ss"> of variation"</span>)</span>
<span id="cb21-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="ss">f"  first two   : </span><span class="sc">{</span>pe[:<span class="dv">2</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss"> of variation"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  coordinates : (120, 120)
  axis 1:  26.7% of variation
  axis 2:  23.1% of variation
  axis 3:   1.1% of variation
  axis 4:   1.1% of variation
  first two   : 49.8% of variation</code></pre>
</div>
</div>
<p><strong>Read the drop, not the percentages.</strong> Axes 1 and 2 carry 26.7% and 23.1%; axis 3 carries 1.1%. That cliff is the answer to “how many dimensions does this data actually have?” — two, which is exactly what three groups need. Everything after the cliff is noise, and plotting PC3 would be plotting noise.</p>
</div>
</div>
</div>
</section>
<section id="principal-coordinates-analysis-1" class="slide level2 scrollable">
<h2>Principal Coordinates Analysis</h2>
<div id="c415e38a" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a aria-label="1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">5.2</span>, <span class="fl">3.6</span>))</span>
<span id="cb23-2"><a aria-label="2"></a><span class="cf">for</span> g <span class="kw">in</span> <span class="bu">sorted</span>(<span class="bu">set</span>(labels)):</span>
<span id="cb23-3"><a aria-label="3"></a>    m <span class="op">=</span> np.array(labels) <span class="op">==</span> g</span>
<span id="cb23-4"><a aria-label="4"></a>    ax.scatter(coords[m, <span class="dv">0</span>], coords[m, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">22</span>, label<span class="op">=</span>g, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb23-5"><a aria-label="5"></a>ax.set_xlabel(<span class="ss">f"PC1 (</span><span class="sc">{</span>pe[<span class="dv">0</span>]<span class="sc">:.1%}</span><span class="ss">)"</span>)<span class="op">;</span> ax.set_ylabel(<span class="ss">f"PC2 (</span><span class="sc">{</span>pe[<span class="dv">1</span>]<span class="sc">:.1%}</span><span class="ss">)"</span>)</span>
<span id="cb23-6"><a aria-label="6"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">7</span>)<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-16-output-1.png" width="565" height="390"></p>
</figure>
</div>
</div>
</div>
<p>The genera separate without ever being told there were genera. <strong>That is the check worth doing before any classification</strong> — and had the groups overlapped here, the 100% accuracy on the next slides would have been the only warning you got.</p>
</section>
<section id="reading-an-ordination-plot" class="slide level2 scrollable">
<h2>Reading an ordination plot</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Three rules, all of them violated routinely</strong></p>
</div>
<div class="callout-content">
<p><strong>1. Axis order is meaningful.</strong> PC1 explains more than PC2, which explains more than PC3. So the plot is not square: a given distance along PC1 means <em>more</em> than the same distance along PC2. Axes should be scaled by their explained variation, and usually are not.</p>
<p><strong>2. The axes are uncorrelated by construction.</strong> PC1 and PC2 are orthogonal, which means <strong>they are not two independent biological findings</strong>. “Group A separates on PC1 and group B on PC2” describes one decomposition, not two discoveries.</p>
<p><strong>3. The direction of an axis is arbitrary.</strong> Eigenvectors are defined up to sign, so flipping an axis changes nothing. Re-run with a different library, or a different seed on a randomised solver, and the plot may be mirrored.</p>
<blockquote>
<p>Nothing about “left” or “right” on a PCoA plot means anything. Only relative position does.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="the-same-idea-twice" class="slide level2">
<h2>The same idea, twice</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Ordination is dimensionality reduction</strong></p>
</div>
<div class="callout-content">
<p><code>scikit-bio</code>’s own documentation is explicit about it:</p>
<blockquote>
<p>Mathematically, ordination shares similarities with, and is in multiple respects equivalent to, embedding and dimensionality reduction. […] the term “ordination” is mainly used in the field of ecology.</p>
</blockquote>
<p>So the arc in Bio 3 — count matrix, distances, PCA, then a 2-D embedding — is this arc, at a different scale and with a different vocabulary.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>here (ecology)</th>
<th>Bio 3 (single cell)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>sample</td>
<td>cell</td>
</tr>
<tr class="even">
<td>feature (<span class="math inline">\(k\)</span>-mer)</td>
<td>gene</td>
</tr>
<tr class="odd">
<td>feature table</td>
<td><code>adata.X</code></td>
</tr>
<tr class="even">
<td>beta diversity</td>
<td>neighbour graph distances</td>
</tr>
<tr class="odd">
<td>ordination (PCoA)</td>
<td>PCA</td>
</tr>
<tr class="even">
<td>—</td>
<td>UMAP / t-SNE</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="and-the-caveats-transfer" class="slide level2">
<h2>And the caveats transfer</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>PCoA is the well-behaved case</strong></p>
</div>
<div class="callout-content">
<p>PCoA is <strong>linear and distance-preserving</strong>, so the three rules above are the honest ones. UMAP is neither, which is why its caveats in Bio 3 are <em>stronger</em>: it does not preserve between-cluster distance or density at all. A PCoA axis at least has a percentage attached to it. A UMAP axis has no units and no meaning.</p>
</div>
</div>
</div>
</section>
<section id="naive-bayes" class="slide level2">
<h2>Naive Bayes</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why it suits this problem</strong></p>
</div>
<div class="callout-content">
<p>For a sequence with <span class="math inline">\(k\)</span>-mer counts <span class="math inline">\(x\)</span> and class <span class="math inline">\(c\)</span>:</p>
<p><span class="math display">\[P(c \mid x) \propto P(c) \prod_{i} P(x_i \mid c)\]</span></p>
<p>The “naive” part is that product: it assumes <span class="math inline">\(k\)</span>-mers occur <strong>independently</strong> given the class. That is clearly false — overlapping <span class="math inline">\(k\)</span>-mers share <span class="math inline">\(k-1\)</span> characters.</p>
<p>It works anyway, for the usual reason: we only need the <em>ranking</em> of <span class="math inline">\(P(c \mid x)\)</span> across classes to be right, not the probabilities themselves. And it is extremely fast, which matters when classifying millions of reads.</p>
<p>This is the method behind the RDP classifier and <code>q2-feature-classifier</code>, the standard tools in microbiome work.</p>
</div>
</div>
</div>
</section>
<section id="training-and-evaluating" class="slide level2 scrollable">
<h2>Training and evaluating</h2>
<div id="ca53088e" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a aria-label="1"></a><span class="im">from</span> sklearn.naive_bayes <span class="im">import</span> MultinomialNB</span>
<span id="cb24-2"><a aria-label="2"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score, train_test_split</span>
<span id="cb24-3"><a aria-label="3"></a></span>
<span id="cb24-4"><a aria-label="4"></a>clf <span class="op">=</span> MultinomialNB()</span>
<span id="cb24-5"><a aria-label="5"></a>scores <span class="op">=</span> cross_val_score(clf, X, labels, cv<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb24-6"><a aria-label="6"></a><span class="bu">print</span>(<span class="st">"  5-fold CV accuracy:"</span>, scores.<span class="bu">round</span>(<span class="dv">3</span>))</span>
<span id="cb24-7"><a aria-label="7"></a><span class="bu">print</span>(<span class="st">"  mean              :"</span>, <span class="bu">round</span>(scores.mean(), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  5-fold CV accuracy: [1. 1. 1. 1. 1.]
  mean              : 1.0</code></pre>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Be suspicious of a perfect score</strong></p>
</div>
<div class="callout-content">
<p><strong>100% accuracy should worry you, not please you.</strong> Real taxonomic classifiers do not achieve it, particularly at genus level.</p>
<p>The next slide explains what went wrong here — and it is the single most common mistake in applied machine learning.</p>
</div>
</div>
</div>
</section>
<section id="the-leakage-trap" class="slide level2">
<h2>The leakage trap</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Our test set was never independent</strong></p>
</div>
<div class="callout-content">
<p>Every sequence labelled <code>Genus_A</code> was generated by mutating <strong>one</strong> reference sequence at 8%. So any two <code>Genus_A</code> sequences are ~92% identical to the same original, and therefore ~85% identical to each other.</p>
<p>When 5-fold CV splits them randomly, each fold’s test sequences have <strong>near-duplicates in the training set</strong>. The classifier is not generalising to new organisms; it is recognising sequences it has effectively already seen.</p>
<p>This is <strong>data leakage</strong>, and it is endemic in biological data because biological data is <em>structured by relatedness</em>: strains within a species, species within a genus, and now sequences within a training set.</p>
</div>
</div>
</div>
</section>
<section id="what-leakage-costs-you" class="slide level2 scrollable">
<h2>What leakage costs you</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The failure that matters: an organism you have never seen</strong></p>
</div>
<div class="callout-content">
<p>Random CV told us 100%. Here is what the same classifier does when handed a genus that was <strong>not in its training set at all</strong> — the everyday situation in environmental sequencing, where most organisms are uncharacterised.</p>
<div id="536c1709" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a aria-label="1"></a>novel_ref <span class="op">=</span> <span class="st">""</span>.join(np.random.default_rng(<span class="dv">999</span>).choice(<span class="bu">list</span>(<span class="st">"ACGT"</span>), <span class="dv">400</span>))</span>
<span id="cb26-2"><a aria-label="2"></a>novel <span class="op">=</span> [mutate(novel_ref, <span class="fl">0.08</span>) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>)]</span>
<span id="cb26-3"><a aria-label="3"></a></span>
<span id="cb26-4"><a aria-label="4"></a>clf_fitted <span class="op">=</span> MultinomialNB().fit(X, labels)</span>
<span id="cb26-5"><a aria-label="5"></a>Xn <span class="op">=</span> vec.transform(novel)</span>
<span id="cb26-6"><a aria-label="6"></a>pred <span class="op">=</span> clf_fitted.predict(Xn)</span>
<span id="cb26-7"><a aria-label="7"></a>conf <span class="op">=</span> clf_fitted.predict_proba(Xn).<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb26-8"><a aria-label="8"></a></span>
<span id="cb26-9"><a aria-label="9"></a><span class="im">import</span> collections</span>
<span id="cb26-10"><a aria-label="10"></a></span>
<span id="cb26-11"><a aria-label="11"></a><span class="bu">print</span>(<span class="st">"  predicted labels :"</span>, <span class="bu">dict</span>(collections.Counter(pred)))</span>
<span id="cb26-12"><a aria-label="12"></a><span class="bu">print</span>(<span class="ss">f"  mean confidence  : </span><span class="sc">{</span>conf<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">   (min </span><span class="sc">{</span>conf<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, max </span><span class="sc">{</span>conf<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  predicted labels : {np.str_('Genus_C'): 10}
  mean confidence  : 0.985   (min 0.854, max 1.000)</code></pre>
</div>
</div>
<p>Every one of these sequences came from an organism the classifier has never seen. It assigned them all to <code>Genus_C</code> — <strong>with a reported confidence of 1.000</strong>.</p>
<p>The label is meaningless and the confidence is worse than meaningless: it is maximal. Depending on the random draw the predictions may land on one genus or scatter across several; what never happens is the classifier declining to answer.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Naive Bayes has no “none of the above”</strong></p>
</div>
<div class="callout-content">
<p><code>predict_proba</code> returns a distribution over the <strong>classes it was trained on</strong>. It is a statement of relative preference among those, not of absolute fit — so it cannot express <em>“this is unlike anything I know”</em>.</p>
<p>Real taxonomic classifiers add a confidence threshold below which they refuse to assign, and report the sequence at a coarser rank (“Bacteria” rather than a genus) or not at all. Without that, a pipeline silently invents plausible answers for every unknown it meets.</p>
</div>
</div>
</div>
<!-- source: readIAB ch.5, "Evaluating our confidence in the results of the
     Naive Bayes classifier" -- the RDP-style bootstrap over the query's own
     k-mers. Applied here to the novel-genus case to test whether it helps. -->
</section>
<section id="the-bootstrap-confidence" class="slide level2 scrollable">
<h2>The bootstrap confidence</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>readIAB’s answer, and the real one used by RDP</strong></p>
</div>
<div class="callout-content">
<p><code>predict_proba</code> is not the confidence measure taxonomic classifiers actually report. Theirs is a <strong>bootstrap</strong>: resample the query’s own <span class="math inline">\(k\)</span>-mers with replacement, reclassify each subsample, and count how often you get the original answer back.</p>
<p><span class="math display">\[\text{confidence} = \frac{\#\{\text{subsamples agreeing with the full query}\}}{\#\text{iterations}}\]</span></p>
<p>It asks a sharper question than <code>predict_proba</code> does: <em>how much does this assignment depend on which parts of my sequence I happened to look at?</em></p>
<div id="015190e4" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a aria-label="1"></a><span class="kw">def</span> bootstrap_confidence(clf, counts, n_iter<span class="op">=</span><span class="dv">100</span>, frac<span class="op">=</span><span class="fl">0.1</span>, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb28-2"><a aria-label="2"></a>    <span class="co">"""RDP-style confidence: resample the query's k-mers, reclassify, count agreement."""</span></span>
<span id="cb28-3"><a aria-label="3"></a>    rng_b <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb28-4"><a aria-label="4"></a>    counts <span class="op">=</span> np.asarray(counts).ravel().astype(<span class="bu">int</span>)</span>
<span id="cb28-5"><a aria-label="5"></a>    occurrences <span class="op">=</span> np.repeat(np.arange(counts.size), counts)</span>
<span id="cb28-6"><a aria-label="6"></a>    base <span class="op">=</span> clf.predict(counts.reshape(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>))[<span class="dv">0</span>]</span>
<span id="cb28-7"><a aria-label="7"></a>    size <span class="op">=</span> <span class="bu">max</span>(<span class="dv">1</span>, <span class="bu">int</span>(<span class="bu">len</span>(occurrences) <span class="op">*</span> frac))</span>
<span id="cb28-8"><a aria-label="8"></a>    agree <span class="op">=</span> <span class="bu">sum</span>(</span>
<span id="cb28-9"><a aria-label="9"></a>        clf.predict(</span>
<span id="cb28-10"><a aria-label="10"></a>            np.bincount(rng_b.choice(occurrences, size, replace<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb28-11"><a aria-label="11"></a>                        minlength<span class="op">=</span>counts.size).reshape(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb28-12"><a aria-label="12"></a>        )[<span class="dv">0</span>] <span class="op">==</span> base</span>
<span id="cb28-13"><a aria-label="13"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_iter)</span>
<span id="cb28-14"><a aria-label="14"></a>    )</span>
<span id="cb28-15"><a aria-label="15"></a>    <span class="cf">return</span> base, agree <span class="op">/</span> n_iter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section>
<section id="does-it-catch-the-unknown" class="slide level2 scrollable">
<h2>Does it catch the unknown?</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The test that matters</strong></p>
</div>
<div class="callout-content">
<p>Apply it to a sequence from a <strong>known</strong> genus, then to the <strong>novel</strong> ones.</p>
<div id="0eb4ffaf" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a aria-label="1"></a>known_idx <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb29-2"><a aria-label="2"></a>tax, conf <span class="op">=</span> bootstrap_confidence(clf_fitted, X[known_idx].toarray())</span>
<span id="cb29-3"><a aria-label="3"></a><span class="bu">print</span>(<span class="ss">f"  known genus  : true </span><span class="sc">{</span>labels[known_idx]<span class="sc">}</span><span class="ss">, called </span><span class="sc">{</span>tax<span class="sc">}</span><span class="ss">, confidence </span><span class="sc">{</span>conf<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb29-4"><a aria-label="4"></a></span>
<span id="cb29-5"><a aria-label="5"></a><span class="bu">print</span>(<span class="st">"  novel genus  :"</span>)</span>
<span id="cb29-6"><a aria-label="6"></a>novel_conf <span class="op">=</span> []</span>
<span id="cb29-7"><a aria-label="7"></a><span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb29-8"><a aria-label="8"></a>    tax_n, conf_n <span class="op">=</span> bootstrap_confidence(clf_fitted, Xn[r].toarray(), seed<span class="op">=</span>r)</span>
<span id="cb29-9"><a aria-label="9"></a>    novel_conf.append(conf_n)</span>
<span id="cb29-10"><a aria-label="10"></a>    <span class="bu">print</span>(<span class="ss">f"    sequence </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss">: called </span><span class="sc">{</span>tax_n<span class="sc">}</span><span class="ss">, confidence </span><span class="sc">{</span>conf_n<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb29-11"><a aria-label="11"></a><span class="bu">print</span>(<span class="ss">f"  mean confidence on novel organisms: </span><span class="sc">{</span>np<span class="sc">.</span>mean(novel_conf)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  known genus  : true Genus_A, called Genus_A, confidence 1.00
  novel genus  :
    sequence 0: called Genus_C, confidence 0.51
    sequence 1: called Genus_C, confidence 0.65
    sequence 2: called Genus_C, confidence 0.54
    sequence 3: called Genus_C, confidence 0.66
    sequence 4: called Genus_C, confidence 0.60
  mean confidence on novel organisms: 0.59</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="it-works-and-predict_proba-did-not" class="slide level2">
<h2>It works — and <code>predict_proba</code> did not</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The same predictions, two confidence measures</strong></p>
</div>
<div class="callout-content">
<p>Both measures describe the <em>identical</em> set of predictions — all ten novel sequences called <code>Genus_C</code>. They disagree completely about how much to believe them.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>known genus</th>
<th>novel genus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>predict_proba</code></td>
<td>1.000</td>
<td><strong>1.000</strong></td>
</tr>
<tr class="even">
<td>bootstrap</td>
<td>1.00</td>
<td><strong>0.59</strong></td>
</tr>
</tbody>
</table>
<p>At the <strong>0.80 threshold conventional in 16S work</strong>, every novel sequence is correctly rejected and backed off to a coarser rank. <code>predict_proba</code> rejects nothing, ever.</p>
</div>
</div>
</div>
</section>
<section id="why-the-bootstrap-sees-it" class="slide level2">
<h2>Why the bootstrap sees it</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Two questions, not one</strong></p>
</div>
<div class="callout-content">
<p><code>predict_proba</code> normalises likelihoods <em>across the training classes</em>. Whatever the evidence, the numbers sum to one, and a weak preference and an overwhelming one both come out near 1.0 once the log-likelihoods are exponentiated.</p>
<p>The bootstrap probes something else: <strong>how robust is the margin?</strong> Take 10% of the query’s <span class="math inline">\(k\)</span>-mers and the answer either survives or it does not.</p>
<ul>
<li>a genuine <code>Genus_A</code> sequence — even a tenth of its <span class="math inline">\(k\)</span>-mers point overwhelmingly one way. Confidence 1.00.</li>
<li>a novel organism — the preference for <code>Genus_C</code> rests on a handful of coincidental matches. Resample, and a different accident wins. Confidence 0.59.</li>
</ul>
<p>Fragility under resampling is a usable proxy for <em>“the evidence was thin”</em> — which is what you wanted to know and what the probability would not tell you.</p>
</div>
</div>
</div>
</section>
<section id="still-not-a-novelty-detector" class="slide level2">
<h2>Still not a novelty detector</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Do not over-read the result</strong></p>
</div>
<div class="callout-content">
<p>The bootstrap measures <strong>stability</strong>, which correlated with fit here. That is not a guarantee:</p>
<ul>
<li>0.59 is well below threshold but it is not zero — a classifier forced to choose still chose, ten times out of ten, and reported a genus.</li>
<li>A novel organism that happens to be <em>consistently</em> similar to one training class will bootstrap high and be confidently wrong. Nothing in the procedure looks outside the label set.</li>
</ul>
<p>A true novelty measure is a <strong>distance to the training data</strong>, not a confidence within it. In taxonomic practice that role is played by an alignment-identity floor: assign only if the query is within some identity of a reference.</p>
<p>Which returns us to the first half of this lecture — <strong>the classifier does not replace the search, it sits on top of it.</strong></p>
</div>
</div>
</div>
</section>
<section id="why-this-matters-here-especially" class="slide level2">
<h2>Why this matters here especially</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Biological data is never i.i.d.</strong></p>
</div>
<div class="callout-content">
<p>The independence assumption behind random cross-validation is violated by construction in biology:</p>
<ul>
<li>sequences from the same <strong>strain</strong> are near-identical</li>
<li>strains within a <strong>species</strong> are highly similar</li>
<li>species within a <strong>genus</strong> share most of their genome</li>
<li>and reference databases are <strong>biased</strong> toward organisms people study</li>
</ul>
<p>A classifier can score 99% on a benchmark and fail completely on an environmental sample full of organisms nobody has sequenced.</p>
<blockquote>
<p>Regard these methods as a starting point rather than an end-point — the same warning that will return in Bio 4 for automated cell-type annotation. It is the same underlying problem.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="splitting-by-group" class="slide level2">
<h2>Splitting by group</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The fix: make the split respect the structure</strong></p>
</div>
<div class="callout-content">
<p>Random <span class="math inline">\(k\)</span>-fold CV asks <em>can the model classify a new sequence?</em> What you almost always want to know is <em>can it classify a new <strong>organism</strong>?</em> — and that is a different question, answered by a different split.</p>
<p>The rule: <strong>split at the level you want to generalise to.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>you want to claim</th>
<th>group by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>works on a new read from a known strain</td>
<td>nothing — random is fine</td>
</tr>
<tr class="even">
<td>works on a new strain</td>
<td>strain</td>
</tr>
<tr class="odd">
<td>works on a new species</td>
<td>species</td>
</tr>
<tr class="even">
<td>works on an uncultured environmental organism</td>
<td>genus, or higher</td>
</tr>
</tbody>
</table>
<p>In <code>scikit-learn</code> this is <code>GroupKFold</code>, <code>StratifiedGroupKFold</code> or <code>LeaveOneGroupOut</code>, passing <code>groups=</code>. It is one keyword argument, and it is the difference between a number you can report and a number you cannot.</p>
</div>
</div>
</div>
</section>
<section id="expect-the-score-to-drop" class="slide level2">
<h2>Expect the score to drop</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And let it</strong></p>
</div>
<div class="callout-content">
<p>A grouped score is <em>supposed</em> to be lower than a random one. If it is not, either there is no structure in your data or the grouping does not capture it.</p>
<p>The temptation — to report the higher number because the lower one “looks bad” — is exactly how the leakage literature says published results get inflated.</p>
</div>
</div>
</div>
</section>
<section id="accuracy-is-the-wrong-headline" class="slide level2">
<h2>Accuracy is the wrong headline</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What to report instead</strong></p>
</div>
<div class="callout-content">
<p>Accuracy hides everything that matters when classes are imbalanced, and taxonomic data is always imbalanced — reference databases have thousands of <em>E. coli</em> and one of most things.</p>
<p>A classifier that labels <strong>everything</strong> as the majority genus can score 95% accuracy and be useless. Report instead:</p>
<ul>
<li><strong>per-class recall</strong> — which genera does it systematically miss? The rare ones, invariably.</li>
<li><strong>macro-averaged F1</strong> — treats every class equally rather than weighting by frequency.</li>
<li><strong>the confusion matrix</strong> — the only output that shows <em>what it confuses with what</em>. Confusions between closely related genera are expected and tolerable; confusions between distant ones mean something is broken.</li>
<li><strong>accuracy at each rank</strong> — a classifier that is 60% right at genus may be 95% right at phylum. Reporting the rank you actually achieved is more useful than reporting the rank you wanted.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="what-a-classifier-should-output" class="slide level2">
<h2>What a classifier should output</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Three properties worth demanding</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>A calibrated confidence.</strong> Not just a preferred class, but a number that means something — among the cases it reports at 0.9, roughly 90% should be right. Naive Bayes confidences are notoriously <strong>over-confident</strong>, because the independence assumption multiplies correlated evidence as though it were independent. Calibrate (<code>CalibratedClassifierCV</code>) before believing a probability.</li>
<li><strong>The ability to abstain.</strong> Below a confidence threshold, report nothing, or report at a coarser rank. A pipeline that must answer will invent answers — as this one did, at confidence 1.000.</li>
<li><strong>A record of what it was trained on.</strong> The only way anybody can judge whether your sample resembles the training distribution.</li>
</ol>
<p>The RDP classifier and <code>q2-feature-classifier</code> do all three. A <code>MultinomialNB</code> you fitted yourself does none of them by default.</p>
</div>
</div>
</div>
</section>
<section id="choosing-k" class="slide level2 scrollable">
<h2>Choosing <span class="math inline">\(k\)</span></h2>
<div id="5549b5d5" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a aria-label="1"></a>rows <span class="op">=</span> []</span>
<span id="cb31-2"><a aria-label="2"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>, <span class="dv">10</span>):</span>
<span id="cb31-3"><a aria-label="3"></a>    v <span class="op">=</span> CountVectorizer(analyzer<span class="op">=</span><span class="st">"char"</span>, ngram_range<span class="op">=</span>(k, k))</span>
<span id="cb31-4"><a aria-label="4"></a>    Xk <span class="op">=</span> v.fit_transform(sequences)</span>
<span id="cb31-5"><a aria-label="5"></a>    rows.append((k, <span class="dv">4</span><span class="op">**</span>k, Xk.shape[<span class="dv">1</span>], <span class="dv">100</span> <span class="op">*</span> Xk.nnz <span class="op">/</span> (Xk.shape[<span class="dv">0</span>] <span class="op">*</span> Xk.shape[<span class="dv">1</span>])))</span>
<span id="cb31-6"><a aria-label="6"></a>    <span class="bu">print</span>(<span class="ss">f"  k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span><span class="dv">4</span><span class="op">**</span>k<span class="sc">:&gt;7}</span><span class="ss"> possible, </span><span class="sc">{</span>Xk<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">:&gt;6}</span><span class="ss"> observed, "</span></span>
<span id="cb31-7"><a aria-label="7"></a>          <span class="ss">f"</span><span class="sc">{</span>rows[<span class="op">-</span><span class="dv">1</span>][<span class="dv">3</span>]<span class="sc">:5.1f}</span><span class="ss">% of the matrix non-zero"</span>)</span>
<span id="cb31-8"><a aria-label="8"></a></span>
<span id="cb31-9"><a aria-label="9"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">3</span>))</span>
<span id="cb31-10"><a aria-label="10"></a>ax.semilogy([r[<span class="dv">0</span>] <span class="cf">for</span> r <span class="kw">in</span> rows], [r[<span class="dv">1</span>] <span class="cf">for</span> r <span class="kw">in</span> rows], <span class="st">"o-"</span>, label<span class="op">=</span><span class="st">"possible $4^k$"</span>)</span>
<span id="cb31-11"><a aria-label="11"></a>ax.semilogy([r[<span class="dv">0</span>] <span class="cf">for</span> r <span class="kw">in</span> rows], [r[<span class="dv">2</span>] <span class="cf">for</span> r <span class="kw">in</span> rows], <span class="st">"s-"</span>, label<span class="op">=</span><span class="st">"actually observed"</span>)</span>
<span id="cb31-12"><a aria-label="12"></a>ax.set_xlabel(<span class="st">"k"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"number of $k$-mers"</span>)</span>
<span id="cb31-13"><a aria-label="13"></a>ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  k=3:      64 possible,     64 observed,  99.8% of the matrix non-zero
  k=4:     256 possible,    256 observed,  79.3% of the matrix non-zero
  k=5:    1024 possible,   1024 observed,  31.9% of the matrix non-zero
  k=6:    4096 possible,   3931 observed,   9.5% of the matrix non-zero
  k=7:   16384 possible,   9738 observed,   4.0% of the matrix non-zero
  k=8:   65536 possible,  14628 observed,   2.7% of the matrix non-zero
  k=9:  262144 possible,  17679 observed,   2.2% of the matrix non-zero</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio2_files/figure-revealjs/cell-21-output-2.png" width="544" height="324"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The trade-off</strong></p>
</div>
<div class="callout-content">
<p>The two curves separate sharply. Below <span class="math inline">\(k \approx 5\)</span> every possible <span class="math inline">\(k\)</span>-mer is observed, so the features carry almost no positional information — all sequences look alike. Above <span class="math inline">\(k \approx 7\)</span> most <span class="math inline">\(k\)</span>-mers are seen <strong>once or never</strong>: the vector becomes mostly zeros, counts stop being estimates of anything, and the classifier is fitting noise.</p>
<p>Useful values for 16S work are typically <strong>6–8</strong> — large enough to be specific, small enough that counts are still counts. The right value depends on sequence length and how closely related your classes are, and is worth tuning rather than assuming.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center">
<h1>Wrap-up</h1>

</section>
<section id="what-we-covered" class="slide level2 scrollable">
<h2>What we covered</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Summary</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>idea</th>
<th>point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>homolog / ortholog / paralog</td>
<td>homology is binary and historical; the best hit may be a paralog</td>
</tr>
<tr class="even">
<td>the database</td>
<td>redundant, mostly inferred, biased — all of which flatter you</td>
</tr>
<tr class="odd">
<td>database search</td>
<td>exhaustive alignment is <span class="math inline">\(\sim10^{15}\)</span> cells — infeasible</td>
</tr>
<tr class="even">
<td><span class="math inline">\(k\)</span>-mer prefilter</td>
<td>cheap Jaccard ranks like expensive SW</td>
</tr>
<tr class="odd">
<td>seed-and-extend</td>
<td>skip the matrix; this is BLAST</td>
</tr>
<tr class="even">
<td>word size</td>
<td>the main dial; <code>megablast</code> misses remote homology by design</td>
</tr>
<tr class="odd">
<td>search in protein space</td>
<td>synonymous changes hide nucleotide homology</td>
</tr>
<tr class="even">
<td>the cost</td>
<td><strong>distant homologs are lost</strong></td>
</tr>
<tr class="odd">
<td>bit score vs E-value</td>
<td>one describes the alignment, one the search space</td>
</tr>
<tr class="even">
<td>profiles</td>
<td>a family carries information a pair cannot</td>
</tr>
<tr class="odd">
<td>sensitivity/specificity</td>
<td>a decision about consequences, not statistics</td>
</tr>
<tr class="even">
<td>the feature table</td>
<td><span class="math inline">\(n \times p\)</span> + labels — the only interface, and where the modelling happens</td>
</tr>
<tr class="odd">
<td>unsupervised first</td>
<td>look before classifying; ordination is how you check the labels mean something</td>
</tr>
<tr class="even">
<td>ordination</td>
<td>PCoA = dimensionality reduction in ecology’s vocabulary; read the scree cliff</td>
</tr>
<tr class="odd">
<td>reading an ordination</td>
<td>axis order matters, axes are not two findings, direction is arbitrary</td>
</tr>
<tr class="even">
<td>Naive Bayes</td>
<td>wrong assumption, useful ranking, very fast, over-confident</td>
</tr>
<tr class="odd">
<td>bootstrap confidence</td>
<td>resample the query’s <span class="math inline">\(k\)</span>-mers — 1.00 known vs <strong>0.59</strong> novel, where <code>predict_proba</code> said 1.000 both times</td>
</tr>
<tr class="even">
<td><strong>leakage</strong></td>
<td>biological data is not i.i.d.; split at the level you want to generalise to</td>
</tr>
<tr class="odd">
<td>abstention</td>
<td>a classifier that must answer will invent answers</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="the-thread-through-both-lectures" class="slide level2">
<h2>The thread through both lectures</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Exact, then approximate</strong></p>
</div>
<div class="callout-content">
<p>Lecture 1 built an algorithm that is <strong>provably optimal</strong> and quadratic. Lecture 2 threw the guarantee away to get three orders of magnitude, and then spent its time on the question that replaces it: <em>how do we know the approximation is good enough?</em></p>
<p>Sensitivity, specificity, E-values and honest cross-validation are all answers to that one question.</p>
<p>That pattern — optimality abandoned, then the loss quantified — is the same one you saw in scheduling, and it is most of what applied computing consists of.</p>
</div>
</div>
</div>
</section>
<section id="exercises" class="slide level2 scrollable">
<h2>Exercises</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Try these</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Vary <span class="math inline">\(k\)</span> in the Jaccard filter from 3 to 12. At which <span class="math inline">\(k\)</span> do unrelated sequences stop sharing any <span class="math inline">\(k\)</span>-mers, and why is that not automatically better?</li>
<li>Add a <code>min_shared</code> sweep to the inverted-index filter. Plot candidates surviving against the threshold, and mark the point where the true homolog is lost.</li>
<li>Implement a minimizer index: keep only the smallest <span class="math inline">\(k\)</span>-mer per window of <span class="math inline">\(w\)</span>. Measure how index size and homolog recall change as <span class="math inline">\(w\)</span> grows.</li>
<li>In the threshold plot, add a curve for <strong>precision</strong>. Why does it depend on how many homologs the database contains, when sensitivity does not?</li>
<li>Generate homologs at 45% and 60% divergence. At what point does the <span class="math inline">\(k\)</span>-mer filter fail completely?</li>
<li>Translate the diverged sequences to protein and repeat the detection-limit experiment. How much further out does homology stay visible?</li>
<li>Recompute the distance matrix with a different metric — <code>braycurtis</code> on counts rather than <code>jaccard</code> on presence/absence. Does the PCoA change? Which is more sensitive to sequence length?</li>
<li>Plot PC2 against PC3 instead of PC1 against PC2. Relate what you see to the scree cliff.</li>
<li>Sweep the bootstrap <code>frac</code> from 0.02 to 0.5. At what subsample size does the novel-organism confidence stop separating from the known one, and why?</li>
<li>Restructure the synthetic genera so each contains several distinct “strains”, then compare <code>cross_val_score</code> with <code>GroupKFold(groups=strain)</code>. Reproduce the inflated score and explain the gap to somebody else.</li>
<li>Replace <code>MultinomialNB</code> with logistic regression and a random forest under grouped CV. Does the ranking of methods change?</li>
<li>Add an abstention rule: report <code>Unassigned</code> below a bootstrap confidence of 0.8. Sweep the threshold and plot the fraction assigned against the accuracy of what was assigned.</li>
<li>Wrap the classifier in <code>CalibratedClassifierCV</code> and compare predicted confidence against observed accuracy. How over-confident was <code>predict_proba</code>?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="further-reading" class="slide level2 scrollable">
<h2>Further reading</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sources</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Caporaso</strong>, <em>An Introduction to Applied Bioinformatics</em>, 2nd ed.&nbsp;<a href="https://readiab.org" class="uri">https://readiab.org</a> — CC BY-NC-SA 4.0</li>
<li><strong>Altschul, Gish, Miller, Myers &amp; Lipman</strong>, <em>Basic local alignment search tool</em> (BLAST), <strong>J. Mol. Biol.</strong> 215(3), 1990, 403–410. <a href="https://doi.org/10.1016/S0022-2836(05)80360-2" class="uri">https://doi.org/10.1016/S0022-2836(05)80360-2</a></li>
<li><strong>Altschul et al.</strong>, <em>Gapped BLAST and PSI-BLAST</em>, <strong>Nucleic Acids Research</strong> 25(17), 1997. <a href="https://doi.org/10.1093/nar/25.17.3389" class="uri">https://doi.org/10.1093/nar/25.17.3389</a></li>
<li><strong>Karlin &amp; Altschul</strong>, <em>Methods for assessing the statistical significance of molecular sequence features</em> (E-values), <strong>PNAS</strong> 87(6), 1990. <a href="https://doi.org/10.1073/pnas.87.6.2264" class="uri">https://doi.org/10.1073/pnas.87.6.2264</a></li>
<li><strong>Ma, Tromp &amp; Li</strong>, <em>PatternHunter: faster and more sensitive homology search</em> (spaced seeds), <strong>Bioinformatics</strong> 18(3), 2002.</li>
<li><strong>Eddy</strong>, <em>Accelerated profile HMM searches</em> (HMMER3), <strong>PLoS Computational Biology</strong> 7(10), 2011.</li>
<li><strong>Roberts, Hayes, Hunt, Mount &amp; Yorke</strong>, <em>Reducing storage requirements for biological sequence comparison</em> (minimizers), <strong>Bioinformatics</strong> 20(18), 2004. <a href="https://doi.org/10.1093/bioinformatics/bth408" class="uri">https://doi.org/10.1093/bioinformatics/bth408</a></li>
<li><strong>Wang, Garrity, Tiedje &amp; Cole</strong>, <em>Naive Bayesian classifier for rapid assignment of rRNA sequences</em> (RDP), <strong>Applied and Environmental Microbiology</strong> 73(16), 2007. <a href="https://doi.org/10.1128/AEM.00062-07" class="uri">https://doi.org/10.1128/AEM.00062-07</a></li>
<li><strong>Bokulich et al.</strong>, <em>Optimizing taxonomic classification of marker-gene amplicon sequences with QIIME 2</em>, <strong>Microbiome</strong> 6, 2018. <a href="https://doi.org/10.1186/s40168-018-0470-z" class="uri">https://doi.org/10.1186/s40168-018-0470-z</a></li>
<li><strong>Kapoor &amp; Narayanan</strong>, <em>Leakage and the reproducibility crisis in machine-learning-based science</em>, <strong>Patterns</strong> 4(9), 2023. <a href="https://doi.org/10.1016/j.patter.2023.100804" class="uri">https://doi.org/10.1016/j.patter.2023.100804</a></li>
</ul>
</div>
</div>
</div>
</section>
<section id="end-of-the-series" class="slide level2">
<h2>End of the series</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Four lectures, two scales</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Bio 1</strong></td>
<td>sequences; alignment as dynamic programming</td>
</tr>
<tr class="even">
<td><strong>Bio 2</strong></td>
<td>search and classification; heuristics and their evaluation</td>
</tr>
<tr class="odd">
<td><strong>Bio 3</strong></td>
<td>single-cell data; QC, normalization, dimensionality reduction</td>
</tr>
<tr class="even">
<td><strong>Bio 4</strong></td>
<td>cellular structure; clustering, annotation, integration, conditions</td>
</tr>
</tbody>
</table>
<p>The sequence half is about <strong>one molecule at a time, exactly</strong>. The single-cell half is about <strong>millions of measurements, statistically</strong>. Both end at the same place: an approximate answer whose error you have to characterise yourself.</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/socket.io.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/multiplex.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'multiplex': {"url":"https://mplex.vitv.ly","secret":null,"id":"1b1a8e6a2af9232259dacb73d7f8b1863a3ca4a4ac192dbb7a2a67a3fc04e125"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dslnu\.github\.io\/data_analytics\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>