<!DOCTYPE html>
<html lang="en"><head>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="MSDE">
  <title>Big Data analytics / Applied Data analytics – Bioinformatics 4</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="custom.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Bioinformatics 4</h1>
  <p class="subtitle">Cellular structure and conditions</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
MSDE
</div>
        <p class="quarto-title-affiliation">
            Lviv University
          </p>
    </div>
</div>

</section>
<section id="identifying-cellular-structure" class="slide level2">
<h2>Identifying cellular structure</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Where we are</strong></p>
</div>
<div class="callout-content">
<p>Last lecture ended with a <strong>UMAP and a neighbour graph</strong> — cells arranged by similarity, but entirely anonymous. Groups are visible; nothing is named.</p>
<p>This lecture turns that into biology, in four steps:</p>
<ol type="1">
<li><strong>Clustering</strong> — partition the graph into groups</li>
<li><strong>Annotation</strong> — give the groups names</li>
<li><strong>Integration</strong> — reconcile groups across batches</li>
<li><strong>Conditions</strong> — ask what changed between samples</li>
</ol>
<p>Source: <strong>Single-cell best practices</strong> (Apache 2.0), <a href="https://www.sc-best-practices.org" class="uri">https://www.sc-best-practices.org</a></p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And the honest framing</strong></p>
</div>
<div class="callout-content">
<p>Steps 1 and 2 are where single-cell analysis stops being a pipeline and starts being an argument. There is no objectively correct number of clusters, and no algorithm that reliably names them.</p>
</div>
</div>
</div>
</section>
<section id="setting-up" class="slide level2 scrollable">
<h2>Setting up</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The same PBMC3k, preprocessed as in lecture 3</strong></p>
</div>
<div class="callout-content">
<div id="7d00155d" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a aria-label="1"></a>adata <span class="op">=</span> sc.datasets.pbmc3k()</span>
<span id="cb1-2"><a aria-label="2"></a>sc.pp.filter_cells(adata, min_genes<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb1-3"><a aria-label="3"></a>sc.pp.filter_genes(adata, min_cells<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb1-4"><a aria-label="4"></a></span>
<span id="cb1-5"><a aria-label="5"></a>adata.layers[<span class="st">"counts"</span>] <span class="op">=</span> adata.X.copy()</span>
<span id="cb1-6"><a aria-label="6"></a>sc.pp.normalize_total(adata)</span>
<span id="cb1-7"><a aria-label="7"></a>sc.pp.log1p(adata)</span>
<span id="cb1-8"><a aria-label="8"></a>adata.layers[<span class="st">"log1p_norm"</span>] <span class="op">=</span> adata.X.copy()</span>
<span id="cb1-9"><a aria-label="9"></a></span>
<span id="cb1-10"><a aria-label="10"></a>sc.pp.highly_variable_genes(adata, n_top_genes<span class="op">=</span><span class="dv">2000</span>)</span>
<span id="cb1-11"><a aria-label="11"></a>sc.pp.pca(adata, n_comps<span class="op">=</span><span class="dv">50</span>, mask_var<span class="op">=</span><span class="st">"highly_variable"</span>)</span>
<span id="cb1-12"><a aria-label="12"></a>sc.pp.neighbors(adata, n_neighbors<span class="op">=</span><span class="dv">15</span>, n_pcs<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb1-13"><a aria-label="13"></a>sc.tl.umap(adata)</span>
<span id="cb1-14"><a aria-label="14"></a><span class="bu">print</span>(adata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>AnnData object with n_obs × n_vars = 2700 × 9713
    obs: 'n_genes'
    var: 'gene_ids', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'hvg', 'pca', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'
    layers: None (.X), 'counts', 'log1p_norm'</code></pre>
</div>
</div>
</div>
</div>
</div>
<!-- =========================================================================
     SOURCE: sc-best-practices, Identifying cellular structure / "Clustering"
       https://www.sc-best-practices.org/cellular_structure/clustering.html
       Motivation | graph-based community detection | Leiden | resolution
       Leiden vs Louvain: Traag et al. 2019, doi 10.1038/s41598-019-41695-z
     ========================================================================= -->
</section>
<section>
<section id="clustering" class="title-slide slide level1 center">
<h1>Clustering</h1>

</section>
<section id="what-clustering-means-here" class="slide level2">
<h2>What clustering means here</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Not k-means on the expression matrix</strong></p>
</div>
<div class="callout-content">
<p>We do <strong>not</strong> cluster in gene space. We cluster the <strong>neighbour graph</strong> built in PCA space — the <code>connectivities</code> matrix from last lecture.</p>
<p>The task becomes <em>community detection</em>: find groups of nodes that are more densely connected to each other than to the rest of the graph.</p>
<p>This matters because it inherits every choice made upstream: the number of PCs, <span class="math inline">\(k\)</span>, and the feature selection all shaped the graph, and the graph is all the clustering algorithm sees.</p>
</div>
</div>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why graph-based rather than k-means</strong></p>
</div>
<div class="callout-content">
<ul>
<li>no assumption that clusters are spherical or equally sized — cell types are neither</li>
<li>works in the high-dimensional sparse regime where Euclidean distance degrades</li>
<li>scales to millions of cells, since the graph is sparse</li>
</ul>
</div>
</div>
</div>
</section>
<section id="modularity" class="slide level2">
<h2>Modularity</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What the algorithms optimise</strong></p>
</div>
<div class="callout-content">
<p><strong>Modularity</strong> <span class="math inline">\(Q\)</span> measures how many edges fall <em>inside</em> communities compared with how many you would expect if the same nodes were wired at random:</p>
<p><span class="math display">\[Q = \frac{1}{2m}\sum_{ij}\left(A_{ij} - \frac{k_i k_j}{2m}\right)\delta(c_i, c_j)\]</span></p>
<p>where <span class="math inline">\(A\)</span> is the adjacency matrix, <span class="math inline">\(k_i\)</span> the degree of node <span class="math inline">\(i\)</span>, <span class="math inline">\(m\)</span> the edge count, and <span class="math inline">\(\delta(c_i,c_j)\)</span> is 1 when <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> share a community.</p>
<p>High <span class="math inline">\(Q\)</span> = the partition captures real structure rather than the degree distribution.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Modularity has a resolution limit</strong></p>
</div>
<div class="callout-content">
<p>Maximising <span class="math inline">\(Q\)</span> systematically <strong>cannot detect communities below a certain size</strong>, which depends on the size of the whole graph. Rare cell types are exactly what this hides — and rare cell types are often the point of the experiment.</p>
</div>
</div>
</div>
</section>
<section id="louvain-then-leiden" class="slide level2">
<h2>Louvain, then Leiden</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why the field switched</strong></p>
</div>
<div class="callout-content">
<p><strong>Louvain</strong> (2008) greedily moves nodes between communities to increase <span class="math inline">\(Q\)</span>, then aggregates and repeats. Fast, and for a decade the default.</p>
<p><strong>Leiden</strong> (2019) fixes a real defect: Louvain can produce <strong>internally disconnected communities</strong> — a “cluster” that is actually two groups with no path between them inside the cluster. Traag et al.&nbsp;showed this is not rare.</p>
<p>Leiden adds a refinement phase guaranteeing every community is internally connected, and is usually faster too.</p>
<blockquote>
<p>Use Leiden. Louvain remains in the codebase for reproducing older analyses.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="the-resolution-parameter" class="slide level2 scrollable">
<h2>The resolution parameter</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The only knob that really matters</strong></p>
</div>
<div class="callout-content">
<p>Resolution <span class="math inline">\(\gamma\)</span> scales the penalty term in the objective. Low <span class="math inline">\(\gamma\)</span> → few large clusters; high <span class="math inline">\(\gamma\)</span> → many small ones. It does <strong>not</strong> have a correct value.</p>
<div id="5ca21081" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a aria-label="1"></a><span class="cf">for</span> res <span class="kw">in</span> (<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>):</span>
<span id="cb3-2"><a aria-label="2"></a>    sc.tl.leiden(</span>
<span id="cb3-3"><a aria-label="3"></a>        adata,</span>
<span id="cb3-4"><a aria-label="4"></a>        resolution<span class="op">=</span>res,</span>
<span id="cb3-5"><a aria-label="5"></a>        key_added<span class="op">=</span><span class="ss">f"leiden_</span><span class="sc">{</span>res<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb3-6"><a aria-label="6"></a>        flavor<span class="op">=</span><span class="st">"igraph"</span>,</span>
<span id="cb3-7"><a aria-label="7"></a>        n_iterations<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb3-8"><a aria-label="8"></a>        directed<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb3-9"><a aria-label="9"></a>    )</span>
<span id="cb3-10"><a aria-label="10"></a>    n <span class="op">=</span> adata.obs[<span class="ss">f"leiden_</span><span class="sc">{</span>res<span class="sc">}</span><span class="ss">"</span>].nunique()</span>
<span id="cb3-11"><a aria-label="11"></a>    <span class="bu">print</span>(<span class="ss">f"  resolution </span><span class="sc">{</span>res<span class="sc">:&lt;5}</span><span class="ss"> -&gt; </span><span class="sc">{</span>n<span class="sc">:&gt;3}</span><span class="ss"> clusters"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  resolution 0.25  -&gt;   7 clusters
  resolution 0.5   -&gt;   9 clusters
  resolution 1.0   -&gt;  13 clusters
  resolution 2.0   -&gt;  16 clusters</code></pre>
</div>
</div>
<p>Same graph, same data, same algorithm — and a factor of eight in <span class="math inline">\(\gamma\)</span> roughly doubles the cluster count. <strong>Every one of those partitions is defensible.</strong></p>
</div>
</div>
</div>
</section>
<section id="the-resolution-parameter-1" class="slide level2 scrollable">
<h2>The resolution parameter</h2>
<div id="4af0e3ce" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a aria-label="1"></a>sc.pl.umap(</span>
<span id="cb5-2"><a aria-label="2"></a>    adata,</span>
<span id="cb5-3"><a aria-label="3"></a>    color<span class="op">=</span>[<span class="st">"leiden_0.25"</span>, <span class="st">"leiden_0.5"</span>, <span class="st">"leiden_1.0"</span>, <span class="st">"leiden_2.0"</span>],</span>
<span id="cb5-4"><a aria-label="4"></a>    ncols<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb5-5"><a aria-label="5"></a>    legend_loc<span class="op">=</span><span class="st">"on data"</span>,</span>
<span id="cb5-6"><a aria-label="6"></a>    show<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-7"><a aria-label="7"></a>)</span>
<span id="cb5-8"><a aria-label="8"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-5-output-1.png" width="1002" height="768"></p>
</figure>
</div>
</div>
</div>
<p>The large populations stay stable; it is the <strong>boundaries between related subtypes</strong> that split and re-split as <span class="math inline">\(\gamma\)</span> rises. <strong>Neither extreme is wrong</strong> — they answer different questions, at different levels of the cell-type hierarchy.</p>
</section>
<section id="how-to-choose" class="slide level2">
<h2>How to choose</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>There is no statistic that settles it</strong></p>
</div>
<div class="callout-content">
<p>What people actually do, in rough order of honesty:</p>
<ul>
<li><strong>Marker-driven</strong> — pick the resolution at which clusters correspond to markers you can interpret. Circular, but it is what the biology demands.</li>
<li><strong>Stability</strong> — cluster repeatedly on subsamples and keep partitions that recur. Expensive; detects clusters that are noise.</li>
<li><strong>Hierarchy</strong> — cluster coarsely, then sub-cluster within a group of interest. Often the most practical: one resolution need not serve every question.</li>
<li><strong>Silhouette / Calinski-Harabasz</strong> — geometric scores. Weak here, since they assume compact clusters in a metric space and we are in a graph.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The thing to tell students</strong></p>
</div>
<div class="callout-content">
<p>A cluster is <strong>a hypothesis about a group of cells</strong>, not a discovery. It becomes a finding only once markers, and ideally an orthogonal dataset, support it.</p>
</div>
</div>
</div>
</section>
<section id="sub-clustering" class="slide level2 scrollable">
<h2>Sub-clustering</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>One resolution need not serve every question</strong></p>
</div>
<div class="callout-content">
<p>The practical answer to the resolution problem: cluster coarsely, then <strong>re-cluster within a group of interest</strong>. The sub-graph is rebuilt from only those cells, so the variable genes and PCs are chosen for <em>their</em> heterogeneity rather than the whole dataset’s.</p>
<div id="c6ef3f37" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a aria-label="1"></a>big <span class="op">=</span> adata.obs[<span class="st">"leiden_0.25"</span>].value_counts().idxmax()</span>
<span id="cb6-2"><a aria-label="2"></a>sub <span class="op">=</span> adata[adata.obs[<span class="st">"leiden_0.25"</span>] <span class="op">==</span> big].copy()</span>
<span id="cb6-3"><a aria-label="3"></a><span class="bu">print</span>(<span class="ss">f"sub-clustering cluster </span><span class="sc">{</span>big<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>sub<span class="sc">.</span>n_obs<span class="sc">}</span><span class="ss"> cells"</span>)</span>
<span id="cb6-4"><a aria-label="4"></a></span>
<span id="cb6-5"><a aria-label="5"></a>sc.pp.highly_variable_genes(sub, n_top_genes<span class="op">=</span><span class="dv">1500</span>)</span>
<span id="cb6-6"><a aria-label="6"></a>sc.pp.pca(sub, n_comps<span class="op">=</span><span class="dv">30</span>, mask_var<span class="op">=</span><span class="st">"highly_variable"</span>)</span>
<span id="cb6-7"><a aria-label="7"></a>sc.pp.neighbors(sub, n_neighbors<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb6-8"><a aria-label="8"></a>sc.tl.leiden(sub, resolution<span class="op">=</span><span class="fl">0.5</span>, key_added<span class="op">=</span><span class="st">"sub"</span>,</span>
<span id="cb6-9"><a aria-label="9"></a>             flavor<span class="op">=</span><span class="st">"igraph"</span>, n_iterations<span class="op">=</span><span class="dv">2</span>, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-10"><a aria-label="10"></a><span class="bu">print</span>(<span class="st">"sub-clusters found:"</span>, sub.obs[<span class="st">"sub"</span>].nunique())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>sub-clustering cluster 2: 1133 cells
sub-clusters found: 4</code></pre>
</div>
</div>
<p>Structure that was invisible at the top level becomes resolvable, because the PCA is no longer dominated by the difference between <em>T cells and monocytes</em>.</p>
</div>
</div>
</div>
</section>
<section id="sub-clustering-1" class="slide level2 scrollable">
<h2>Sub-clustering</h2>
<div id="091612d3" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a aria-label="1"></a>sc.tl.umap(sub)</span>
<span id="cb8-2"><a aria-label="2"></a>sc.pl.umap(sub, color<span class="op">=</span><span class="st">"sub"</span>, legend_loc<span class="op">=</span><span class="st">"on data"</span>, show<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb8-3"><a aria-label="3"></a>           title<span class="op">=</span><span class="ss">f"sub-clusters within cluster </span><span class="sc">{</span>big<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-4"><a aria-label="4"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-7-output-1.png" width="451" height="381"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="is-a-cluster-real" class="slide level2 scrollable">
<h2>Is a cluster real?</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A cheap stability check</strong></p>
</div>
<div class="callout-content">
<p>Cluster repeatedly on random subsamples. A partition that survives resampling is more credible than one that does not.</p>
<div id="00c108ab" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a aria-label="1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> adjusted_rand_score</span>
<span id="cb9-2"><a aria-label="2"></a></span>
<span id="cb9-3"><a aria-label="3"></a>rng_s <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb9-4"><a aria-label="4"></a>base <span class="op">=</span> adata.obs[<span class="st">"leiden_1.0"</span>].astype(<span class="bu">str</span>).values</span>
<span id="cb9-5"><a aria-label="5"></a>scores <span class="op">=</span> []</span>
<span id="cb9-6"><a aria-label="6"></a><span class="cf">for</span> rep <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb9-7"><a aria-label="7"></a>    idx <span class="op">=</span> rng_s.choice(adata.n_obs, size<span class="op">=</span><span class="bu">int</span>(<span class="fl">0.8</span> <span class="op">*</span> adata.n_obs), replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-8"><a aria-label="8"></a>    sub_a <span class="op">=</span> adata[idx].copy()</span>
<span id="cb9-9"><a aria-label="9"></a>    sc.pp.neighbors(sub_a, n_neighbors<span class="op">=</span><span class="dv">15</span>, n_pcs<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb9-10"><a aria-label="10"></a>    sc.tl.leiden(sub_a, resolution<span class="op">=</span><span class="fl">1.0</span>, key_added<span class="op">=</span><span class="st">"r"</span>,</span>
<span id="cb9-11"><a aria-label="11"></a>                 flavor<span class="op">=</span><span class="st">"igraph"</span>, n_iterations<span class="op">=</span><span class="dv">2</span>, directed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-12"><a aria-label="12"></a>    scores.append(adjusted_rand_score(base[idx], sub_a.obs[<span class="st">"r"</span>].astype(<span class="bu">str</span>).values))</span>
<span id="cb9-13"><a aria-label="13"></a></span>
<span id="cb9-14"><a aria-label="14"></a><span class="bu">print</span>(<span class="st">"adjusted Rand index vs full clustering:"</span>,</span>
<span id="cb9-15"><a aria-label="15"></a>      [<span class="bu">round</span>(x, <span class="dv">3</span>) <span class="cf">for</span> x <span class="kw">in</span> scores])</span>
<span id="cb9-16"><a aria-label="16"></a><span class="bu">print</span>(<span class="st">"mean:"</span>, <span class="bu">round</span>(<span class="bu">float</span>(np.mean(scores)), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>adjusted Rand index vs full clustering: [0.892, 0.874, 0.914]
mean: 0.894</code></pre>
</div>
</div>
<p>ARI near 1 means the partition is reproduced on 80% subsamples; well below 1 means the boundaries move, and you should not build an argument on their exact placement.</p>
</div>
</div>
</div>
<!-- =========================================================================
     SOURCE: sc-best-practices, Identifying cellular structure / "Annotation"
       https://www.sc-best-practices.org/cellular_structure/annotation.html
       Manual annotation | From markers to cluster annotation | From cluster
       DE genes to annotation (incl. the inflated p-value warning) |
       Marker-gene classifiers | Wider-gene-set classifiers (CellTypist) |
       Annotation by mapping to a reference (scArches) + uncertainty
     ========================================================================= -->
</section></section>
<section>
<section id="annotation" class="title-slide slide level1 center">
<h1>Annotation</h1>

</section>
<section id="what-is-a-cell-type" class="slide level2">
<h2>What is a cell type?</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The definitional problem comes first</strong></p>
</div>
<div class="callout-content">
<blockquote>
<p>A cell type is a cellular phenotype that is robust across datasets, identifiable by specific marker genes or proteins, and tied to a distinct biological function.</p>
</blockquote>
<p>But as the book notes, <em>like with any categorization the size of categories and the borders drawn between them are partly arbitrary</em>.</p>
<p>Is a “CD4 T cell” a type? Or are naive, memory, regulatory and effector CD4 T cells four types? Both answers are used in practice, in the same tissue, by different labs.</p>
<p><strong>Cell type is a hierarchy with no canonical depth</strong> — which is exactly why the resolution parameter has no correct value.</p>
</div>
</div>
</div>
</section>
<section id="manual-annotation" class="slide level2 scrollable">
<h2>Manual annotation</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Marker genes</strong></p>
</div>
<div class="callout-content">
<p>The classical approach predates single-cell entirely: identify a cell type by a small set of genes known to mark it. It carries over from FACS panels of 30–40 proteins.</p>
<p>Two directions, used together:</p>
<ol type="1">
<li><strong>markers → clusters</strong> — start from a literature marker list, find which clusters express them</li>
<li><strong>clusters → markers</strong> — compute what is differentially expressed in each cluster, then look those genes up</li>
</ol>
<p>You move back and forth. Neither alone is sufficient.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Annotate clusters, never single cells</strong></p>
</div>
<div class="callout-content">
<p>Dropout makes a per-cell call unreliable: a cell can be a B cell and still show zero counts for <code>CD79A</code>, simply because that transcript was not captured.</p>
<p>Clustering aggregates over the dropout. This is the main reason annotation happens at cluster level.</p>
</div>
</div>
</div>
</section>
<section id="markers-per-cluster" class="slide level2 scrollable">
<h2>Markers per cluster</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Wilcoxon rank-sum, one cluster against the rest</strong></p>
</div>
<div class="callout-content">
<div id="65a966d3" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a aria-label="1"></a>adata.obs[<span class="st">"leiden"</span>] <span class="op">=</span> adata.obs[<span class="st">"leiden_1.0"</span>]</span>
<span id="cb11-2"><a aria-label="2"></a>sc.tl.rank_genes_groups(adata, <span class="st">"leiden"</span>, method<span class="op">=</span><span class="st">"wilcoxon"</span>)</span>
<span id="cb11-3"><a aria-label="3"></a></span>
<span id="cb11-4"><a aria-label="4"></a>pd.DataFrame(adata.uns[<span class="st">"rank_genes_groups"</span>][<span class="st">"names"</span>]).head(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>CCL5</td>
<td>CD74</td>
<td>LTB</td>
<td>MALAT1</td>
<td>RPS12</td>
<td>CST3</td>
<td>S100A8</td>
<td>LST1</td>
<td>NKG7</td>
<td>CCL5</td>
<td>HLA-DPB1</td>
<td>PF4</td>
<td>ACTG1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>GZMK</td>
<td>HLA-DRA</td>
<td>IL32</td>
<td>RPL32</td>
<td>RPS6</td>
<td>LYZ</td>
<td>S100A9</td>
<td>FCGR3A</td>
<td>GNLY</td>
<td>NKG7</td>
<td>HLA-DPA1</td>
<td>GNG11</td>
<td>SUB1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>IL32</td>
<td>CD79A</td>
<td>LDHB</td>
<td>RPS6</td>
<td>RPS27</td>
<td>LGALS2</td>
<td>LYZ</td>
<td>FCER1G</td>
<td>GZMB</td>
<td>CST7</td>
<td>HLA-DRA</td>
<td>SPARC</td>
<td>HSP90B1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>NKG7</td>
<td>CD79B</td>
<td>IL7R</td>
<td>RPL13</td>
<td>RPL32</td>
<td>FTH1</td>
<td>FTL</td>
<td>AIF1</td>
<td>PRF1</td>
<td>B2M</td>
<td>HLA-DRB1</td>
<td>PPBP</td>
<td>HMGB1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>B2M</td>
<td>HLA-DPB1</td>
<td>CD3D</td>
<td>RPS27</td>
<td>RPL31</td>
<td>FCN1</td>
<td>TYROBP</td>
<td>COTL1</td>
<td>CTSW</td>
<td>HLA-C</td>
<td>CST3</td>
<td>SDPR</td>
<td>PCNA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Simple non-parametric tests outperform elaborate ones for this task — the book cites benchmarks to that effect. The ranking is what matters, not the <span class="math inline">\(p\)</span>-values.</p>
</div>
</div>
</div>
</section>
<section id="the-double-dipping-problem" class="slide level2">
<h2>The double-dipping problem</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why those <span class="math inline">\(p\)</span>-values are not real</strong></p>
</div>
<div class="callout-content">
<p>We defined the clusters <strong>using the same data</strong> on which we now test for differential expression. The clustering already maximised between-group separation — so of course the groups differ.</p>
<blockquote>
<p>As the definition of the clusters is based on the same data as used for these statistical tests, the <span class="math inline">\(p\)</span>-values of these tests will be inflated.</p>
</blockquote>
<p>This is <em>selective inference</em>, or “double dipping”. The consequence is not that the markers are wrong — ranking genes by cluster specificity works fine — but that <strong>the significance values are meaningless</strong> and must not be reported as evidence that a cluster is real.</p>
<p>Methods exist that correct for it (e.g.&nbsp;data splitting, or the <code>countsplit</code>/selective-inference literature), but they are not yet standard practice.</p>
</div>
</div>
</div>
<!-- source: sc-best-practices, Annotation / "From cluster DE genes to annotation"
     https://www.sc-best-practices.org/cellular_structure/annotation.html -->
</section>
<section id="which-test-and-does-it-matter" class="slide level2 scrollable">
<h2>Which test, and does it matter?</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong><code>rank_genes_groups</code> takes a <code>method=</code>, and the default is fine</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>method</th>
<th>what it does</th>
<th>note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>wilcoxon</code></td>
<td>rank-sum on normalized values</td>
<td><strong>the recommended default</strong></td>
</tr>
<tr class="even">
<td><code>t-test</code></td>
<td>assumes normality after log</td>
<td>fast, fine in practice</td>
</tr>
<tr class="odd">
<td><code>t-test_overestim_var</code></td>
<td>scanpy’s conservative variant</td>
<td>the historic default</td>
</tr>
<tr class="even">
<td><code>logreg</code></td>
<td>multinomial logistic regression</td>
<td>considers genes jointly, no <span class="math inline">\(p\)</span>-values</td>
</tr>
</tbody>
</table>
<p>Benchmarks consistently find that <strong>simple non-parametric tests do as well as or better than elaborate ones</strong> for marker ranking. The elaborate machinery is aimed at a harder question — between-condition DE — where it belongs, and where we go later in this lecture.</p>
<p>Two practical points that matter more than the choice of test:</p>
<ul>
<li>set <code>use_raw=False</code> and be deliberate about <strong>which layer</strong> you are testing. Testing scaled (z-scored) values is meaningless; test the normalized log values.</li>
<li>one-vs-rest is a different question from one-vs-one. A gene shared by clusters 3 and 7 may fail one-vs-rest for both while being an excellent marker for the pair. <code>groups=</code> and <code>reference=</code> let you ask the pairwise question.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="ranking-is-not-selecting" class="slide level2">
<h2>Ranking is not selecting</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A top-10 list is a starting point, not a result</strong></p>
</div>
<div class="callout-content">
<p><code>rank_genes_groups</code> will always return the top <span class="math inline">\(n\)</span> genes, whether or not the cluster has any markers at all. It has no notion of “this cluster is not distinct”.</p>
<p>So filter on something with meaning, not on rank:</p>
<ul>
<li><strong>log fold change</strong> — an effect size. <code>sc.tl.filter_rank_genes_groups</code> applies a <code>min_fold_change</code> and a <code>min_in_group_fraction</code>.</li>
<li><strong>the fraction of cells expressing it</strong> in the cluster versus outside. A gene detected in 8% of cluster cells is not a marker regardless of its <span class="math inline">\(p\)</span>-value; dropout makes low-detection genes unreliable in exactly the way Bio 3 described.</li>
<li><strong>whether it is a real gene for your purpose.</strong> Ribosomal, mitochondrial and haemoglobin genes dominate marker lists and almost never carry the biological signal you want.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="canonical-pbmc-markers" class="slide level2 scrollable">
<h2>Canonical PBMC markers</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A literature marker set</strong></p>
</div>
<div class="callout-content">
<div id="8007dd11" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a aria-label="1"></a>markers <span class="op">=</span> {</span>
<span id="cb12-2"><a aria-label="2"></a>    <span class="st">"CD4 T"</span>:          [<span class="st">"IL7R"</span>, <span class="st">"CCR7"</span>],</span>
<span id="cb12-3"><a aria-label="3"></a>    <span class="st">"CD8 T"</span>:          [<span class="st">"CD8A"</span>, <span class="st">"CD8B"</span>],</span>
<span id="cb12-4"><a aria-label="4"></a>    <span class="st">"NK"</span>:             [<span class="st">"GNLY"</span>, <span class="st">"NKG7"</span>],</span>
<span id="cb12-5"><a aria-label="5"></a>    <span class="st">"B"</span>:              [<span class="st">"MS4A1"</span>, <span class="st">"CD79A"</span>],</span>
<span id="cb12-6"><a aria-label="6"></a>    <span class="st">"CD14+ Mono"</span>:     [<span class="st">"CD14"</span>, <span class="st">"LYZ"</span>],</span>
<span id="cb12-7"><a aria-label="7"></a>    <span class="st">"FCGR3A+ Mono"</span>:   [<span class="st">"FCGR3A"</span>, <span class="st">"MS4A7"</span>],</span>
<span id="cb12-8"><a aria-label="8"></a>    <span class="st">"Dendritic"</span>:      [<span class="st">"FCER1A"</span>, <span class="st">"CST3"</span>],</span>
<span id="cb12-9"><a aria-label="9"></a>    <span class="st">"Platelet"</span>:       [<span class="st">"PPBP"</span>],</span>
<span id="cb12-10"><a aria-label="10"></a>}</span>
<span id="cb12-11"><a aria-label="11"></a>present <span class="op">=</span> {k: [g <span class="cf">for</span> g <span class="kw">in</span> v <span class="cf">if</span> g <span class="kw">in</span> adata.var_names] <span class="cf">for</span> k, v <span class="kw">in</span> markers.items()}</span>
<span id="cb12-12"><a aria-label="12"></a><span class="bu">print</span>({k: <span class="bu">len</span>(v) <span class="cf">for</span> k, v <span class="kw">in</span> present.items()})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'CD4 T': 2, 'CD8 T': 2, 'NK': 2, 'B': 2, 'CD14+ Mono': 2, 'FCGR3A+ Mono': 2, 'Dendritic': 2, 'Platelet': 1}</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="canonical-pbmc-markers-1" class="slide level2 scrollable">
<h2>Canonical PBMC markers</h2>
<div id="6719895b" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a aria-label="1"></a>sc.pl.dotplot(adata, present, groupby<span class="op">=</span><span class="st">"leiden"</span>, standard_scale<span class="op">=</span><span class="st">"var"</span>, show<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-2"><a aria-label="2"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-11-output-1.png" width="712" height="661"></p>
</figure>
</div>
</div>
</div>
<p>Read it column-block by column-block: each cluster lights up for one marker set. <strong>Dot size</strong> is the fraction of cells expressing; <strong>colour</strong> is mean expression among them. The fraction matters as much as the level — a marker expressed strongly in 5% of a cluster is telling you the cluster is not homogeneous.</p>
</section>
<section id="how-specific-is-a-marker" class="slide level2 scrollable">
<h2>How specific is a marker?</h2>
<div id="1a4b81a1" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a aria-label="1"></a>sc.pl.violin(adata, [<span class="st">"NKG7"</span>, <span class="st">"CD79A"</span>, <span class="st">"LYZ"</span>], groupby<span class="op">=</span><span class="st">"leiden"</span>,</span>
<span id="cb15-2"><a aria-label="2"></a>             rotation<span class="op">=</span><span class="dv">90</span>, show<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-3"><a aria-label="3"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-12-output-1.png" width="1619" height="391"></p>
</figure>
</div>
</div>
</div>
<p><code>CD79A</code> and <code>LYZ</code> are close to ideal: high in one cluster, near zero elsewhere. <code>NKG7</code> is <strong>not</strong> — it is high in several clusters, because NK and cytotoxic T cells share it. That single fact is what misleads the automatic assignment two slides from now.</p>
</section>
<section id="assigning-labels" class="slide level2 scrollable">
<h2>Assigning labels</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From the dot plot to names</strong></p>
</div>
<div class="callout-content">
<div id="bfce92ef" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a aria-label="1"></a>top <span class="op">=</span> pd.DataFrame(adata.uns[<span class="st">"rank_genes_groups"</span>][<span class="st">"names"</span>]).head(<span class="dv">8</span>)</span>
<span id="cb16-2"><a aria-label="2"></a><span class="cf">for</span> cl <span class="kw">in</span> adata.obs[<span class="st">"leiden"</span>].cat.categories:</span>
<span id="cb16-3"><a aria-label="3"></a>    <span class="bu">print</span>(<span class="ss">f"  cluster </span><span class="sc">{</span>cl<span class="sc">:&gt;2}</span><span class="ss">: </span><span class="sc">{</span><span class="st">', '</span><span class="sc">.</span>join(top[cl][:<span class="dv">6</span>])<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cluster  0: CCL5, GZMK, IL32, NKG7, B2M, CTSW
  cluster  1: CD74, HLA-DRA, CD79A, CD79B, HLA-DPB1, MS4A1
  cluster  2: LTB, IL32, LDHB, IL7R, CD3D, JUNB
  cluster  3: MALAT1, RPL32, RPS6, RPL13, RPS27, RPS12
  cluster  4: RPS12, RPS6, RPS27, RPL32, RPL31, RPS25
  cluster  5: CST3, LYZ, LGALS2, FTH1, FCN1, TYMP
  cluster  6: S100A8, S100A9, LYZ, FTL, TYROBP, S100A6
  cluster  7: LST1, FCGR3A, FCER1G, AIF1, COTL1, IFITM2
  cluster  8: NKG7, GNLY, GZMB, PRF1, CTSW, GZMA
  cluster  9: CCL5, NKG7, CST7, B2M, HLA-C, GZMH
  cluster 10: HLA-DPB1, HLA-DPA1, HLA-DRA, HLA-DRB1, CST3, HLA-DQA1
  cluster 11: PF4, GNG11, SPARC, PPBP, SDPR, CD9
  cluster 12: ACTG1, SUB1, HSP90B1, HMGB1, PCNA, PSMB3</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="assigning-labels-1" class="slide level2 scrollable">
<h2>Assigning labels</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Mapping clusters to cell types</strong></p>
</div>
<div class="callout-content">
<div id="39fe0dc8" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a aria-label="1"></a><span class="co"># assign each cluster the marker set whose mean expression is highest in it</span></span>
<span id="cb18-2"><a aria-label="2"></a>scores <span class="op">=</span> {}</span>
<span id="cb18-3"><a aria-label="3"></a><span class="cf">for</span> ct, genes <span class="kw">in</span> present.items():</span>
<span id="cb18-4"><a aria-label="4"></a>    <span class="cf">if</span> genes:</span>
<span id="cb18-5"><a aria-label="5"></a>        sub <span class="op">=</span> adata[:, genes].layers[<span class="st">"log1p_norm"</span>]</span>
<span id="cb18-6"><a aria-label="6"></a>        scores[ct] <span class="op">=</span> np.asarray(sub.mean(axis<span class="op">=</span><span class="dv">1</span>)).ravel()</span>
<span id="cb18-7"><a aria-label="7"></a>score_df <span class="op">=</span> pd.DataFrame(scores, index<span class="op">=</span>adata.obs_names)</span>
<span id="cb18-8"><a aria-label="8"></a>score_df[<span class="st">"leiden"</span>] <span class="op">=</span> adata.obs[<span class="st">"leiden"</span>].values</span>
<span id="cb18-9"><a aria-label="9"></a>per_cluster <span class="op">=</span> score_df.groupby(<span class="st">"leiden"</span>, observed<span class="op">=</span><span class="va">True</span>).mean()</span>
<span id="cb18-10"><a aria-label="10"></a>assignment <span class="op">=</span> per_cluster.idxmax(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-11"><a aria-label="11"></a></span>
<span id="cb18-12"><a aria-label="12"></a>adata.obs[<span class="st">"cell_type"</span>] <span class="op">=</span> adata.obs[<span class="st">"leiden"</span>].<span class="bu">map</span>(assignment).astype(<span class="st">"category"</span>)</span>
<span id="cb18-13"><a aria-label="13"></a><span class="bu">print</span>(assignment.to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>leiden
0               NK
1                B
2            CD4 T
3            CD4 T
4            CD4 T
5       CD14+ Mono
6       CD14+ Mono
7     FCGR3A+ Mono
8               NK
9               NK
10       Dendritic
11        Platelet
12              NK</code></pre>
</div>
</div>
<p>This is a crude automation of what an analyst does by eye. It is shown to make the logic explicit — and, usefully, <strong>to fail visibly</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Look at what it got wrong</strong></p>
</div>
<div class="callout-content">
<p>Compare the assignment above with the marker listing on the previous slide.</p>
<p><strong>Cluster 0</strong> was labelled <code>NK</code>. But its top genes are <code>CCL5, GZMK, IL32, NKG7, B2M, CTSW</code> — <code>GZMK</code> and <code>CTSW</code> are cytotoxic <strong>T</strong> cell markers, and <code>NKG7</code> is shared between NK and CD8 T cells. It is almost certainly an <strong>effector CD8 T</strong> population, and the argmax was misled by the one gene the two types have in common.</p>
<p>Notice also that <strong>no cluster received the <code>CD8 T</code> label at all</strong>, and that several clusters are dominated by ribosomal genes (<code>RPS*</code>, <code>RPL*</code>) — which usually signals either low-quality cells or a resolution that has split a homogeneous population.</p>
<blockquote>
<p>This is exactly why annotation is not automated away. A shared marker is enough to flip a label, and only knowing the biology catches it.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="the-annotated-map" class="slide level2 scrollable">
<h2>The annotated map</h2>
<div id="c1c6b189" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a aria-label="1"></a>sc.pl.umap(adata, color<span class="op">=</span><span class="st">"cell_type"</span>, legend_loc<span class="op">=</span><span class="st">"right margin"</span>, show<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb20-2"><a aria-label="2"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-15-output-1.png" width="639" height="381"></p>
</figure>
</div>
</div>
</div>
<div id="dde58a2f" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a aria-label="1"></a>adata.obs[<span class="st">"cell_type"</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>cell_type
CD4 T           1126
NK               528
CD14+ Mono       503
B                349
FCGR3A+ Mono     149
Dendritic         34
Platelet          11
Name: count, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="automated-annotation" class="slide level2 scrollable">
<h2>Automated annotation</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Three families</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Marker-based classifiers</strong> (Garnett, CellAssign) — take a predefined marker set. Transparent: you know which genes drove the call.</li>
<li><strong>Wide-gene-set classifiers</strong> (CellTypist, Clustifyr) — trained on annotated atlases using thousands of genes. Do not require clustering at all.</li>
<li><strong>Reference mapping</strong> (scArches, Symphony, Azimuth) — embed your data into an existing reference’s latent space and transfer labels from neighbours.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Quality depends on things you do not control</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>the classifier type</strong> — benchmarks find neural networks generally do <em>not</em> beat SVMs or logistic regression here</li>
<li><strong>the training data’s annotation quality</strong> — a classifier trained on coarse labels returns coarse labels</li>
<li><strong>how similar your data is to the training data</strong> — different tissue, protocol or species degrades it sharply</li>
</ol>
<blockquote>
<p>Regard these methods as a starting point rather than an end-point of the annotation process.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="uncertainty" class="slide level2 scrollable">
<h2>Uncertainty</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The most useful output is not the label</strong></p>
</div>
<div class="callout-content">
<p>Reference-mapping methods score each transferred label by how consistent the neighbouring reference cells were. That uncertainty is more informative than the label:</p>
<ul>
<li><strong>progenitor and transitional cells</strong> score uncertain because they genuinely lie between annotated states</li>
<li><strong>an unseen cell type</strong> — present in your query, absent from the reference — also scores uncertain</li>
</ul>
<p>So high uncertainty flags both <em>“the method cannot tell”</em> and <em>“this may be something new”</em>. In a disease-versus-healthy design, uncertainty against a healthy reference is a way of finding disease-specific states.</p>
</div>
</div>
</div>
<!-- =========================================================================
     SOURCE: sc-best-practices, Identifying cellular structure / "Integration"
       https://www.sc-best-practices.org/cellular_structure/integration.html
       NOTE: that chapter leans on R (18 rpy2/%%R references). This deck uses
       the Python path only: harmonypy directly, plus scVI/BBKNN described.
       The synthetic batch effect is ours, not the book's.
     ========================================================================= -->
</section></section>
<section>
<section id="integration" class="title-slide slide level1 center">
<h1>Integration</h1>

</section>
<section id="batch-effects" class="slide level2">
<h2>Batch effects</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The problem</strong></p>
</div>
<div class="callout-content">
<p>Cells from different samples, donors, protocols or sequencing runs differ <em>systematically</em> for reasons that are not biological. Left uncorrected, cells cluster by <strong>batch</strong> rather than by cell type — and you annotate the same cell type twice under different names.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And the fundamental difficulty</strong></p>
</div>
<div class="callout-content">
<p>A batch effect and a biological difference are <strong>not identifiable in general</strong>. If you processed all healthy samples on Monday and all diseased on Tuesday, no algorithm can separate disease from day.</p>
<p>Integration methods work by assuming <em>shared cell types exist across batches</em> and aligning those. When that assumption fails — a cell type genuinely present in only one condition — over-correction <strong>erases the finding</strong>.</p>
</div>
</div>
</div>
</section>
<section id="design-beats-correction" class="slide level2">
<h2>Design beats correction</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The cheapest integration is the one you do not need</strong></p>
</div>
<div class="callout-content">
<p>Because batch and biology are confounded <em>by the design</em>, not by the algorithm, the decisive choices are made before any data exists:</p>
<ul>
<li><strong>Randomise condition across batches.</strong> Never process all cases together and all controls together. If you can only run 8 samples a day, run 4 of each.</li>
<li><strong>Block, and record the blocking.</strong> Whatever you cannot randomise — operator, reagent lot, chip, day — record it in <code>.obs</code>. A covariate you did not record cannot be modelled, and it does not stop existing.</li>
<li><strong>Multiplex where possible.</strong> Cell hashing, or genetic demultiplexing of pooled donors (<code>souporcell</code>, <code>vireo</code>), puts several samples in <em>one</em> reaction, so the batch effect between them is zero by construction. This is the single most effective intervention available.</li>
<li><strong>Replicate at the level you want to generalise to.</strong> Three technical replicates of one donor tell you about the assay. They tell you nothing about people.</li>
</ul>
<p>No integration method recovers information the design destroyed. It can only make the plot look as though it did.</p>
</div>
</div>
</div>
</section>
<section id="same-lesson-as-bio-2" class="slide level2">
<h2>Same lesson as Bio 2</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Replicate at the level you want to generalise to</strong></p>
</div>
<div class="callout-content">
<p>“Split at the level you want to generalise to” and “replicate at the level you want to generalise to” are the same sentence. Cells within a donor are not independent, exactly as strains within a genus are not.</p>
</div>
</div>
</div>
</section>
<section id="a-controlled-demonstration" class="slide level2 scrollable">
<h2>A controlled demonstration</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Manufacture a batch effect we know the truth about</strong></p>
</div>
<div class="callout-content">
<div id="4c86e305" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a aria-label="1"></a>bdata <span class="op">=</span> sc.datasets.pbmc3k()</span>
<span id="cb23-2"><a aria-label="2"></a>sc.pp.filter_cells(bdata, min_genes<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb23-3"><a aria-label="3"></a>sc.pp.filter_genes(bdata, min_cells<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb23-4"><a aria-label="4"></a></span>
<span id="cb23-5"><a aria-label="5"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb23-6"><a aria-label="6"></a>bdata.obs[<span class="st">"batch"</span>] <span class="op">=</span> pd.Categorical(rng.choice([<span class="st">"A"</span>, <span class="st">"B"</span>], bdata.n_obs))</span>
<span id="cb23-7"><a aria-label="7"></a></span>
<span id="cb23-8"><a aria-label="8"></a><span class="co"># batch B up-regulates a random third of genes.</span></span>
<span id="cb23-9"><a aria-label="9"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: it must be *gene*-specific -- a per-cell scaling would be</span></span>
<span id="cb23-10"><a aria-label="10"></a><span class="co"># removed exactly by normalize_total, and produce no batch effect at all.</span></span>
<span id="cb23-11"><a aria-label="11"></a>affected <span class="op">=</span> rng.choice(bdata.n_vars, size<span class="op">=</span>bdata.n_vars <span class="op">//</span> <span class="dv">3</span>, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-12"><a aria-label="12"></a>factor <span class="op">=</span> np.ones(bdata.n_vars)</span>
<span id="cb23-13"><a aria-label="13"></a>factor[affected] <span class="op">=</span> <span class="fl">3.0</span></span>
<span id="cb23-14"><a aria-label="14"></a></span>
<span id="cb23-15"><a aria-label="15"></a>isB <span class="op">=</span> bdata.obs.batch.values <span class="op">==</span> <span class="st">"B"</span></span>
<span id="cb23-16"><a aria-label="16"></a>X <span class="op">=</span> bdata.X.tolil()</span>
<span id="cb23-17"><a aria-label="17"></a>X[isB] <span class="op">=</span> X[isB].multiply(factor).tolil()</span>
<span id="cb23-18"><a aria-label="18"></a>bdata.X <span class="op">=</span> X.tocsr()</span>
<span id="cb23-19"><a aria-label="19"></a></span>
<span id="cb23-20"><a aria-label="20"></a>sc.pp.normalize_total(bdata)</span>
<span id="cb23-21"><a aria-label="21"></a>sc.pp.log1p(bdata)</span>
<span id="cb23-22"><a aria-label="22"></a>sc.pp.highly_variable_genes(bdata, n_top_genes<span class="op">=</span><span class="dv">2000</span>)</span>
<span id="cb23-23"><a aria-label="23"></a>sc.pp.pca(bdata, n_comps<span class="op">=</span><span class="dv">50</span>, mask_var<span class="op">=</span><span class="st">"highly_variable"</span>)</span>
<span id="cb23-24"><a aria-label="24"></a><span class="bu">print</span>(<span class="st">"batches:"</span>, <span class="bu">dict</span>(bdata.obs.batch.value_counts()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>batches: {'B': np.int64(1401), 'A': np.int64(1299)}</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="measuring-the-damage" class="slide level2 scrollable">
<h2>Measuring the damage</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What fraction of a cell’s neighbours share its batch?</strong></p>
</div>
<div class="callout-content">
<div id="b861d97a" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a aria-label="1"></a><span class="kw">def</span> batch_mixing(adata, rep):</span>
<span id="cb25-2"><a aria-label="2"></a>    <span class="co">"""1.0 = fully separated by batch, 0.5 = perfectly mixed."""</span></span>
<span id="cb25-3"><a aria-label="3"></a>    sc.pp.neighbors(adata, use_rep<span class="op">=</span>rep, key_added<span class="op">=</span><span class="st">"tmp"</span>, n_neighbors<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb25-4"><a aria-label="4"></a>    graph <span class="op">=</span> adata.obsp[<span class="st">"tmp_connectivities"</span>]</span>
<span id="cb25-5"><a aria-label="5"></a>    codes <span class="op">=</span> np.asarray(pd.Categorical(adata.obs[<span class="st">"batch"</span>]).codes)</span>
<span id="cb25-6"><a aria-label="6"></a>    same <span class="op">=</span> total <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb25-7"><a aria-label="7"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(adata.n_obs):</span>
<span id="cb25-8"><a aria-label="8"></a>        nb <span class="op">=</span> graph[i].indices</span>
<span id="cb25-9"><a aria-label="9"></a>        <span class="cf">if</span> <span class="bu">len</span>(nb):</span>
<span id="cb25-10"><a aria-label="10"></a>            same <span class="op">+=</span> (codes[nb] <span class="op">==</span> codes[i]).<span class="bu">sum</span>()</span>
<span id="cb25-11"><a aria-label="11"></a>            total <span class="op">+=</span> <span class="bu">len</span>(nb)</span>
<span id="cb25-12"><a aria-label="12"></a>    <span class="cf">return</span> same <span class="op">/</span> total</span>
<span id="cb25-13"><a aria-label="13"></a></span>
<span id="cb25-14"><a aria-label="14"></a></span>
<span id="cb25-15"><a aria-label="15"></a><span class="bu">print</span>(<span class="ss">f"raw PCA : </span><span class="sc">{</span>batch_mixing(bdata, <span class="st">'X_pca'</span>)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>raw PCA : 0.808</code></pre>
</div>
</div>
<p>0.81 against a null of 0.5 — cells overwhelmingly neighbour their own batch. The structure we would cluster on is the batch, not the biology.</p>
</div>
</div>
</div>
</section>
<section id="harmony" class="slide level2 scrollable">
<h2>Harmony</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Correcting in PCA space</strong></p>
</div>
<div class="callout-content">
<p>Harmony iterates between soft-clustering cells and computing, per cluster, a linear correction that removes batch-specific offsets. It adjusts the <strong>embedding</strong>, not the expression matrix — fast, and it leaves your counts untouched.</p>
<div id="3134224b" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a aria-label="1"></a><span class="im">import</span> harmonypy</span>
<span id="cb27-2"><a aria-label="2"></a></span>
<span id="cb27-3"><a aria-label="3"></a></span>
<span id="cb27-4"><a aria-label="4"></a><span class="kw">def</span> harmony_integrate(adata, key, basis<span class="op">=</span><span class="st">"X_pca"</span>, adjusted_basis<span class="op">=</span><span class="st">"X_pca_harmony"</span>, <span class="op">**</span>kw):</span>
<span id="cb27-5"><a aria-label="5"></a>    <span class="co">"""Version-robust stand-in for sc.external.pp.harmony_integrate.</span></span>
<span id="cb27-6"><a aria-label="6"></a></span>
<span id="cb27-7"><a aria-label="7"></a><span class="co">    scanpy &lt;= 1.12 does `Z_corr.T` unconditionally, but harmonypy &gt;= 2</span></span>
<span id="cb27-8"><a aria-label="8"></a><span class="co">    already returns (cells, components) -- so that transpose corrupts the</span></span>
<span id="cb27-9"><a aria-label="9"></a><span class="co">    result. Decide the orientation from the shape instead of assuming it.</span></span>
<span id="cb27-10"><a aria-label="10"></a><span class="co">    """</span></span>
<span id="cb27-11"><a aria-label="11"></a>    X <span class="op">=</span> adata.obsm[basis].astype(np.float64)</span>
<span id="cb27-12"><a aria-label="12"></a>    n_cells, n_comps <span class="op">=</span> X.shape</span>
<span id="cb27-13"><a aria-label="13"></a>    Z <span class="op">=</span> np.asarray(harmonypy.run_harmony(X, adata.obs, key, <span class="op">**</span>kw).Z_corr)</span>
<span id="cb27-14"><a aria-label="14"></a>    <span class="cf">if</span> Z.shape <span class="op">==</span> (n_comps, n_cells):</span>
<span id="cb27-15"><a aria-label="15"></a>        Z <span class="op">=</span> Z.T</span>
<span id="cb27-16"><a aria-label="16"></a>    <span class="cf">if</span> Z.shape <span class="op">!=</span> (n_cells, n_comps):</span>
<span id="cb27-17"><a aria-label="17"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"unexpected Z_corr shape </span><span class="sc">{</span>Z<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-18"><a aria-label="18"></a>    adata.obsm[adjusted_basis] <span class="op">=</span> Z</span>
<span id="cb27-19"><a aria-label="19"></a>    <span class="cf">return</span> adata</span>
<span id="cb27-20"><a aria-label="20"></a></span>
<span id="cb27-21"><a aria-label="21"></a></span>
<span id="cb27-22"><a aria-label="22"></a>harmony_integrate(bdata, <span class="st">"batch"</span>)</span>
<span id="cb27-23"><a aria-label="23"></a><span class="bu">print</span>(<span class="ss">f"harmony : </span><span class="sc">{</span>batch_mixing(bdata, <span class="st">'X_pca_harmony'</span>)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>harmony : 0.499</code></pre>
</div>
</div>
<p><strong>0.81 → 0.50.</strong> Essentially perfect mixing.</p>
</div>
</div>
</div>
</section>
<section id="a-bug-worth-knowing-about" class="slide level2 scrollable">
<h2>A bug worth knowing about</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong><code>sc.external.pp.harmony_integrate</code> is broken with harmonypy 2.x</strong></p>
</div>
<div class="callout-content">
<p>The scanpy wrapper ends with</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a aria-label="1"></a>adata.obsm[adjusted_basis] <span class="op">=</span> harmony_out.Z_corr.T   <span class="co"># scanpy 1.12.4</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That transpose was correct when harmonypy returned <code>(components, cells)</code>. Version 2 returns <code>(cells, components)</code> already, so the transpose produces a <code>(50,)</code> array and AnnData rejects it:</p>
<pre><code>ValueError: Value passed for key 'X_pca_harmony' is of incorrect shape.
Values of obsm must match dimensions ('obs',) of parent.
Value had shape (50,) while it should have had (2700,).</code></pre>
<p><strong>Three ways out:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>fix</th>
<th>trade-off</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>uv add "harmonypy&lt;2"</code></td>
<td>one line; but pins you to old harmonypy</td>
</tr>
<tr class="even">
<td>the shape-guarded helper above</td>
<td>works on both versions; ~8 lines you own</td>
</tr>
<tr class="odd">
<td>call <code>run_harmony</code> inline</td>
<td>fine once, repeats the logic everywhere else</td>
</tr>
</tbody>
</table>
<p>The general lesson: when a library wrapper silently assumes an orientation, <strong>check the shape</strong> rather than trusting it. A transpose bug that raises is the lucky case — one that does not raise gives you a plausible, wrong embedding.</p>
</div>
</div>
</div>
</section>
<section id="before-and-after" class="slide level2 scrollable">
<h2>Before and after</h2>
<div id="3217d6fe" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a aria-label="1"></a>sc.pp.neighbors(bdata, use_rep<span class="op">=</span><span class="st">"X_pca"</span>, n_neighbors<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb31-2"><a aria-label="2"></a>sc.tl.umap(bdata)</span>
<span id="cb31-3"><a aria-label="3"></a>bdata.obsm[<span class="st">"X_umap_raw"</span>] <span class="op">=</span> bdata.obsm[<span class="st">"X_umap"</span>].copy()</span>
<span id="cb31-4"><a aria-label="4"></a></span>
<span id="cb31-5"><a aria-label="5"></a>sc.pp.neighbors(bdata, use_rep<span class="op">=</span><span class="st">"X_pca_harmony"</span>, n_neighbors<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb31-6"><a aria-label="6"></a>sc.tl.umap(bdata)</span>
<span id="cb31-7"><a aria-label="7"></a></span>
<span id="cb31-8"><a aria-label="8"></a>f, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb31-9"><a aria-label="9"></a>axs[<span class="dv">0</span>].scatter(<span class="op">*</span>bdata.obsm[<span class="st">"X_umap_raw"</span>].T, s<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb31-10"><a aria-label="10"></a>               c<span class="op">=</span>pd.Categorical(bdata.obs.batch).codes, cmap<span class="op">=</span><span class="st">"coolwarm"</span>)</span>
<span id="cb31-11"><a aria-label="11"></a>axs[<span class="dv">0</span>].set_title(<span class="st">"before: PCA"</span>)</span>
<span id="cb31-12"><a aria-label="12"></a>axs[<span class="dv">1</span>].scatter(<span class="op">*</span>bdata.obsm[<span class="st">"X_umap"</span>].T, s<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb31-13"><a aria-label="13"></a>               c<span class="op">=</span>pd.Categorical(bdata.obs.batch).codes, cmap<span class="op">=</span><span class="st">"coolwarm"</span>)</span>
<span id="cb31-14"><a aria-label="14"></a>axs[<span class="dv">1</span>].set_title(<span class="st">"after: Harmony"</span>)</span>
<span id="cb31-15"><a aria-label="15"></a><span class="cf">for</span> ax <span class="kw">in</span> axs:</span>
<span id="cb31-16"><a aria-label="16"></a>    ax.set_xticks([])<span class="op">;</span> ax.set_yticks([])</span>
<span id="cb31-17"><a aria-label="17"></a>plt.tight_layout()</span>
<span id="cb31-18"><a aria-label="18"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src="bio4_files/figure-revealjs/cell-20-output-1.png" width="1075" height="415"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-methods-landscape" class="slide level2">
<h2>The methods landscape</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>What to reach for</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>method</th>
<th>corrects</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Harmony</strong></td>
<td>the embedding</td>
<td>fast, strong default, linear</td>
</tr>
<tr class="even">
<td><strong>BBKNN</strong></td>
<td>the <em>graph</em></td>
<td>very fast; modifies neighbours directly</td>
</tr>
<tr class="odd">
<td><strong>scVI / scANVI</strong></td>
<td>latent space</td>
<td>deep generative; handles counts natively; scANVI uses labels</td>
</tr>
<tr class="even">
<td><strong>Scanorama</strong></td>
<td>embedding + expression</td>
<td>panorama stitching; good with partial overlap</td>
</tr>
<tr class="odd">
<td><strong>ComBat</strong></td>
<td>expression</td>
<td>classic bulk method; <code>sc.pp.combat</code>; assumes shared composition</td>
</tr>
</tbody>
</table>
<p>The <strong>scIB</strong> benchmark scores methods jointly on <em>batch removal</em> and <em>biological conservation</em> — because the two trade off, and a method that scores perfectly on the first has usually destroyed the second.</p>
</div>
</div>
</div>
</section>
<section id="deep-generative-integration" class="slide level2">
<h2>Deep generative integration</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>scVI, and why it is different</strong></p>
</div>
<div class="callout-content">
<p>Harmony corrects an embedding that PCA already produced. <strong>scVI</strong> instead fits a generative model directly to the <em>counts</em>:</p>
<ul>
<li>each cell gets a low-dimensional latent vector <span class="math inline">\(z_c\)</span></li>
<li>observed counts are modelled as negative-binomial draws conditioned on <span class="math inline">\(z_c\)</span> <strong>and</strong> a batch covariate</li>
<li>because batch enters the model explicitly, <span class="math inline">\(z_c\)</span> is batch-free by construction</li>
</ul>
<p>Because it models counts rather than a transformed matrix, it handles the mean–variance structure from lecture 3 natively instead of transforming it away.</p>
<p><strong>scANVI</strong> extends it with cell-type labels where you have them — semi-supervised, so known labels shape the latent space and can then be transferred to unlabelled cells.</p>
<p>The cost is a neural network: slower, needs a GPU to be comfortable at scale, and has hyperparameters that a linear method does not.</p>
</div>
</div>
</div>
</section>
<section id="over-correction" class="slide level2">
<h2>Over-correction</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The failure mode nobody sees</strong></p>
</div>
<div class="callout-content">
<p>Integration methods align shared populations across batches. If a cell type is genuinely <strong>present in one condition only</strong> — a disease-specific state, say — the algorithm has no counterpart to align it to, and its most likely behaviour is to blend it into the nearest shared population.</p>
<p>The result is a clean, well-mixed UMAP in which <strong>your finding has been removed</strong>, and nothing in the output indicates it happened.</p>
<p>Mitigations: check that known condition-specific populations survive; compare cluster composition before and after; and use benchmark metrics (scIB) that score <em>biological conservation</em> alongside batch removal rather than batch removal alone.</p>
</div>
</div>
</div>
</section>
<section id="how-integration-is-benchmarked" class="slide level2 scrollable">
<h2>How integration is benchmarked</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Two scores that must be read together</strong></p>
</div>
<div class="callout-content">
<p>The mixing statistic we measured — 0.808 <span class="math inline">\(\rightarrow\)</span> 0.499 — is a <strong>batch-removal</strong> score, and on its own it is dangerously easy to maximise. Replacing the embedding with random noise scores perfectly.</p>
<p>So scIB reports both families and combines them:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>batch correction</strong></th>
<th><strong>biological conservation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kBET, graph iLISI</td>
<td>ARI / NMI against known labels</td>
</tr>
<tr class="even">
<td>graph connectivity</td>
<td>isolated-label F1 — <em>does the rare type survive?</em></td>
</tr>
<tr class="odd">
<td>PCR comparison</td>
<td>cell-cycle variance conservation</td>
</tr>
<tr class="even">
<td></td>
<td>trajectory conservation</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{overall} = 0.6 \times \text{bio conservation} + 0.4 \times \text{batch removal}\]</span></p>
<p><strong>The isolated-label metrics are the ones to watch</strong>, because they measure precisely the failure on the previous slide: whether a population present in only one batch is still recognisable afterwards.</p>
</div>
</div>
</div>
</section>
<section id="what-the-benchmark-found" class="slide level2">
<h2>What the benchmark found</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>No method wins everywhere</strong></p>
</div>
<div class="callout-content">
<p>No method wins everywhere. Broadly: for <strong>simple batch effects</strong>, Harmony is fast and hard to beat; for <strong>atlas-scale</strong> integration across many studies, scVI and scANVI rank highest; <strong>BBKNN</strong> is the cheapest and adjusts only the graph. And the more aggressive the correction, the more biological signal it costs — the trade-off is visible directly in the two columns.</p>
</div>
</div>
</div>
<!-- =========================================================================
     SOURCE: sc-best-practices, Conditions / "Differential gene expression"
       https://www.sc-best-practices.org/conditions/differential_gene_expression.html
       + "Compositional analysis"
       https://www.sc-best-practices.org/conditions/compositional.html
       Pseudoreplication argument: Squair et al. 2021, doi 10.1038/s41467-021-25960-2
     ========================================================================= -->
</section></section>
<section>
<section id="conditions" class="title-slide slide level1 center">
<h1>Conditions</h1>

</section>
<section id="the-question-changes" class="slide level2">
<h2>The question changes</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From “what cells are here?” to “what changed?”</strong></p>
</div>
<div class="callout-content">
<p>With cell types annotated across several samples, the biological questions become:</p>
<ol type="1">
<li><strong>Differential expression</strong> — within a cell type, which genes differ between conditions?</li>
<li><strong>Compositional</strong> — did the <em>proportions</em> of cell types change?</li>
</ol>
<p>Both are comparisons <strong>between samples</strong>, and that is what makes them statistically different from everything so far.</p>
</div>
</div>
</div>
</section>
<section id="why-per-cell-tests-are-wrong" class="slide level2">
<h2>Why per-cell tests are wrong</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Pseudoreplication</strong></p>
</div>
<div class="callout-content">
<p>The tempting analysis: take all T cells from diseased donors and all from healthy, run a Wilcoxon test per gene across cells. With 10 000 cells you get spectacular <span class="math inline">\(p\)</span>-values.</p>
<p>They are <strong>wrong</strong>, because cells from one donor are not independent observations. Your real sample size is the <strong>number of donors</strong>, not the number of cells.</p>
<p><span class="math display">\[n = 6 \text{ donors} \quad \text{not} \quad n = 10{,}000 \text{ cells}\]</span></p>
<p>Treating cells as replicates inflates significance by orders of magnitude. This is pseudoreplication, and it is one of the most common errors in published single-cell analyses.</p>
</div>
</div>
</div>
</section>
<section id="pseudobulk" class="slide level2 scrollable">
<h2>Pseudobulk</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sum counts within (sample, cell type)</strong></p>
</div>
<div class="callout-content">
<p>Collapse each donor’s cells of a given type into one profile, then use well-understood bulk RNA-seq methods on the result.</p>
<div id="b19c9a2e" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a aria-label="1"></a>rng2 <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb32-2"><a aria-label="2"></a>adata.obs[<span class="st">"donor"</span>] <span class="op">=</span> pd.Categorical(rng2.choice([<span class="st">"d1"</span>, <span class="st">"d2"</span>, <span class="st">"d3"</span>, <span class="st">"d4"</span>], adata.n_obs))</span>
<span id="cb32-3"><a aria-label="3"></a></span>
<span id="cb32-4"><a aria-label="4"></a>counts <span class="op">=</span> pd.DataFrame(</span>
<span id="cb32-5"><a aria-label="5"></a>    adata.layers[<span class="st">"counts"</span>].toarray(), index<span class="op">=</span>adata.obs_names, columns<span class="op">=</span>adata.var_names</span>
<span id="cb32-6"><a aria-label="6"></a>)</span>
<span id="cb32-7"><a aria-label="7"></a>pseudobulk <span class="op">=</span> counts.groupby(</span>
<span id="cb32-8"><a aria-label="8"></a>    [adata.obs[<span class="st">"donor"</span>], adata.obs[<span class="st">"cell_type"</span>]], observed<span class="op">=</span><span class="va">True</span></span>
<span id="cb32-9"><a aria-label="9"></a>).<span class="bu">sum</span>()</span>
<span id="cb32-10"><a aria-label="10"></a></span>
<span id="cb32-11"><a aria-label="11"></a><span class="bu">print</span>(<span class="st">"pseudobulk shape:"</span>, pseudobulk.shape, <span class="st">" = (donor x cell type) x genes"</span>)</span>
<span id="cb32-12"><a aria-label="12"></a>pseudobulk.iloc[:<span class="dv">4</span>, :<span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>pseudobulk shape: (28, 9713)  = (donor x cell type) x genes</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">index</th>
<th data-quarto-table-cell-role="th">NOC2L</th>
<th data-quarto-table-cell-role="th">HES4</th>
<th data-quarto-table-cell-role="th">ISG15</th>
<th data-quarto-table-cell-role="th">C1orf159</th>
<th data-quarto-table-cell-role="th">TNFRSF18</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">donor</th>
<th data-quarto-table-cell-role="th">cell_type</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th rowspan="4" data-quarto-table-cell-role="th" data-valign="top">d1</th>
<th data-quarto-table-cell-role="th">B</th>
<td>5.0</td>
<td>2.0</td>
<td>35.0</td>
<td>0.0</td>
<td>2.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CD14+ Mono</th>
<td>8.0</td>
<td>17.0</td>
<td>268.0</td>
<td>1.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">CD4 T</th>
<td>35.0</td>
<td>1.0</td>
<td>248.0</td>
<td>4.0</td>
<td>17.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Dendritic</th>
<td>1.0</td>
<td>0.0</td>
<td>33.0</td>
<td>0.0</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The matrix went from ~2 600 cells to a few dozen rows — and those rows <em>are</em> independent replicates.</p>
</div>
</div>
</div>
</section>
<section id="pseudobulk-1" class="slide level2">
<h2>Pseudobulk</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Why this is the recommended default</strong></p>
</div>
<div class="callout-content">
<ul>
<li>restores a correct notion of replication, so <span class="math inline">\(p\)</span>-values mean something</li>
<li>lets you use <strong>edgeR</strong>, <strong>DESeq2</strong> or <strong>limma</strong> — two decades of careful bulk methodology</li>
<li>averages away dropout, which was never informative for this question</li>
<li>vastly fewer tests, so much less multiple-testing burden</li>
</ul>
<p><strong>The cost:</strong> you lose within-cell-type heterogeneity, and you need enough cells per (sample, type) for the sum to be stable — typically at least 10–20.</p>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>When per-cell models are legitimate</strong></p>
</div>
<div class="callout-content">
<p>Mixed models with a random effect per donor (<code>MAST</code> with a donor term, <code>glmmTMB</code>, <code>NEBULA</code>) do model the dependency properly. They are slower and harder to get right, but they are the honest alternative when you genuinely need cell-level resolution.</p>
</div>
</div>
</div>
</section>
<section id="how-many-samples" class="slide level2">
<h2>How many samples?</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Cells are cheap; donors are the experiment</strong></p>
</div>
<div class="callout-content">
<p>Once you accept that <span class="math inline">\(n\)</span> is the number of <strong>samples</strong>, the arithmetic becomes uncomfortable:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>donors per group</th>
<th>what you can realistically detect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>nothing. You cannot estimate within-group variance at all</td>
</tr>
<tr class="even">
<td>3</td>
<td>very large, consistent effects only</td>
</tr>
<tr class="odd">
<td>5–6</td>
<td>the usual floor for a publishable DE analysis</td>
</tr>
<tr class="even">
<td>10+</td>
<td>moderate effects; some ability to model covariates</td>
</tr>
</tbody>
</table>
<p><strong>Sequencing 50 000 cells from 3 donors does not give you <span class="math inline">\(n = 50{,}000\)</span>.</strong> It gives you <span class="math inline">\(n = 3\)</span>, measured precisely. Precision on each sample is not a substitute for having samples — it reduces measurement error, not biological variance, and biological variance is what the test is about.</p>
<p>Where extra cells <em>do</em> help: rare cell types. If a population is 1% of the sample, 50 000 cells gives 500 of them and a stable pseudobulk sum; 2 000 cells gives 20, which is not enough to sum reliably. <strong>Depth buys you cell types; replication buys you conclusions.</strong></p>
</div>
</div>
</div>
</section>
<section id="effect-size-not-just-significance" class="slide level2">
<h2>Effect size, not just significance</h2>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A ranked <span class="math inline">\(p\)</span>-value list is the wrong output</strong></p>
</div>
<div class="callout-content">
<p>With enough cells, tiny differences become significant, so the top of a <span class="math inline">\(p\)</span>-value-ranked list fills with highly expressed genes showing a 1.05-fold change. Statistically real, biologically uninteresting.</p>
<ul>
<li><strong>Rank by, or at least threshold on, log fold change</strong> alongside adjusted <span class="math inline">\(p\)</span>. A volcano plot exists to make you look at both axes at once.</li>
<li><strong>Shrink the estimates.</strong> Low-expression genes give wildly variable fold changes; <code>DESeq2::lfcShrink</code> and edgeR’s empirical Bayes moderation pull unreliable estimates toward zero, which is why their rankings are more reproducible.</li>
<li><strong>Beware composition shifts.</strong> If one cell type expands dramatically, pseudobulk library composition changes, and genes can appear differential through normalization alone. This is the compositional problem from the next slide, arriving in the DE results.</li>
<li><strong>Report the direction and the magnitude</strong>, not a count of significant genes. “1 847 genes were differentially expressed” is not a finding.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="compositional-analysis" class="slide level2">
<h2>Compositional analysis</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Proportions are not independent</strong></p>
</div>
<div class="callout-content">
<p>“The fraction of B cells doubled in disease” sounds simple. It is not, because proportions are <strong>compositional</strong>: they sum to 1, so <em>one cell type increasing forces every other to decrease</em>.</p>
<p>Test each cell type’s proportion separately and a single expanding population produces apparent significant depletion in all the others.</p>
<p>Methods designed for this — <strong>scCODA</strong>, <strong>tascCODA</strong>, or a centred-log-ratio transform followed by a standard test — model the constraint explicitly. <code>scCODA</code> additionally accounts for the low number of samples by being Bayesian about it.</p>
</div>
</div>
</div>
</section>
<section id="multiple-testing" class="slide level2">
<h2>Multiple testing</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The scale of the problem</strong></p>
</div>
<div class="callout-content">
<p>A differential expression analysis over 20 000 genes × 10 cell types is <strong>200 000 tests</strong>. At <span class="math inline">\(\alpha = 0.05\)</span> you expect 10 000 false positives by chance alone.</p>
<ul>
<li><strong>Benjamini-Hochberg FDR</strong> is the convention; control at 5% FDR, not 5% per test</li>
<li>filter to expressed genes <em>first</em> — testing a gene that is zero everywhere wastes power</li>
<li>and remember the double-dipping problem from the annotation section: if the <em>cell types themselves</em> were defined from this data, the correction does not rescue you</li>
</ul>
</div>
</div>
</div>
<!-- source: sc-best-practices, Conditions / "Gene set enrichment and pathway analysis"
     https://www.sc-best-practices.org/conditions/gsea_pathway.html -->
</section>
<section id="from-genes-to-pathways" class="slide level2 scrollable">
<h2>From genes to pathways</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>A list of 300 genes is not a finding</strong></p>
</div>
<div class="callout-content">
<p>Differential expression hands you a ranked gene list. Interpreting it one gene at a time is both laborious and statistically dubious — you are eyeballing the top of a list you already know is enriched for noise.</p>
<p><strong>Gene set enrichment</strong> asks instead whether genes belonging to a known set — a pathway, a GO term, a published signature — are shifted systematically towards the top of the ranking.</p>
<ul>
<li><strong>ORA</strong> (over-representation) — take the significant genes, test each set with a hypergeometric test. Simple; throws away the ranking and depends entirely on your cut-off.</li>
<li><strong>GSEA</strong> — walk the <em>whole</em> ranked list and accumulate a running score. Uses all the data, no arbitrary threshold.</li>
<li><strong>decoupleR / PROGENy</strong> — score pathway <em>activity</em> per cell from weighted signatures, rather than testing sets after the fact.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Two traps</strong></p>
</div>
<div class="callout-content">
<p>Gene sets are <strong>overlapping and redundant</strong> — a hundred “significant” GO terms may all reflect one signal. And the databases are biased toward well-studied biology, so an enrichment result partly measures <em>what people have studied</em>, not what your cells are doing.</p>
</div>
</div>
</div>
<!-- source: sc-best-practices Parts IV-VI (trajectories, mechanisms, spatial) --
     named here as pointers only; not covered in this series -->
</section>
<section id="what-this-series-does-not-cover" class="slide level2">
<h2>What this series does not cover</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The rest of the book</strong></p>
</div>
<div class="callout-content">
<p>The source text continues well past where we stop. Worth knowing the names:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>topic</th>
<th>question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Trajectory inference</strong></td>
<td>can cells be ordered along a developmental path? (pseudotime, RNA velocity, lineage tracing)</td>
</tr>
<tr class="even">
<td><strong>Gene regulatory networks</strong></td>
<td>which transcription factors drive which programmes?</td>
</tr>
<tr class="odd">
<td><strong>Cell-cell communication</strong></td>
<td>which ligand-receptor pairs link which cell types?</td>
</tr>
<tr class="even">
<td><strong>Chromatin accessibility</strong></td>
<td>scATAC-seq: which regions are open?</td>
</tr>
<tr class="odd">
<td><strong>Spatial omics</strong></td>
<td>where in the tissue is each cell?</td>
</tr>
<tr class="even">
<td><strong>Multimodal integration</strong></td>
<td>RNA + protein + chromatin in the same cell</td>
</tr>
</tbody>
</table>
<p>Each is a chapter at <a href="https://www.sc-best-practices.org" class="uri">https://www.sc-best-practices.org</a>, and each rests on exactly the preprocessing and clustering covered in these two lectures.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="wrap-up" class="title-slide slide level1 center">
<h1>Wrap-up</h1>

</section>
<section id="the-pipeline-continued" class="slide level2">
<h2>The pipeline, continued</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>From lecture 3 to here</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<thead>
<tr class="header">
<th>step</th>
<th>function</th>
<th>output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>clustering</td>
<td><code>sc.tl.leiden</code></td>
<td>anonymous groups</td>
</tr>
<tr class="even">
<td>markers</td>
<td><code>sc.tl.rank_genes_groups</code></td>
<td>ranked genes per group</td>
</tr>
<tr class="odd">
<td>annotation</td>
<td>marker sets + judgement</td>
<td>named cell types</td>
</tr>
<tr class="even">
<td>integration</td>
<td><code>harmonypy</code>, scVI, BBKNN</td>
<td>batch-free embedding</td>
</tr>
<tr class="odd">
<td>DE</td>
<td>pseudobulk + edgeR/DESeq2</td>
<td>genes changed per type</td>
</tr>
<tr class="even">
<td>composition</td>
<td>scCODA</td>
<td>populations changed</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="what-to-take-away" class="slide level2">
<h2>What to take away</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Four things</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Clusters are hypotheses.</strong> The resolution parameter has no correct value; we saw 6 to 15 clusters from the same graph.</li>
<li><strong>Annotation is the least automatable step</strong> in the field, and the quality of automated methods depends on training data you did not choose.</li>
<li><strong>Batch and biology are not identifiable in general.</strong> Integration works by assumption, and over-correction destroys real findings silently.</li>
<li><strong>Your sample size is the number of donors.</strong> Not the number of cells. Pseudobulk before you test.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>And the one that connects them</strong></p>
</div>
<div class="callout-content">
<p>Every step reuses the data that defined the previous step. Clusters defined from expression, tested for differential expression; cell types defined from markers, then used to compare conditions. <strong>Selective inference is everywhere in this pipeline</strong>, and mostly uncorrected.</p>
</div>
</div>
</div>
</section>
<section id="exercises" class="slide level2">
<h2>Exercises</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Try these</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li>Run Leiden at resolution 0.1 and 5.0. At what point do the clusters stop corresponding to anything in the dot plot?</li>
<li>Sub-cluster only the T cells (<code>adata[adata.obs.cell_type == "CD4 T"]</code>) and re-run the pipeline. Do you recover naive vs memory structure?</li>
<li>In the batch demo, change the affected fraction from 1/3 to 1/50. At what point does Harmony stop being needed — and how would you know without the ground truth?</li>
<li>Build the pseudobulk matrix with <code>mean</code> instead of <code>sum</code>. Why is <code>sum</code> the right choice for count-based DE methods?</li>
<li>Take one cluster, split it randomly in half, and run <code>rank_genes_groups</code> between the halves. You should find “significant” genes. Explain why, in terms of the double-dipping section.</li>
<li>Compare <code>sc.pp.combat</code> with Harmony on the synthetic batch data using <code>batch_mixing</code>. Does correcting the expression matrix beat correcting the embedding?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="further-reading" class="slide level2 scrollable">
<h2>Further reading</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Sources</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Heumos, Schaar, Lance et al.</strong>, <em>Best practices for single-cell analysis across modalities</em>, <strong>Nature Reviews Genetics</strong> 24, 2023. <a href="https://doi.org/10.1038/s41576-023-00586-w" class="uri">https://doi.org/10.1038/s41576-023-00586-w</a></li>
<li><strong>Traag, Waltman &amp; van Eck</strong>, <em>From Louvain to Leiden: guaranteeing well-connected communities</em>, <strong>Scientific Reports</strong> 9, 2019. <a href="https://doi.org/10.1038/s41598-019-41695-z" class="uri">https://doi.org/10.1038/s41598-019-41695-z</a></li>
<li><strong>Korsunsky et al.</strong>, <em>Fast, sensitive and accurate integration of single-cell data with Harmony</em>, <strong>Nature Methods</strong> 16, 2019. <a href="https://doi.org/10.1038/s41592-019-0619-0" class="uri">https://doi.org/10.1038/s41592-019-0619-0</a></li>
<li><strong>Luecken et al.</strong>, <em>Benchmarking atlas-level data integration in single-cell genomics</em> (scIB), <strong>Nature Methods</strong> 19, 2022. <a href="https://doi.org/10.1038/s41592-021-01336-8" class="uri">https://doi.org/10.1038/s41592-021-01336-8</a></li>
<li><strong>Squair et al.</strong>, <em>Confronting false discoveries in single-cell differential expression</em>, <strong>Nature Communications</strong> 12, 2021. <a href="https://doi.org/10.1038/s41467-021-25960-2" class="uri">https://doi.org/10.1038/s41467-021-25960-2</a> — the pseudoreplication paper</li>
<li><strong>Büttner et al.</strong>, <em>scCODA is a Bayesian model for compositional single-cell data analysis</em>, <strong>Nature Communications</strong> 12, 2021. <a href="https://doi.org/10.1038/s41467-021-27150-6" class="uri">https://doi.org/10.1038/s41467-021-27150-6</a></li>
<li><strong>Lähnemann et al.</strong>, <em>Eleven grand challenges in single-cell data science</em>, <strong>Genome Biology</strong> 21, 2020. <a href="https://doi.org/10.1186/s13059-020-1926-6" class="uri">https://doi.org/10.1186/s13059-020-1926-6</a></li>
</ul>
</div>
</div>
</div>
</section>
<section id="coming-next" class="slide level2">
<h2>Coming next</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The other half of the series</strong></p>
</div>
<div class="callout-content">
<p>Lectures 1 and 2 go back to <strong>sequences</strong> — the layer beneath the count matrix:</p>
<ul>
<li><strong>Bio 1</strong> — biological data and sequence alignment; dynamic programming, Needleman-Wunsch and Smith-Waterman</li>
<li><strong>Bio 2</strong> — homology search, why BLAST exists, and machine learning over <span class="math inline">\(k\)</span>-mers</li>
</ul>
<p>Source: <strong>An Introduction to Applied Bioinformatics</strong> (Caporaso), <a href="https://readiab.org" class="uri">https://readiab.org</a></p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/socket.io.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/multiplex.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'multiplex': {"url":"https://mplex.vitv.ly","secret":null,"id":"65eb5618ea8b9f655a7ebd875e440447a2ed3bbc62868fa399c9640d8dc784d1"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dslnu\.github\.io\/data_analytics\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>